### ISSUE TITLE
how to proxy php-fpm? 

### ISSUE THREAD

**Issue by Vortexxxx** [jwilder/nginx-proxy#1000]
## docker-compose.yaml

```
version: '2'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment: 
      - DEFAULT_HOST=php

  php:
    image: php:5.6.32-fpm-alpine3.4
    environment: 
      - VIRTUAL_PROTO=fastcgi
      - VIRTUAL_HOST=php
      
  nginx: 
    image: openresty/openresty:alpine
    ports: 
      - "81:80"
    volumes: 
      - "~/Desktop/nginx-proxy:/nginx-proxy"

```
The file definition three services,  `nginx` is all Traffic entrance service,  `nginx-proxy` to proxy only php-fpm.    

The php service simple return the hostname , like this : `Hello, I am 0d571ba83bb6`. It listening on 9000 port.

When I will direct traffic to php, it's work, nginx.conf like `fastcgi_pass  php:9000;`, return `Hello, I am 0d571ba83bb6` 

but  when I will traffic to `nginx-proxy` , nginx.conf like `fastcgi_pass  nginx-proxy:80`, I get a error , like `2017/12/13 03:41:53 [error] 110#110: *69 upstream sent unsupported FastCGI protocol version: 72 while reading response header from upstream, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.25.0.3:80", host: "localhost"`

I don't know what happened and how to get it to work ?
