### ISSUE TITLE
Https Connection refused but http works fine

### ISSUE THREAD

**Issue by donicrosby** [jwilder/nginx-proxy#1002]
I'm having an issue where the proxy is refusing https connections, I'm not sure what settings I need to set up to allow it to enable https. I have the proxy listening on two ports that are forwarded from my router. The router is fine as I can use https fine on other websites. I have flipped the listening ports and when I set the 443 forward to the http port it also works fine. I'm using the lets encrypt companion as well if that changes anything.

**Comment by TemaSM** [comment]
@donicrosby I had the same 'issue', but fixed it by exposing `nginx-proxy`'s 443 port as well as 80:
`docker run -d -p 80:80 -p 443:443 -v /var/run/docker.sock:/tmp/docker.sock:ro jwilder/nginx-proxy`
or in `docker-compose.yml`:
```yml
 nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
```
Hope it will help somehow
