### ISSUE TITLE
proxying https 9443 port is not working

### ISSUE THREAD

**Issue by sgargel** [jwilder/nginx-proxy#1007]
I've trouble proxying a websphere-traditional container.

This is the `nginix-proxy` part of docker-compose.yml:
```
version: '3'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginix-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: always
```
I start my container with:
`docker run --name websphere -e VIRTUAL_HOST=websphere.docker.mydomain.com -e VIRTUAL_PROTO=https -e VIRTUAL_PORT=9443 --expose 9443 myrepo/myimage:latest`

This is the conf generated for `websphere`:
```
upstream websphere.docker.mydomain.com {
}
server {
	server_name websphere.docker.mydomain.com;
	listen 80 ;
	access_log /var/log/nginx/access.log vhost;
	location / {
		proxy_pass https://websphere.docker.mydomain.com;
	}
}
```

AFAIK `websphere` container is exposing ports 9043 and 9443 but only 9443 should be considered by nginix because of `VIRTUAL_PORT=9443` variable.
