### ISSUE TITLE
Can't get it to proxy to my exposed port, only says 'It works!'

### ISSUE THREAD

**Issue by IAMtheIAM** [jwilder/nginx-proxy#1023]
I followed the instructions and it says "It works!" when i visit my page.

my docker-compose

```
version: "3"
services:
    makepdf:
        image: "myreg/myimg:1.0.0"
        working_dir: /home/node/app
        command: [sh, -c, "npm start"]
        ports:
         - "6060:6060" # HOST:CONTAINER
        environment:
          - NODE_ENV=development
          - WEB_PORTS=6060
          - VITRUAL_PORT=6060
```

so if I understand correctly, I deploy that to the docker swarm using `docker stack deploy ...`

then its running on my host at `:6060`, i can confirm by `curl http://localhost:6060` and see my app response.

Then I do
```
docker run -d -e VIRTUAL_HOST=myapp.westus.cloudapp.azure.com \
              -e LETSENCRYPT_HOST=myapp.westus.cloudapp.azure.com \
              -e LETSENCRYPT_EMAIL=me@email.com \
              -e VIRTUAL_PORT=6060 \
              --network=webproxy \
              --name app \
              httpd:alpine
```

But it never forwards the request to my app. It just says "It works!" What am i missing? Thanks
