### ISSUE TITLE
Confused with setup nginx-proxy - phpFpm - multiple sites... (not issue)

### ISSUE THREAD

**Issue by perarg** [jwilder/nginx-proxy#1039]
I am reading and experimenting about 4 days now, please help me with mess in my brain. I have the following setup in my host machine.
`~$ docker ps -a`
>php:5.6-33-fpm-alpine
>jwilder/nginx-proxy
>mariadb:latest

In docker-compose.yml file for the nginx-proxy and php-fpm containers i have the following:
```yml
version: "3.3"
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: always
    ports:
      - 80:80
    volumes:
      - main-webserver-html:/usr/share/nginx/html
      - main-webserver-logs:/var/log/nginx
      - main-webserver-conf:/etc/nginx
      - main-webserver-vhosts:/etc/nginx/conf.d
      - main-webserver-certs:/etc/nginx/certs
      - main-webserver-htpasswd:/etc/nginx/htpasswd
      - ./nginx.tmpl:/app/nginx.tmpl
      - /var/run/docker.sock:/tmp/docker.sock:ro

  php-fpm:
    image: php:5.6.33-fpm-alpine
    container_name: php5.6
    environment:
      - VIRTUAL_HOST=example.com
      - VIRTUAL_ROOT=/var/www/html
      - VIRTUAL_PORT=9000
      - VIRTUAL_PROTO=fastcgi
    restart: always
    ports:
      - 9000
    volumes:
      - ~/sites:/var/www/html

volumes:
  main-webserver-html:
  main-webserver-logs:
  main-webserver-conf:
  main-webserver-vhosts:
  main-webserver-certs:
  main-webserver-htpasswd:

networks:
  default:
    external:
      name: nginx-proxy
```

If i open my browser to example.com, i get the "Welcome to nginx!" page...
In nginx-proxy container, `~$docker exec -it nginx-proxy cat /etc/nginx/conf.d/default.conf` i get the following:
```
upstream example.com {
				## Can be connect with "nginx-proxy" network
			# php5.6
			server 172.18.0.3:9000;
}
server {
	server_name example.com;
	listen 80 ;
	access_log /var/log/nginx/access.log vhost;
	location / {
		root   /var/www/html;
		include fastcgi.conf;
		fastcgi_pass example.com;
	}
}
```
After a lot of searching i finally found that the folder for the files are in nginx-proxy container at /usr/share/nginx/html

This is the point i need your help and guidance. I have two or more websites need php and mysql. I have a container with mariadb so every website will use this db engine. I just have to create new databases and new users. So far so good.

* What do i have to do with php-fpm containers ?
* Can i have just a php-fpm7 and a php-fpm5.6 containers and somehow i can set every website to use one or other ?
* Or do i have to create a new php-fpm container for every website i want to run ?
* Finally, in both scenarios, how can i manage each website's files if they are stored in nginx-proxy single container ?
