### ISSUE TITLE
Letsencrypt certificate's files don't create just with LETSENCRYPT env, needs a hack

### ISSUE THREAD

**Issue by perarg** [jwilder/nginx-proxy#1057]
Hello, i use docker-compose.yml for nginx-proxy and for letsencrypt companion.

```
version: '3'
services:
  proxy:
    image: 'jwilder/nginx-proxy:alpine'
    container_name: 'proxy'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - '/var/run/docker.sock:/tmp/docker.sock:ro'
      - './vhosts:/etc/nginx/vhost.d'
      - './config:/etc/nginx/conf.d'
      - './certs:/etc/nginx/certs'
      - './webroot:/usr/share/nginx/html'
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true"

  letsencrypt:
    image: 'jrcs/letsencrypt-nginx-proxy-companion'
    container_name: 'letsencrypt'
    depends_on:
      - proxy
    environment:
      NGINX_PROXY_CONTAINER: proxy
      NGINX_DOCKER_GEN_CONTAINER: proxy
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      - './vhosts:/etc/nginx/vhost.d'
      - './config:/etc/nginx/conf.d'
      - './certs:/etc/nginx/certs'
      - './webroot:/usr/share/nginx/html'

networks:
  default:
    external:
      name: ngproxy-net
```

When i create a new container through docker composer again the SSL Certificate doesn't created. My docker compose file for example is the following. 

```
version: '3'
services:
  my-app:
    image: nginx:alpine
    container_name: my-app
#   expose:
#     - 80
#     - 443
    volumes:
      - './config:/etc/nginx/conf.d'
      - './html:/usr/share/nginx/html' 
    environment:
      VIRTUAL_HOST: my-app.com
#     VIRTUAL_PORT: 443
#     VIRTUAL_PROTO: https
      LETSENCRYPT_HOST: my-app.com
      LETSENCRYPT_EMAIL: 'myemail@example.com'

networks:
  default:
    external:
      name: ngproxy-net
```

When i comment out the above lines, the cert files are created without problem. And after that i comment these lines again and restart the container. After that everything works great. Why do i have to do that ?
