### ISSUE TITLE
Problem with two expose ports

### ISSUE THREAD

**Issue by flomsk** [jwilder/nginx-proxy#1066]
Hello there!
I have a docker app that exposes two ports.
So my compose config is
```
  test-app:
    build: test-app
    restart: on-failure
    entrypoint: /root/start.sh
    volumes:
      - /etc/localtime:/etc/localtime:ro
    expose:
      - "8545"
      - "8546"
    environment:
      VIRTUAL_HOST: "test1.example.com:8546,test2.example.com:8545"
      LETSENCRYPT_HOST: "test1.example.com,test2.example.com"

networks:
  default:
    external:
      name: webproxy
```
And nginx template parse it like that
```
# test2.example.com:8545
upstream test2.example.com:8545 {
        ## Can be connect with "webproxy" network
    server 172.19.0.8 down;
}
server {
  server_name test2.example.com:8545;
  listen 80 ;
  access_log /var/log/nginx/access.log vhost;
  include /etc/nginx/vhost.d/default;
  location / {
    proxy_pass http://test2.example.com:8545;
  }
}
# test1.example.com:8546
upstream test1.example.com:8546 {
        ## Can be connect with "webproxy" network
    server 172.19.0.8 down;
}
server {
  server_name test1.example.com:8546;
  listen 80 ;
  access_log /var/log/nginx/access.log vhost;
  include /etc/nginx/vhost.d/default;
  location / {
    proxy_pass http://test1.example.com:8546;
  }
}
```
Servername has a port and this is a trouble. Also I dont sure that upstream has a right name.
Can you please provide the correct nginx template to work with more than one exposed port.
Thank you
