### ISSUE TITLE
No SSL and nginx -s reload, exit status 1 with limesurvey image

### ISSUE THREAD

**Issue by VincentGuyader** [jwilder/nginx-proxy#1101]
HI, 

I cant manage to have a ssl certificat using the limesurvey `fjudith/limesurvey` image. 
any idea why ?

> 
> nginx-proxy_1            | dockergen.1 | 2018/03/19 10:10:49 Received event start for container 9d5bf925f4a2
> nginx-proxy_1            | dockergen.1 | 2018/03/19 10:10:49 Generated '/etc/nginx/conf.d/default.conf' from 16 containers
> nginx-proxy_1            | dockergen.1 | 2018/03/19 10:10:49 Running 'nginx -s reload'
> nginx-proxy_1            | dockergen.1 | 2018/03/19 10:10:49 Error running notify command: nginx -s reload, exit status 1
> 

This is the docker-compose file I use:

```
limesurvey-md:
  image: mariadb
  restart: always
  ports:
    - "32805:3306"
  environment:
    MYSQL_DATABASE: limesurvey
    MYSQL_ROOT_PASSWORD: XXX
    MYSQL_USER: limesurvey
    MYSQL_PASSWORD: XXX
  volumes:
  - /home/stack/les_docker_compose/ask/limesurvey-db:/var/lib/mysql
  - /home/stack/les_docker_compose/ask/limesurvey-dblog:/var/log/mysql
  - /home/stack/les_docker_compose/ask/limeservey-dbetc:/etc/mysql

limesurvey:
  image: fjudith/limesurvey
  restart: always
  ports:
    - "32705:80"
  volumes:
    - /home/stack/les_docker_compose/ask/limesurvey-upload:/var/www/html/upload
  links:
    - limesurvey-md:mariadb
  environment:
    - VIRTUAL_HOST=ask.mydomain.fr
    - LETSENCRYPT_HOST=ask.mydomain.fr
    - LETSENCRYPT_EMAIL=contact@mydomain.fr
```

everything is ok with other containers
