### ISSUE TITLE
Isolate containers from internet

### ISSUE THREAD

**Issue by enric1994** [jwilder/nginx-proxy#1103]
I have a reverse proxy container that redirects to other containers, that I want to isolate from the internet.

For example, when I do **apt update** inside a container it works, I want to avoid that.

I tried the following setup:

```
version: "3"
services: 
  ##Reverse-proxy service
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - internet
      - no-internet

  nginx:
    image: nginx:latest
    environment:
      - VIRTUAL_HOST=test
    networks:
      - no-internet

networks:
  internet:
    driver: bridge
  no-internet:
    internal: true
```

I get an `502 Bad Gateway` error

I also tried the NETWORK_ACCESS=internal variable but the container (nginx in the example) still connecting to the internet. How can I isolate all the containers but not the proxy?
