### ISSUE TITLE
nginx-proxy doesn't fill upstream value in nginx config

### ISSUE THREAD

**Issue by lim-daniel** [jwilder/nginx-proxy#1107]
On every vhost I see default nginx webpage.

I added two containers with VIRTUAL_HOST env. Nginx-proxy container found my other containers, but don't fill upstream values in config.

```
# nginx -s reload
2018/03/22 18:05:47 [emerg] 53#53: no servers are inside upstream in /etc/nginx/conf.d/default.conf:55
nginx: [emerg] no servers are inside upstream in /etc/nginx/conf.d/default.conf:55
```

Part of config:
```
# git.example.com
upstream git.example.com {
}
server {
	server_name git.example.com;
	listen 80 ;
	access_log /var/log/nginx/access.log vhost;
	return 301 https://$host$request_uri;
}
server {
	server_name git.example.com;
	listen 443 ssl http2 ;
	access_log /var/log/nginx/access.log vhost;
	ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
	ssl_ciphers 'ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:!DSS';
	ssl_prefer_server_ciphers on;
	ssl_session_timeout 5m;
	ssl_session_cache shared:SSL:50m;
	ssl_session_tickets off;
	ssl_certificate /etc/nginx/certs/git.example.com.crt;
	ssl_certificate_key /etc/nginx/certs/git.example.com.key;
	add_header Strict-Transport-Security "max-age=31536000";
	location / {
		proxy_pass http://git.example.com;
	}
}
# test.example.win
upstream test.example.win {
}
server {
	server_name test.example.win;
	listen 80 ;
	access_log /var/log/nginx/access.log vhost;
	location / {
		proxy_pass http://test.example.win;
	}
}
```

  * Tested on latest and alpine image.
  * I change domain names, to example 

test.example.win docker-compose.yml
```
version: '2'

services:
  whoami:
    image: jwilder/whoami
    environment:
      - VIRTUAL_HOST=test.example.win
```

nginx-proxy docker-compose:
```
version: '2'
services:
  nginx-proxy:
#    image: jwilder/nginx-proxy:alpine
    image: jwilder/nginx-proxy:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /home/dockeruser/nginx/certs:/etc/nginx/certs
      - /home/dockeruser/nginx/vhost.d:/etc/nginx/vhost.d
      - /home/dockeruser/nginx/dhparam:/etc/nginx/dhparam
```
