### ISSUE TITLE
Docker for Windows volume mounts and docker.sock

### ISSUE THREAD

**Issue by johnrom** [jwilder/nginx-proxy#1110]
Mounting `/var/run/docker.sock` is no longer working in stable Docker for Windows with the latest update. There is an issue here: https://github.com/docker/for-win/issues/1829

I'm not sure whether the issue is that `docker.sock` file is no longer a reliable source for DFW, and if that is the case then the issue will have to be resolved here. However, if it's a bug and it should still be able to mount `docker.sock` on the Docker for Windows side of things, this bug should resolve itself in a future update.

An example error is here:

```
ERROR: for front  Cannot create container for service front: b'Mount denied:\nThe source path "\\\\var\\\\run\\\\docker.sock:/tmp/docker.sock"\nis not a valid Windows path'
```

Example `docker-compose.yml`:

```
front:
  restart: always
  image: jwilder/nginx-proxy
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock
  ports:
    - "80:80"
    - "443:443"
```

Docker Version:
18.03.0-ce-win59

**Comment by edinchev** [comment]
https://github.com/docker/for-win/issues/1829

**Comment by a727891** [comment]
There was a workaround found in docker/for-win#1829 

Add an this environment variable: `COMPOSE_CONVERT_WINDOWS_PATHS = 1 `

Or from Powershell run `$Env:COMPOSE_CONVERT_WINDOWS_PATHS=1`

**Comment by BaileyMillerSSI** [comment]
I am still getting my mount error even after changing that value to 1.

**Comment by BaileyMillerSSI** [comment]
Error:
```
ERROR: for reverseproxy_nginx-proxy_1  Cannot create container for service nginx-proxy: b'Mount denied:\nThe source path "\\\\var\\\\run\\\\docker.sock:/tmp/docker.sock"\nis not a valid Windows path'

ERROR: for nginx-proxy  Cannot create container for service nginx-proxy: b'Mount denied:\nThe source path "\\\\var\\\\run\\\\docker.sock:/tmp/docker.sock"\nis not a
valid Windows path'
ERROR: Encountered errors while bringing up the project.
```

docker-compose.yml:
```
version: '2'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock

  whoami:
    image: jwilder/whoami
    environment:
      - VIRTUAL_HOST=www.whoamitest.com
```
