### ISSUE TITLE
Feature request: Proxy exposed port to container (non VIRTUAL_PORT) 

### ISSUE THREAD

**Issue by Bram-Zijp** [jwilder/nginx-proxy#1112]
My container exposes multiple ports (one for websocket and one for webserver). The exposed port that is not the virtual port should be publicly reachable.

**Comment by leleobhz** [comment]
+1 for this request. Im trying to use gitea with this project but all I get is:

```
# gitea.mylongandpublicfqdn.com:3000             
upstream gitea.mylongandpublicfqdn.com:3000 {    
                                # Cannot connect to network of this container                                                                       server 127.0.0.1 down;    
}                            
server {                     
        server_name gitea.mylongandpublicfqdn.com:3000;                                                    
        listen 80 ;          
        access_log /var/log/nginx/access.log vhost;       
        location / {         
                proxy_pass http://gitea.mylongandpublicfqdn.com:3000;                                              }                    
}                            
```

The resulted conf from a composer for nginx-proxy:

```
version: '2'

services:
    nginx-proxy:
        image: jwilder/nginx-proxy
        container_name: nginx-proxy
        restart: always
        logging:             
            driver: journald
        ports:
            - "80:80"
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
        external_links:
            - gitea
```

And another composer file for gitea:

```
version: '3'

services:
    gitea:
        image: gitea/gitea:latest
        container_name: gitea
        environment:
            - USER_UID=1002
            - USER_GID=1003
            - VIRTUAL_HOST=gitea.mylongandpublicfqdn.com:3000
            - VIRTUAL_PORT=3000
        restart: always
        logging:
            driver: journald
        dns:
            - 189.38.95.95
            - 189.38.95.96
            - 2804:10:10::10
            - 2804:10:10::20
        dns_search:
            - mylongandpublicfqdn.com
        volumes:
            - /srv/storage/gitea:/data
        expose:
            - "3000"
        external_links:
            - nginx-proxy
        ports:
            - "3000:3000"
            - "222:22"
```

Inside the nginx-docker, a wget to gitea name results the image reaching public dns entry. But even with ports published, no way to do.

I've tried VIRTUAL_HOST variable with the port and without, but w/o sucess.

Thanks!
