### ISSUE TITLE
SSL network speed is slow

### ISSUE THREAD

**Issue by sweet-greg** [jwilder/nginx-proxy#1122]
Hi,

First off all, great package! Coming from vagrant, this is way more elegant in configuration!
I'm a having an issue though. I have noticed a serious slowdown in 'network' when using SSL.

When loading a page, a larger asset is loaded in 1.2 **minutes**, while without ssl it's done in 2.4 **seconds**. The only change between the 2 is enabling and disabled of SSL.
I have attached screenshots also.

Is this expected / a bug or am I doing something wrong here?

Thank you in advance!
PS: This is all running locally, on a Mac.

![screen shot 2018-04-20 at 14 43 51](https://user-images.githubusercontent.com/5057847/39056870-1b3c0c42-44b8-11e8-94b3-7e70c0d2ce07.png)
<img width="392" alt="screen shot 2018-04-20 at 16 08 51" src="https://user-images.githubusercontent.com/5057847/39056872-1b699676-44b8-11e8-92bb-f72628f9a776.png">

## nginx-proxy config with ssl
```
version: "3"
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ../certificates:/etc/nginx/certs

networks:
  default:
    external:
      name: nginx-proxy
```

## Container config with ssl
```
version: '3'
services:
  app:
    container_name: my_app
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: laravel-docker
    expose:
       - 80
       - 443
    volumes:
      - /Users/Greg/Workspace/StoryChief/sc_dashboard:/srv/app:cached
    links:
      - mysql
    environment:
      DB_HOST: mysql
      DB_DATABASE: my_app
      DB_USERNAME: my_app
      DB_PASSWORD: my_app
      VIRTUAL_HOST: myapp.sc, *.myapp.sc
  mysql:
    container_name: my_app_db
    image: mysql:5.7
    ports:
      - 3666:3306
    expose:
        - 3306
    environment:
      MYSQL_DATABASE: my_app
      MYSQL_USER: my_app
      MYSQL_PASSWORD: my_app
      MYSQL_ROOT_PASSWORD: my_app      
networks:
  default:
    external:
      name: nginx-proxy
```

## container vhost with ssl
```
<VirtualHost *:80 *:443>
    DocumentRoot /srv/app/public

    <Directory "/srv/app/">
        Options +FollowSymlinks
        AllowOverride All
        Require all granted
    </Directory>

    ErrorLog ${APACHE_LOG_DIR}/error.log
    CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>
```
