### ISSUE TITLE
IP down / no binding simple images

### ISSUE THREAD

**Issue by weeger** [jwilder/nginx-proxy#1127]
Hi,

I have a lot of problems with images which not use VIRTUAL_PORT properly : odoo, nextcloud, phpmyadmin... This is an example with phpmyadmin, I can access to it by specifying the port `http://pma.wex:7040`, but not only `http://pma.wex`, so it is not handled by the proxy. What I am doing wrong ?

```yml
version: '2.0'

services:

  my_mysql:
    environment:
      MYSQL_PASSWORD:
    image: wexample/mysql:latest
    networks:
      - reverseproxy_wex_net
    ports:
    - 7030:3306/tcp
    restart: always
    volumes:
    - /var/www/my/mysql/data:/var/lib/mysql:rw

  my_phpmyadmin:
    environment:
      - PMA_HOST=my_mysql
      - PMA_PASSWORD=thisIsAReallyNotSecurePassword!
      - PMA_USER=root
      - VIRTUAL_HOST=pma.wex
      - VIRTUAL_PORT='7040'
    expose:
      - '7040'
    image: phpmyadmin/phpmyadmin:4.7.9-1
    links:
    - my_mysql
    networks:
      - reverseproxy_wex_net
    ports:
    - 7040:80/tcp
    restart: always

networks:
  reverseproxy_wex_net:
    external: true
```
Other simple PHP / Apache images works fine, like this below, I can access to it using `http://one.wex`.

```yml
version: '2.0'

services:

  one_web:
    container_name: one_web
    environment:
      VIRTUAL_HOST: one.wex
      VIRTUAL_PORT: '701'
    # PHP / APACHE server
    image: wexample/php7:latest
    networks:
      reverseproxy_wex_net: null
    ports:
    - 701:80/tcp
    restart: always
    stdin_open: true
    tty: true

networks:
  reverseproxy_wex_net:
    external: true
```

```json
# pma.wex
upstream pma.wex {
                                ## Can be connect with "reverseproxy_wex_net" network
                # pma_my_phpmyadmin_1
                server 172.16.238.5 down;
}
server {
        server_name pma.wex;
        listen 80 ;
        access_log /var/log/nginx/access.log vhost;
        location / {
                proxy_pass http://pma.wex;
        }
}
```

As a fix, I had to make images to use the same port as the VIRTUAL_PORT, which is not easy for every application, and remove the sense to use port binding and proxy.

As a succeed to run a phpmyadmin with a previous version I thought it was a misuse from me, but after the thirt type of really popular images I tried to run, I think there is something uclear we may fix and it drive me crasy.

Thank you,

**Comment by weeger** [comment]
Another example with odoo

Working, with no proxy and customized port, I can access to my odoo with `http://myIP:8888`

```yml
version: '2.0'

services:
  odoo:
    depends_on:
    - odoo_postgres
    environment:
      DB_ENV_POSTGRES_PASSWORD: thisIsAReallyNotSecurePassword!
      DB_ENV_POSTGRES_USER: default
      DB_PORT_5432_TCP_ADDR: odoo_postgres
      DB_PORT_5432_TCP_PORT: '7080'
    image: odoo:11.0
    ports:
    - 8888:8069/tcp
    restart: always

  odoo_postgres:
    command: -p 7080
    container_name: odoo_postgres
    environment:
      PGPORT: '7080'
      POSTGRES_DB: odoo
      POSTGRES_PASSWORD: thisIsAReallyNotSecurePassword!
      POSTGRES_USER: default
    image: postgres:10.3
    ports:
    - 7080:7080/tcp
    restart: always
```

Using prody server and keeping default odoo port (`8069`), I can access to my odoo with `http://odoo.wex`

```yml

version: '2.0'

services:
  odoo:
    depends_on:
    - odoo_postgres
    environment:
      DB_ENV_POSTGRES_PASSWORD: thisIsAReallyNotSecurePassword!
      DB_ENV_POSTGRES_USER: default
      DB_PORT_5432_TCP_ADDR: odoo_postgres
      DB_PORT_5432_TCP_PORT: '7080'
      VIRTUAL_HOST: odoo.wex
      VIRTUAL_PORT: '8069'
    expose:
    - '8069'
    image: odoo:11.0
    networks:
      reverseproxy_wex_net: null
    ports:
    - 8069:8069/tcp
    restart: always

  odoo_postgres:
    command: -p 7080
    container_name: odoo_postgres
    environment:
      PGPORT: '7080'
      POSTGRES_DB: odoo
      POSTGRES_PASSWORD: thisIsAReallyNotSecurePassword!
      POSTGRES_USER: default
    image: postgres:10.3
    networks:
      reverseproxy_wex_net: null
    ports:
    - 7080:7080/tcp
    restart: always

networks:
  reverseproxy_wex_net:
    external: true

```

But does not work when using a custom port (`8888`), I can only access to my odoo with `http://odoo.wex:8888`, and `http://odoo.wex` gives me a `502 Bad Gateway` error.

```yml
version: '2.0'

services:
  odoo:
    depends_on:
    - odoo_postgres
    environment:
      DB_ENV_POSTGRES_PASSWORD: thisIsAReallyNotSecurePassword!
      DB_ENV_POSTGRES_USER: default
      DB_PORT_5432_TCP_ADDR: odoo_postgres
      DB_PORT_5432_TCP_PORT: '7080'
      VIRTUAL_HOST: odoo.wex
      VIRTUAL_PORT: '8888'
    expose:
    - '8888'
    image: odoo:11.0
    networks:
      reverseproxy_wex_net: null
    ports:
    - 8888:8069/tcp
    restart: always

  odoo_postgres:
    command: -p 7080
    container_name: odoo_postgres
    environment:
      PGPORT: '7080'
      POSTGRES_DB: odoo
      POSTGRES_PASSWORD: thisIsAReallyNotSecurePassword!
      POSTGRES_USER: default
    image: postgres:10.3
    networks:
      reverseproxy_wex_net: null
    ports:
    - 7080:7080/tcp
    restart: always

networks:
  reverseproxy_wex_net:
    external: true

```

There is the configuration :

```text
# odoo.wex
upstream odoo.wex {
                                ## Can be connect with "reverseproxy_wex_net" network
                        # odoo_odoo_1
                        server 172.16.238.5:8888;
}
server {
        server_name odoo.wex;
        listen 80 ;
        access_log /var/log/nginx/access.log vhost;
        location / {
                proxy_pass http://odoo.wex;
        }
}
```

And the proxy error log :

```text
nginx.1    | 2018/05/01 13:23:38 [error] 208#208: *38 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.10.2, server: odoo.wex, request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.16.238.5:8888/favicon.ico", host: "odoo.wex", referrer: "http://odoo.wex/"
nginx.1    | odoo.wex 172.20.10.2 - - [01/May/2018:13:23:38 +0000] "GET /favicon.ico HTTP/1.1" 502 576 "http://odoo.wex/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36"
```

. . . h e l p . . .
