### ISSUE TITLE
load http content error 503

### ISSUE THREAD

**Issue by alexanderwilhelm** [jwilder/nginx-proxy#1139]
I'm running a word-press site behind a nginx proxy. When I open the URL "http://www.example.com" I get an error 503. When I open "https://www.example.com" the site works but all http-content (like .css and .js) could not be found due to error 503.

I have the SSL-Cert files example.com.crt and example.com.key in the /certs folder

Here is my docker-compose.yml for nginx proxy:
```
version: '2'
services:
  frontproxy:
    image: jwilder/nginx-proxy:latest
    container_name: frontproxy
    restart: always
    environment:
      DEFAULT_HOST: default.vhost
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs:/etc/nginx/certs
      - /var/run/docker.sock:/tmp/docker.sock:ro
```

and my docker-compose.yml for wordpress:

```
version: '2'
services:
  wordpress:
    image: wordpress:fpm
    links:
      - db:mysql
    restart: always
    networks:
      - frontproxy_default
      - default
  nginx:
    image: raulr/nginx-wordpress
    links:
      - wordpress
    volumes_from:
      - wordpress
    ports:
      - "8080:80"
    restart: always
    networks:
      - frontproxy_default
      - default
    environment:
      - VIRTUAL_HOST=example.com
      #POST_MAX_SIZE: 128m
  db:
    image: mariadb
    restart: always
    networks:
      - frontproxy_default
      - default
    environment:
      MYSQL_ROOT_PASSWORD: somepass
networks:
  frontproxy_default:
    external: true
```
