### ISSUE TITLE
Proxying container exposing multiple ports (but only one HTTP)

### ISSUE THREAD

**Issue by muesli** [jwilder/nginx-proxy#1148]
I'm trying to proxy a gitea container, which is exposing one SSH port and one HTTP port.

The README states:
```
If your container exposes multiple ports, nginx-proxy will default to the service running on port 80. If you need to specify a different port, you can set a VIRTUAL_PORT env var to select a different one. If your container only exposes one port and it has a VIRTUAL_HOST env var set, that port will be selected.
```

However even though I have set VIRTUAL_PORT to the exposed HTTP port, the service is marked as "down" in the generated default.conf of nginx:
```
server 172.17.0.11 down;
```

If I only expose the HTTP port the generator works as expected.

**Comment by amosbird** [comment]
I'm facing the same issue with phabricator docker-compose.

**Comment by samara8609** [comment]
can you publish the docker compose or docker run command you are using to create the container?

**Comment by pyriand3r** [comment]
I have the same problem. I would like to run a gitea container behind the proxy. Running the gitea frontend is no problem with the config below. But the ssh port for git is not accessible through the gitea domain with this config. 

The question is, how to add the port 22 to exposed by the proxy, too?


Here's my `docker-compose`file
```
version: '2'

services:
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/docker/data/nginx/conf.d:/etc/nginx/conf.d
      - /home/docker/data/nginx/network_internal.conf:/etc/nginx/network_internal.conf

  dockergen:
    image: jwilder/docker-gen
    container_name: dockergen
    restart: always
    command: -notify-sighup nginx -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes_from:
      - nginx
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /home/docker/data/nginx/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl

  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    volumes:
      - /home/docker/data/gitea/data:/data
    depends_on:
      - gitea-db
    restart: always
    environment:
      VIRTUAL_HOST: "code.example.de"
      VIRTUAL_PORT: 3000
  gitea-db:
    image: mariadb:10
    container_name: gitea-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=changeme
      - MYSQL_DATABASE=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=changemetoo
    volumes:
      - /home/docker/data/gitea/db/:/var/lib/mysql
```
