### ISSUE TITLE
Can GET from Google Chrome Browser but not from Firefox Browser or curl or wget

### ISSUE THREAD

**Issue by hadrien-toma** [jwilder/nginx-proxy#1153]
# Step to reproduce
## File system
```
.
├── certs/
├── docker-compose.yml
├── README.md
└── served_files/
    └── index.html (content is: "<head></head><body>Index</body>")
```
## Generate certs
```
openssl req -x509 \
      -newkey rsa:4096 \
      -sha256 \
      -nodes \
      -subj '/CN=localhost' \
      -keyout ./certs/subdomain.localhost.key \
      -out ./certs/subdomain.localhost.crt
```
## Composition
```
version: '3.5'

services:
  server:
    environment:
      - VIRTUAL_HOST=subdomain.localhost
      - VIRTUAL_NETWORK=nginx_proxy
      - VIRTUAL_PORT=8888
    image: rapidoid/rapidoid
    volumes:
      - ./served_files:/app/static

  nginx_proxy:
    image: jwilder/nginx-proxy:alpine
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs
```
## Build/run
```
docker-compose up --build
```
# Troubles
Trying to query `https://subdomain.localhost/index.html` with :
## Google Chrome Browser
After accepting the self signed certificate, Chrome render the `index.html` file without any trouble.
## Firefox Browser
Firefox failure, telling "Server not found".
## Curl 
Curl failure, telling `curl: (6) Could not resolve host: subdomain.localhost`
## Wget
Wget failure, telling `Resolving subdomain.localhost (subdomain.localhost)... failed: Name or service not known. wget: unable to resolve host address ‘subdomain.localhost’`

# Question
Does someone know what I am doing wrong? I only tested in Chrome before now... what a bad thing this seems to be...
