### ISSUE TITLE
HTTPS protocol not works

### ISSUE THREAD

**Issue by saostad** [jwilder/nginx-proxy#1156]
I have my wild card certificate for multiple domain in a .pem file.
I attach dhparam/dhparam.pem 
and generate .key file from .pem file with this command: 

`openssl rsa -outform der -in private.pem -out private.key`

and rename the certificates to a.domain.com format and put it with .crt file in cert folder, to test it with one of my domains.
my website works fine with HTTP but with HTTPS I am getting no response from server. 
this is my docker-compose.yml file for run reverse-proxy
```
version: "3"
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs:/etc/nginx/certs
      - ./dhparam/dhparam.pem:/etc/nginx/dhparam/dhparam.pem:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./myproxy.conf:/etc/nginx/conf.d/myproxy.conf:ro

networks:
  default:
    external:
      name: nginx-proxy
```

and this is my back-end web server:
```
version: '3.1'

services:
  kbdg_forms_app:
    image: nginx:1.15.2-alpine
    volumes:
      - ./build:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    expose:
      - 80
    environment:
      VIRTUAL_HOST: a.domain.com

networks:
  default:
    external:
      name: nginx-proxy
```
