### ISSUE TITLE
nginx-proxy and GitLab -> 503 Service Temporarily Unavailable

### ISSUE THREAD

**Issue by MySora** [jwilder/nginx-proxy#1166]
Hi, 

I am trying to run this nginx-proxy with several other containers. One of there containers is a gitlab container which does not work (other containers work perfectly fine with the proxy!)
Sadly, I can't connect to the gitlab UI. I am getting a "503 Service Temporarily Unavailable" nginx error by the proxy. The connection between the proxy and gitlab does not seem to work correctly. I am also unable to curl from the frontproxy to the gitlab site using it's internal ip in the frontproxy_default network (->connection refused error).

I also tried to configure gitlab with the following settings (in the gitlab.rb file):
```
external_url 'https://gitlab.<domain>'
nginx['listen_port'] = 80
nginx['listen_https'] = false
nginx['proxy_set_headers'] = {  "X-Forwarded-Proto" => "https", "X-Forwarded-Ssl" => "on" }
```
--Docker-compose Files
The Proxy

```
version: '2.0'
services:
  frontproxy:
    image: jwilder/nginx-proxy
    container_name: frontproxy
    restart: always
    environment:
      DEFAULT_HOST: default.vhost
    volumes:
      - certs:/etc/nginx/certs
      - /var/run/docker.sock:/tmp/docker.sock
      - vhost.d:/etc/nginx/vhost.d
      - conf.d:/etc/nginx/conf.d
      - html:/usr/share/nginx/html
    ports:
      - 80:80
      - 443:443

  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    environment:
      - "ACME_CA_URI=https://acme-staging.api.letsencrypt.org/directory"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    volumes_from:
      - frontproxy

volumes:
    certs:
    vhost.d:
    conf.d:
    html:
```

And the Gitlab-Compose File
```
version: '2'
services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    restart: always

    volumes:
      - config:/etc/gitlab
      - logs:/var/log/gitlab
      - data:/var/opt/gitlab
    networks:
      - frontproxy_default
    environment:
      - VIRTUAL_HOST=gitlab.<domain>
      - LETSENCRYPT_HOST=gitlab.<domain>
      - LETSENCRYPT_EMAIL=<email>
      - LETSENCRYPT_TEST=true
      - VIRTUAL_PORT=80


networks:
  frontproxy_default:
    external: true
volumes:
  config:
  logs:
  data:

```

**Comment by MySora** [comment]
So actually I can curl inside the frontproxy docker to the gitlab docker but it won't connect me from the outsite

**Comment by ptrxwsmitt** [comment]
Try to disable letsencrypt in gitlab, which is active by default when the external_url starts with https and no certificate is provided:
letsencrypt['enable'] = false

**Comment by MySora** [comment]
just got back to this topic: disabled the virtual port as well and it works now thank you

**Comment by JosephBowkett** [comment]
@MySora , do you mean you commented out the virtual port in the reverse proxy config, or something in the gitlab omnibus config?
I'm facing the same problem but cannot see any reference to virtual port in gitlab.rb other than nginx['listen_port'] = nil

Is there any chance you could post the docker-compose that ended up working for you?
Thanks

**Comment by MySora** [comment]
@JosephBowkett I commented it out in the gitlab docker-compose file (environment setting).

I also came back on this topic some time ago... It didn't work out of the box (again; which is kinda weird).
So I did this:

- no virtual port in the **gitlab docker-compose file**; 
- in my final gitlab docker-compose file, I added the following environment setting ( I dunno if this had any effect tbh, because it did not apply these lines in the gitlab.rb file; so I had to manually edit that file and add these settings)
> GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.DOMAIN'
        nginx['listen_port'] = 80
        nginx['listen_https'] = false
        nginx['proxy_set_headers'] = {
          "X-Forwarded-Proto" => "https",
          "X-Forwarded-Ssl" => "on"
        } 
- I suggest you to put these line into the environment setting of your gitlab docker-compose file. If it does not work, set the settings in the gitlab.rb file and reconfigure/restart gitlab-ctl

**Comment by mahsan3** [comment]
Had the same issue when trying to setup gitlab-ce with nginx-proxy, without ssl the below docker-compose finally worked for me.
```
version: "3.1"

services:

  nginx-proxy:
    image: 'gitlab/gitlab-ce:latest'
    container_name: gitlab
    volumes:
      - '/srv/gitlab/config:/etc/gitlab'
      - '/srv/gitlab/logs:/var/log/gitlab'
      - '/srv/gitlab/data:/var/opt/gitlab'

    environment:
      GITLAB_OMNIBUS_CONFIG: |
         external_url 'http://gitlab.example.com'
         nginx['listen_port'] = 80
         nginx['listen_https'] = false

      VIRTUAL_HOST: gitlab.example.com
      VIRTUAL_PORT: 80

networks:
  default:
    external:
      name: nginx-proxy

```
