### ISSUE TITLE
+1 Error 503 when access from host/outside to container nginx-proxy

### ISSUE THREAD

**Issue by ikwijaya** [jwilder/nginx-proxy#1174]
**Dear @jwilder** 

I have 1 host with docker like this 
![image](https://user-images.githubusercontent.com/23114902/46866552-1205b380-ce4c-11e8-90ac-a384835851cf.png)

and container 1 reproduce **default.conf** with error here
`server_name _; # This is just an invalid value which will never trigger on a real hostname.`

```
proxy_set_header Proxy "";
server {
        server_name _; # This is just an invalid value which will never trigger on a real hostname.
        listen 80;
        access_log /var/log/nginx/access.log vhost;
        return 503;
}
# api1.dev.local
upstream api1.dev.local {
                                ## Can be connected with "reverse-proxy" network
                        # api1-local
                        server 172.19.0.3:80;
}
server {
        server_name api1.dev.local;
        listen 80 ;
        access_log /var/log/nginx/access.log vhost;
        location / {
                proxy_pass http://api1.dev.local;
        }
}
# api2.dev.local
upstream api2.dev.local {
                                ## Can be connected with "reverse-proxy" network
                        # api2-local
                        server 172.19.0.4:80;
}
server {
        server_name api2.dev.local;
        listen 80 ;
        access_log /var/log/nginx/access.log vhost;
        location / {
                proxy_pass http://api2.dev.local
        }
}
```

i **can** access container 2 with curl localhost:3000 => OK
i **can** access container 2 with curl localhost:3001 => OK
i **can** access from host -> proxy -> container 2 with curl -H "Host:api1.dev.local" localhost => OK
i **can** access from host -> proxy -> container 3 with curl -H "Host:api2.dev.local" localhost => OK
but 
i **cannot** access container 1 with curl localhost => 503
i cannot access from outside -> host => 503

may i missing something ?
here my reverse-proxy
```
#!/bin/bash
##########################################################################
# script to check if the jwilder proxy container is already running
# and if the ngnix-proxy network exists
# should be called before "docker-compose up -d"
##########################################################################

if [ ! "$(docker network ls | grep reverse-proxy)" ]; then
  echo "Creating reverse-proxy network ..."
  docker network create --driver bridge reverse-proxy
else
  echo "reverse-proxy network exists."
fi

if [ ! "$(docker ps | grep reverse-proxy)" ]; then
    if [ "$(docker ps -aq -f name=reverse-proxy)" ]; then
        # cleanup
        echo "Cleaning Reverse Proxy ..."
        docker rm reverse-proxy
    fi
    # run your container in our global network shared by different projects
    echo "Running Reverse Proxy in global reverse-proxy network ..."
    docker run -d -p 80:80 -p 443:443 \
    --name=reverse-proxy \
    --net=reverse-proxy \
    -v /var/run/docker.sock:/tmp/docker.sock:ro \
    jwilder/nginx-proxy
else
  echo "Nginx Proxy already running."
fi
```
and here my docker-compose

```
version: "3.2"

services:
  api1-local:
    build: ./_atkrequest                 #path which Dockerfile is exists
    container_name: api1-local
    restart: always
    networks:
      - reverse-proxy
    expose:
      - 80
    ports:
      - "3000:80"                            #host:container
    environment:
      - VIRTUAL_HOST=api1.dev.local       #nginx-proxy host
      - VIRTUAL_PORT=3000                 #nginx-proxy port
      - HTTPS_METHOD=noredirect

  api2-local:
    build: ./_atkmanage                 #path which Dockerfile is exists
    container_name: api2-local
    restart: always
    networks:
      - reverse-proxy
    expose:
      - 80
    ports:
      - "3001:80"                            #host:container
    environment:
      - VIRTUAL_HOST=api2.dev.local       #nginx-proxy host
      - VIRTUAL_PORT=3001                 #nginx-proxy port
      - HTTPS_METHOD=noredirect

networks:
  reverse-proxy:
    external: true
```

thanks in advance
@ikwijaya
