### ISSUE TITLE
DNS not resolving despite seemingly correct config

### ISSUE THREAD

**Issue by jairenee** [jwilder/nginx-proxy#1192]
I have a bind server running on my home server, and two containers to test the proxy, an apache server and ghost. The apache server is working flawlessly, however the ghost server is not resolving via the proxy. I checked all configs, and everything is seemingly in place. I don't understand why this is not resolving.

```
Resolve-DnsName test.jaimewiz.home

Name                                           Type   TTL   Section    IPAddress
----                                           ----   ---   -------    ---------
test.jaimewiz.home                             A      86400 Answer     192.168.1.123
```

```
Resolve-DnsName ghost.jaimewiz.home
Resolve-DnsName : ghost.jaimewiz.home : DNS name does not exist
At line:1 char:1
+ Resolve-DnsName ghost.jaimewiz.home
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (ghost.jaimewiz.home:String) [Resolve-DnsName], Win32Exception
    + FullyQualifiedErrorId : DNS_ERROR_RCODE_NAME_ERROR,Microsoft.DnsClient.Commands.ResolveDnsName
```

*apache docker-compose.yml*

```
version: "3"
services:
        gitlab:
                image: httpd:2.4
                container_name: test
                hostname: test.jaimewiz.home
                expose:
                        - "80"
                environment:
                        - VIRTUAL_HOST=test.jaimewiz.home
                        - VIRTUAL_PORT=80
                restart: "always"
                network_mode: "bridge"
```

*ghost docker-compose.yml*

```
version: "3"
services:
        ghost:
                image: ghost:1-alpine
                container_name: ghost
                hostname: ghost.jaimewiz.home
                expose:
                        - "2368"
                environment:
                        - VIRTUAL_HOST=ghost.jaimewiz.home
                        - VIRTUAL_PORT=2368
                restart: "always"
                network_mode: "bridge"
```

*bind zone*

```
;
; BIND data file for local loopback interface
;

$TTL    604800
@               IN      SOA     n1.jaimewiz.home. root.jaimewiz.home. (
                                        3       ; Serial
                                        604800  ; Refresh
                                        86400   ; Retry
                                        2419200 ; Expire
                                        604800 ); Negative Cache TTL
;
jaimewiz.home.  IN      NS      ns1.jaimewiz.home.
ns1             IN      A       192.168.1.123
@               IN      A       192.168.1.123
www             IN      A       192.168.1.123
*               IN      A       192.168.1.123
```

*default.conf from nginx-proxy container*

```
server {
        server_name _; # This is just an invalid value which will never trigger on a real hostname.
        listen 80;
        access_log /var/log/nginx/access.log vhost;
        return 503;
}
# ghost.jaimewiz.home
upstream ghost.jaimewiz.home {
                                ## Can be connected with "bridge" network
                        # ghost
                        server 172.17.0.4:2368;
}
server {
        server_name ghost.jaimewiz.home;
        listen 80 ;
        access_log /var/log/nginx/access.log vhost;
        location / {
                proxy_pass http://ghost.jaimewiz.home;
        }
}
# test.jaimewiz.home
upstream test.jaimewiz.home {
                                ## Can be connected with "bridge" network
                        # test
                        server 172.17.0.2:80;
}
server {
        server_name test.jaimewiz.home;
        listen 80 ;
        access_log /var/log/nginx/access.log vhost;
        location / {
                proxy_pass http://test.jaimewiz.home;
        }
}
```

I don't understand why this is happening.
