### ISSUE TITLE
SSL setup connection refused, bad nginx conf generation?

### ISSUE THREAD

**Issue by krainboltgreene** [jwilder/nginx-proxy#1206]
I have tried my very best to follow the instructions listed and I keep hitting a barrier with the SSL configuration. 

So before starting, know that I have tested the .crt and .key with a plain nginx server on the same server. The SSL came back positive via the browser and in curl.

Here's my docker compose, pruned for legibility:

``` yaml
version: "3.7"

x-logging-elk: &logging-elk
  driver: gelf
  options:
    gelf-address: udp://172.16.0.38:12201
    labels: container_group

x-sentry-environment: &sentry-environment
  SENTRY_SECRET_KEY:
  SENTRY_POSTGRES_HOST: "sentry-postgres"
  SENTRY_DB_NAME: "sentry_production"
  SENTRY_MEMCACHED_HOST: "sentry-memcached"
  SENTRY_REDIS_HOST: "sentry-redis"
  SENTRY_SINGLE_ORGANIZATION: "True"
  SENTRY_EMAIL_HOST: "smtp-la.company.com"
  SENTRY_SERVER_EMAIL: "sentry@company.com"

services:
  sentry:
    image: sentry:9.0.0
    labels:
      container_group: sentry
    depends_on:
      - logstash
      - sentry-postgres
      - sentry-redis
      - sentry-memcached
    environment:
      <<: *sentry-environment
      VIRTUAL_HOST: sentry.ie.company.com
    logging:
      <<: *logging-elk

  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    labels:
      container_group: utility
    ports:
      - "443:443"
    volumes:
      - "./volumes/settings/nginx-proxy/htpasswd/:/etc/nginx/htpasswd/:ro"
      - "./volumes/settings/nginx-proxy/conf.d/:/etc/nginx/conf.d/:rw"
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "./volumes/data/nginx-proxy/certs/:/etc/nginx/certs/"
    environment:
      ENABLE_IPV6: "true"

networks:
  outside:
    # Extra-network is necessary to have a dedicated IP for Logstash to forwards log to.
    ipam:
      driver: default
      config:
        - subnet: 172.16.0.38/24
```

Here's a network request via curl from my home machine:

```
𝑓 35 curl --verbose https://sentry.ie.company.com/
*   Trying x.x.x.x...
* TCP_NODELAY set
* Connected to sentry.ie.company.com (x.x.x.x) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to sentry.ie.company.com:443
* stopped the pause stream!
* Closing connection 0
curl: (35) LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to sentry.ie.company.com:443
```

That same request over http

```
𝑓 35 curl --verbose http://sentry.ie.company.com/
*   Trying x.x.x.x...
* TCP_NODELAY set
* Connected to sentry.ie.company.com (x.x.x.x) port 80 (#0)
> GET / HTTP/1.1
> Host: sentry.ie.company.com
> User-Agent: curl/7.54.0
> Accept: */*
>
* Empty reply from server
* Connection #0 to host sentry.ie.company.com left intact
curl: (52) Empty reply from server
```

Here's the nginx generated from this:

```
# If we receive X-Forwarded-Proto, pass it through; otherwise, pass along the
# scheme used to connect to this server
map $http_x_forwarded_proto $proxy_x_forwarded_proto {
  default $http_x_forwarded_proto;
  ''      $scheme;
}
# If we receive X-Forwarded-Port, pass it through; otherwise, pass along the
# server port the client connected to
map $http_x_forwarded_port $proxy_x_forwarded_port {
  default $http_x_forwarded_port;
  ''      $server_port;
}
# If we receive Upgrade, set Connection to "upgrade"; otherwise, delete any
# Connection header that may have been passed to this server
map $http_upgrade $proxy_connection {
  default upgrade;
  '' close;
}
# Apply fix for very long server names
server_names_hash_bucket_size 128;
# Default dhparam
ssl_dhparam /etc/nginx/dhparam/dhparam.pem;
# Set appropriate X-Forwarded-Ssl header
map $scheme $proxy_x_forwarded_ssl {
  default off;
  https on;
}
gzip_types text/plain text/css application/javascript application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript;
log_format vhost '$host $remote_addr - $remote_user [$time_local] '
                 '"$request" $status $body_bytes_sent '
                 '"$http_referer" "$http_user_agent"';
access_log off;
resolver 127.0.0.11;
# HTTP 1.1 support
proxy_http_version 1.1;
proxy_buffering off;
proxy_set_header Host $http_host;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection $proxy_connection;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $proxy_x_forwarded_proto;
proxy_set_header X-Forwarded-Ssl $proxy_x_forwarded_ssl;
proxy_set_header X-Forwarded-Port $proxy_x_forwarded_port;
# Mitigate httpoxy attack (see README for details)
proxy_set_header Proxy "";
server {
	server_name _; # This is just an invalid value which will never trigger on a real hostname.
	listen 80;
	listen [::]:80;
	access_log /var/log/nginx/access.log vhost;
	return 503;
}
# sentry.ie.company.com
upstream sentry.ie.company.com {
				## Can be connected with "20181203195336_default" network
			# 20181203195336_sentry_1
			server 192.168.224.14:9000;
}
server {
	server_name sentry.ie.company.com;
	listen 80 ;
	listen [::]:80 ;
	access_log /var/log/nginx/access.log vhost;
	location / {
		proxy_pass http://sentry.ie.company.com;
	}
}
```

The directory of my host-located SSL files:

```
kurtis.rainbolt-gree@la-eq-nginx04:/var/www/sites/monitoring-alerting-logging/current$ ls -la volumes/data/nginx-proxy/certs/
total 8
drwxr-xr-x 2 root root 4096 Dec  3 12:57 .
drwxr-xr-x 3 root root 4096 Dec  3 11:51 ..
lrwxrwxrwx 1 root root   46 Dec  3 12:57 ie.company.com.crt -> /etc/nginx/ssl/ie/star.ie.company.com.crt
lrwxrwxrwx 1 root root   46 Dec  3 12:57 ie.company.com.key -> /etc/nginx/ssl/ie/star.ie.company.com.key
```
