### ISSUE TITLE
502 Bad Gateway with multiple public IP addresses

### ISSUE THREAD

**Issue by DatAres37** [jwilder/nginx-proxy#1207]
Hi,
I'm currently having the problem that I'm getting a 502 Bad Gateway error if I have multiple public IP addresses on my host. I added another public IP by editing the netplan file on Ubuntu and both of them are pingable (it's a private subnet for testing purposes). **The compose files worked before adding a second public IP**.

That's my compose file for the reverse proxy:
```
version: '2'  
services:  
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - '/etc/nginx/vhost.d'
      - '/usr/share/nginx/html'
      - '/etc/nginx/certs:/etc/nginx/certs:ro' 
      - '/var/run/docker.sock:/tmp/docker.sock:ro'

  letsencrypt-nginx-proxy:
    container_name: letsencrypt-nginx-proxy
    image: 'jrcs/letsencrypt-nginx-proxy-companion'
    volumes:
      - '/etc/nginx/certs:/etc/nginx/certs'
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
    volumes_from:
      - nginx-proxy

networks:  
  default:
    external:
      name: nginx-proxy
```
The compose file for my portainer container (which works and is accessible):
```
...
#ports:
#  - "9000:9000"
expose:
  - "9000"
...
environment:
  - VIRTUAL_HOST=portainer.domain1.local
...
networks:  
  default:
    external:
      name: nginx-proxy
...
```
The compose file for my container that gets the 502 error:
```
...
nginx-mailcow:
...
#    ports:
#      - "${HTTPS_BIND:-0.0.0.0}:${HTTPS_PORT:-443}:${HTTPS_PORT:-443}"
#      - "${HTTP_BIND:-0.0.0.0}:${HTTP_PORT:-80}:${HTTP_PORT:-80}"
    expose:
      - "8080"
...
    environment:
      - HTTPS_PORT=${HTTPS_PORT:-443}
      - HTTP_PORT=${HTTP_PORT:-80}
      - MAILCOW_HOSTNAME=${MAILCOW_HOSTNAME}
      - IPV4_NETWORK=${IPV4_NETWORK:-172.22.1}
      - VIRTUAL_HOST=mail.domain2.local
      - VIRTUAL_PORT=8080
      - VIRTUAL_PROTO=http
...
    networks:
       mailcow-network:
            aliases:
             - nginx
       nginx-proxy:
            aliases:
             - mail.domain2.local
...
networks:
  mailcow-network:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: ${IPV4_NETWORK:-172.22.1}.0/24
        - subnet: ${IPV6_NETWORK:-fd4d:6169:6c63:6f77::/64}
   nginx-proxy:
      external: true
```
I bound HTTP of this container to 127.0.0.1:8080 and HTTPS to 127.0.0.1:8443 (only 8080 is used tho).
Full compose file (without my changes): https://github.com/mailcow/mailcow-dockerized/blob/master/docker-compose.yml

My DNS looks like this:
192.168.1.2 -> portainer.domain1.local
192.168.1.3 -> mail.domain2.local
I've also tried pointing both to .1.2, but no change.

I'm not a docker expert so it's likely to be my own fault, but can someone give me a little hint on what's going on? Is the proxy even compatible with multiple public IPs?
