### ISSUE TITLE
Error on proxying overriden services with docker-compose.override.yml ( not listening 443) 

### ISSUE THREAD

**Issue by toni-moreno** [jwilder/nginx-proxy#1218]
Hi guys all nginx-proxy seems to fail when working with overrided services.

It fails when a docker-compose.override.yml file has defined virtualhost  to change the default  service name from "resistor" to "resistort01" , the config has not 443 listening and 

On my docker-compose.yml ( with 2 proxied services  resistor and git 

````yaml
version: '3.1'

services:

  proxy:
    build: ./proxy/build/
    image: my_proxy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./proxy/certs:/etc/nginx/certs
      - ./proxy/extrasites/:/etc/nginx/conf.d
    environment:
       DEFAULT_HOST: default.vhost
    restart: always

  resistor:
    image: tonimoreno/resistor
    user: ${USER_UID}
    environment:
      VIRTUAL_HOST: resistor.${DOMAIN_BASE}  <--- OLD NAME
    volumes:
      - ./resistor/conf:/opt/resistor/conf
      - ./resistor/log:/opt/resistor/log
    restart: always
    ports:
      - "127.0.0.1:6090:6090"
    links:
      - influxdb
      - kapacitor

  git:
    image: gitea/gitea:latest
    environment:
      APP_NAME: GitServer
      HTTP_PORT: 4000
      SSH_DOMAIN: git.${DOMAIN_BASE}
      VIRTUAL_HOST: git.${DOMAIN_BASE}
      VIRTUAL_PORT: 4000
      USER_UID: ${USER_UID}
      USER_GID: ${USER_GID}
      GIT_SSL_NO_VERIFY: 1
    restart: always
    volumes:
      - ./gitea:/data
    ports:
      - "127.0.0.1:4000:4000"
      - "127.0.0.1:222:22"

````

On my docker-compose.override.yml ( where configured my new name for service resistor) 

````yml
  resistor:
    image: tonimoreno/resistor
    user: ${USER_UID}
    environment:
      VIRTUAL_HOST: resistort01.${DOMAIN_BASE} <-- NEW NAME
    volumes:
      - ./resistor/conf:/opt/resistor/conf
      - ./resistor/log:/opt/resistor/log
    restart: always
    ports:
      - "127.0.0.1:6090:6090"
    links:
      - influxdb
      - kapacitor
````

When restarted these are the server config  created  on the nginx default.conf file

````
# git.mydomain.org  <--- THIS IS OK ( LISTENING ON 80  with redirect and 443) 
upstream git.mydomain.org {
                                ## Can be connected with "project_default" network
                        # project_git_1_8d42ad7bf607
                        server 172.19.0.3:4000;
}
server {
        server_name git.mydomain.org;
        listen 80 ;
        access_log /var/log/nginx/access.log vhost;
        return 301 https://$host$request_uri;
}
server {
        server_name git.mydomain.org;
        listen 443 ssl http2 ;
        access_log /var/log/nginx/access.log vhost;
        ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;
        ssl_ciphers 'ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:!DSS';
        ssl_prefer_server_ciphers on;
        ssl_session_timeout 5m;
        ssl_session_cache shared:SSL:50m;
        ssl_session_tickets off;
        ssl_certificate /etc/nginx/certs/git.mydomain.org.crt;
        ssl_certificate_key /etc/nginx/certs/git.mydomain.org.key;
        add_header Strict-Transport-Security "max-age=31536000" always;
        location / {
                proxy_pass http://git.mydomain.org;
                include /etc/nginx/vhost.d/default_location;
        }
}

# resistort01.mydomain.org <--- THIS ONLY LISTENING ON PORT 80
upstream resistort01.mydomain.org {
                                ## Can be connected with "project_default" network
                        # project_resistor_1_4523011b4a6c
                        server 172.19.0.13:6090;
}
server {
        server_name resistort01.mydomain.org;
        listen 80 ;
        access_log /var/log/nginx/access.log vhost;
        location / {
                proxy_pass http://resistort01.mydoqmain.org;
                include /etc/nginx/vhost.d/default_location;
        }
}


````

Also I've noticed that it also adds an existeng service as  default site  for non existeing names ( instead of thown an 503 error like before) how can I fix this two errors?

Thank you!
