### ISSUE TITLE
Error 404 Not Found on .php files only

### ISSUE THREAD

**Issue by ReverseBrain** [jwilder/nginx-proxy#1222]
I have an nginx reverse proxy container and also an nginx and a php-fpm one. I have no problem serving .html files but when I try to navigate to a .php I receive Error 404 Not Found.

This is the docker-compose.yml of nginx reverse proxy:

```
version: "2"

services:
  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    container_name: nginx-proxy
    ports:
      - "8080:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./vhost.d:/etc/nginx/vhost.d

networks:
  default:
    external:
      name: nginx-proxy-net
```
This is the docker-compose.yml of my website:

```
version: "2"

services:
  nginx:
    image: nginx:latest
    expose:
      - 80
    restart: always
    volumes:
      - ./html:/usr/share/nginx/html
    environment:
      - VIRTUAL_HOST=vhost.example.it
    container_name: vhost-html

  php:
    image: php:7-fpm
    expose:
      - 9000
    restart: always
    volumes:
      - ./html:/usr/share/nginx/html
    environment:
      - VIRTUAL_PROTO=fastcgi
      - VIRTUAL_ROOT=/usr/share/nginx/html
      - VIRTUAL_PORT=9000
      - VIRTUAL_HOST=vhost-php.local
    container_name: vhost-php

networks:
  default:
    external:
      name: nginx-proxy-net
```
Also I created a per-VIRTUAL_HOST configuration file inside vhost.d folder:

```
location ~ \.php$ {
    try_files $uri =404;
    fastcgi_split_path_info ^(.+\.php)(/.+)$;
    fastcgi_pass vhost-php:9000;
    fastcgi_index index.php;
    include fastcgi_params;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    fastcgi_param PATH_INFO $fastcgi_path_info;
}
```
Is this a bug with FastCGI?

**Comment by andrefecto** [comment]
I had to add `fastcgi_index index.php;` to the beginning of my _location file. Then I can actually get to index.php. However, I'm having a problem where none of my CSS/JS files will load. You can see them by navigating to them directly but they come with the header of text/html instead of text/css. From my research I've tried all kinds of location blocks like the one you have but to no avail...if anyone has tips that would be great.

**Comment by ReverseBrain** [comment]
I have problems on all .php files, not only index.php

-------- Messaggio originale --------
On 26 Gen 2019, 20:39, Andre Fecteau ha scritto:

**Comment by andrefecto** [comment]
@ReverseBrain if I don't have `fastcgi_index index.php; ` at the beginning of my _location file, I get 404 errors for all php files as well.

**Comment by ReverseBrain** [comment]
This is what `docker logs` says on reverse proxy:

`nginx.1    | vhost.example.it <IP> - - [27/Jan/2019:17:17:38 +0000] "GET /publications.php HTTP/1.1" 404 571 "http://vhost.example.it:8080/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36"`

There is no trace about it on nginx and php container.

**Comment by ReverseBrain** [comment]
This is what an nginx debug level of error log says:
```
2019/01/28 09:56:16 [error] 43#43: *3 connect() failed (111: Connection refused) while connecting to upstream, client: <IP>, server: vhost.example.it, request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.19.0.2:80/favicon.ico", host: "vhost.example.it:8080", referrer: `"http://vhost.example.it:8080/publications.php"
```
172.19.0.2 is nginx while 172.19.0.3 is the PHP container.

**Comment by Richacinas** [comment]
I'm exactly going through the same problems

**Comment by petrukngantuk** [comment]
@ReverseBrain @Richacinas @andrefecto please share how to fix the problems, any suggestions?

**Comment by SantoshSah** [comment]
Any solution?

**Comment by judgej** [comment]
I had this probem too, and I really don't know what change finally fixed it. However, here is my minimal `docker-compose.yaml` file that runs a simple PHP server (no MySQL, no special extensions) for a demo app:

https://github.com/consilience/xero-php-oauth2-app/blob/docker-compose/docker-compose.yaml

There may be some clues there. One thing that may have fixed it was overriding the entire `/etc/nginx/conf.d/` directory rather than just add my own `conf` file. The nginx image comes with some default *conf* files that may be overriding settings in your *conf* file. The second thing was setting the `working_dir` for the nginx container.

**Comment by andrefecto** [comment]
@judgej your Docker-Compose actually shows the fix. It's the fact that you're sharing the same files in /var/www between both containers. As for getting this working automatically with the reverse proxy, I haven't figured that out yet. I host quite a few sites so they aren't all available in the same root path as the reverse proxy like your compose file shows.

**Comment by judgej** [comment]
My docker-foo isn't strong, so there is probably little more I can do to help. My docker-compose was put together as an absolute minimum to quickly run a demo app on a desktop of some sort, so everything is local and security is probably wide open.

**Comment by andrefecto** [comment]
@judgej Your Docker-Compose is exactly how I figured out that the Nginx front-end needs access to the WWW files that the back-end is running. It should be helpful to others trying to figure this out.

**Comment by SiliconMachine** [comment]
@andrefecto Were you able to make PHP work with this Docker image? I've been fighting for a week already without results.
I'm exposing the port 9000, and it's returning **localhost didn’t send any data.**

**Comment by andrefecto** [comment]
@SiliconMachine what PHP image are you using?

**Comment by SiliconMachine** [comment]
@andrefecto I am using **php:7.4-fpm** and mounting a Laravel app as a volume.
This is my docker-compose.yml laravel's config:

 ```
 # Laravel API
  laravel:
    container_name: codeverze-api
    build:
      context: docker/dev/api
      dockerfile: Dockerfile
      args:
        - WITH_XDEBUG=true
    restart: always
    ports:
      - "9000:9000"
    tty: true
    environment:
      VIRTUAL_HOST: laravel.test
      VIRTUAL_PROTO: fastcgi
      VIRTUAL_ROOT: /var/www/api
      PHP_IDE_CONFIG: "serverName=Docker"
      XDEBUG_CONFIG: remote_host=192.168.0.16 remote_port=9001
    volumes:
      - ./api:/var/www/api
    networks:
      - mynetwork
```

I thought that with the VIRTUAL_PROTO and VIRTUAL_ROOT env vars would be enough but I think something it's not working.
My nginx-proxy is returning no logs neither :/
