### ISSUE TITLE
503 connect() failed (111: Connection refused) while connecting to upstream

### ISSUE THREAD

**Issue by budim12** [jwilder/nginx-proxy#1253]
## Questions
I set up flask + jwilder with basic auth and got success code..
Then i set up gunicorn + jwilder, but got error,,

My error :
```
[error] 52#52: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: my.local, request: "GET / HTTP/1.1", upstream: "http://172.20.0.2:8000/", host: "my.local"
```

## My working code :
- Docker-compose.py
```
version: '3.7'
services:

  web:
    build: ./myapp
    restart: always
    networks:
      - proxynet
    environment:
      - VIRTUAL_HOST=my.local
      - VIRTUAL_PORT=5000
    expose:
      - 5000

  nginx-proxy:
    container_name: nginx-proxy
    restart: always
    image: jwilder/nginx-proxy:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-proxy/secrets/htpasswd:/etc/nginx/htpasswd
      - ./nginx-proxy/conf.d:/etc/nginx/conf.d
      - ./nginx-proxy/vhost.d:/etc/nginx/vhost.d
      - ./nginx-proxy/html:/usr/share/nginx/html
      - ./nginx-proxy/certs:/etc/nginx/certs
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks: 
      - proxynet

networks:
  proxynet:
    external: true
```

- Dockerfile.py
```
FROM python:3.4-alpine
ADD . /code
WORKDIR /code
RUN pip install -r requirements
CMD ["python", "app.py"]
```

My app.py
```
from flask import Flask
app = Flask(__name__)

@app.route('/')
def hello_world():
    return 'Hello world!'

if __name__ == '__main__':
    app.run(host='0.0.0.0')
```

Ok this upper code is run, and somehow works.. but my question is, when i'am using gunicorn, i got 503/502..

## My error code :

Docker-compose.py
```
version: '3.7'
services:

  app:
    build: 
      context: .
      dockerfile: ./app/Dockerfile
    environment: 
      - VIRTUAL_HOST=my.local
      - VIRTUAL_PORT=8000
    expose:
      - 8000
    networks: 
      - proxynet

  nginx-proxy:
    container_name: nginx-proxy
    restart: always
    image: jwilder/nginx-proxy:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-proxy/secrets/htpasswd:/etc/nginx/htpasswd
      - ./nginx-proxy/conf.d:/etc/nginx/conf.d
      - ./nginx-proxy/vhost.d:/etc/nginx/vhost.d
      - ./nginx-proxy/html:/usr/share/nginx/html
      - ./nginx-proxy/certs:/etc/nginx/certs
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks: 
      - proxynet

networks:
  proxynet:
    external: true
```

Dockerfile.py
```
FROM python:latest
ADD ./app /root
WORKDIR /root
RUN pip install -r requirements.txt
CMD ["/usr/local/bin/gunicorn", "manage"]
```

requirements.txt
```
Flask==1.0.2
gunicorn==19.9.0
```

manage.py
```
import os
from flask import Flask 
application = Flask(__name__)

@application.route("/")
def hello():
    return "<h1 style='color:blue'>Hello There!</h1>"

if __name__ == "__main__":
    application.run(host='0.0.0.0')
```

This last code result error :
```
[error] 52#52: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server:blabla.. 
``` 

Thanks for help..

Thanks,
Budi

**Comment by bilalbayasut** [comment]
same problem here, somehow jwilder/nginx does not detect the virtual_host , @jwilder any idea? thanks in advance

**Comment by Boojs** [comment]
I am in the same boat, I have two ports being proxied, and it seems to take the default port 80 instead of the VIRTUAL_PORT env var that I have set in the container.

**Comment by tomeady** [comment]
Any resolution? Struggling with this....

**Comment by Richacinas** [comment]
Me too. Same problem. I can see in the file /etc/nginx/conf.d/default.conf in my nginx-proxy container that the upstream is correctly linked (or it seems...):

```
# sectorasegurador.local
upstream sectorasegurador.local {
				## Can be connected with "nginxproxy_default" network
			# wp_sectorasegurador.local
			server 172.22.0.3:3001;
}
```

**Comment by wilcool** [comment]
Is solved?

**Comment by Richacinas** [comment]
In my case, the issue had to do with using PHP-FPM. I had to give up using this library because it is not ready to work with that engine of PHP as far as I understood.

I did it "manually", providing to the nginx docker image the parts of config file that I needed to make it work.

**Comment by aloysius-tim** [comment]
Had the same problem and solved it by adding `network_mode: bridge` on my docker-compose service.
Seems that nginx-proxy need the containers to be "connected" to this network to be able to auto-detect.

I'm also wondering if this issue is not related to the version of docker-compose. Let's imagine the proxy architecture have been deployed with a docker-compose v1 and trying to deploy your containers with a DC v2... Anyway, bridge network solve it.


`services:
  api:
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    build:
      context: ./api
    image: api.saastr
    restart: always
    ports:
      - 3333:3333
    expose:
      - "3333"
    environment:
      - ENV_PATH=/api/.env
      - NODE_ENV=production
      - VIRTUAL_HOST=api.saastr.0x0.run
      - LETSENCRYPT_HOST=api.saastr.0x0.run
      - LETSENCRYPT_EMAIL=tim@0x0.run
      - VIRTUAL_PORT=3333
    network_mode: bridge
    volumes:
      - ./api:/api`

**Comment by wilcool** [comment]
I solved it like this:

`docker network create nginx-proxy `
`docker network create network-b`
`docker network connect network-b nginx-proxy`

```shel
docker run -d -p 80:80 -p 443:443 \
  -v /var/run/docker.sock:/tmp/docker.sock:ro \
  -v /god/ssl:/etc/nginx/certs \
  -e DEFAULT_HOST=www.example.com \
  --name nginx-proxy \
  --net nginx-proxy \
  jwilder/nginx-proxy
```


```yml
services:
  gitea:
    image: gitea/gitea
    volumes:
      - /god/deploy/integration/gitea:/data
    ports:
      - "222:22"
    depends_on:
      - db
    restart: always
    expose:
      - "3000"
    environment:
      - VIRTUAL_PORT=3000
      - VIRTUAL_HOST=git.example.com
  db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=123456
    volumes:
      - /god/database/gitea:/var/lib/mysql
networks:
  default:
    external:
      name: network-b
```
