### ISSUE TITLE
How can I proxy multiple container

### ISSUE THREAD

**Issue by GreatFireWall** [jwilder/nginx-proxy#1258]
I want to proxy `wordpress` at 80 and 443, proxy `adminer` at 8080.

```yaml
version: "3.7"

services:
  db:
    image: mysql
    container_name: mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - ./mysql:/var/lib/mysql

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    environment: 
      # It seems not work correctly, I acess localhost:80 response the adminer page.
      VIRTUAL_HOST: localhost
    depends_on:
      - db

  wordpress:
    image: wordpress
    container_name: wordpress
    restart: always
    environment:
      VIRTUAL_HOST: localhost
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: 123456
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./wordpress:/var/www/html
    depends_on:
      - db
      - nginx-proxy

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: always
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs
```
