### ISSUE TITLE
503 with openproject container, but no problem with other containers

### ISSUE THREAD

**Issue by rucksman** [jwilder/nginx-proxy#1275]
I am running various containers behind this proxy (gitlab, nextcloud) without any problem. No I wanted to evaluate OpenProject (https://www.openproject.org/). But for this container I only get 503 when trying to access it via the browser. If I do a curl or wget in the shell with http://localhost:8080, I get the index.html back which means that the container is running fine.

I tried with the command line command they provide on their website (https://www.openproject.org/docker/) and with a docker-compose file, but there is only a 503. My docker-compose file looks like this:
````
version: '3'

services:
    openproject:
        image: 'openproject/community:latest'
        container_name: openproject
        restart: always
        ports:
            - '8080:80'
        volumes:
            - '/srv/openproject/pgdata:/var/openproject/pgdata'
            - '/srv/openproject/assets:/var/openproject/assets'
            - '/srv/openproject/logs:/var/log/supervisor'
        environment:
            - SECRET_KEY_BASE=somesecret
            - VIRTUAL_PORT=8080
            - VIRTUAL_HOST=projects.mydomain.com
        networks:
            - proxynet
networks:
    proxynet:
        external: true
````

What is going wrong here?
