### ISSUE TITLE
Enabling CORS issues

### ISSUE THREAD

**Issue by jonathangaldino** [jwilder/nginx-proxy#1282]
Hello,

I'm having issues when I'm trying to **enable CORS**.

I created a `default_location` file at `/etc/nginx/vhost.d/`. In this file, I have the exactly code:

```
add_header 'Access-Control-Allow-Origin' "$http_origin" always;
add_header 'Access-Control-Allow-Credentials' 'true' always;
add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, DELETE, OPTIONS' always;
add_header 'Access-Control-Allow-Headers' 'Accept,Authorization,Cache-Control,Content-Type,DNT,If-Modified-Since,Keep-Alive,Origin,User-Agent,X-Requested-With' always;

# required to be able to read Authorization header in frontend
#add_header 'Access-Control-Expose-Headers' 'Authorization' always;

if ($request_method = 'OPTIONS') {
        # Tell client that this pre-flight info is valid for 20 days
        add_header 'Access-Control-Max-Age' 1728000;
        add_header 'Content-Type' 'text/plain charset=UTF-8';
        add_header 'Content-Length' 0;
        return 204;
}
```

My API are in a `docker-compose` file, looking like this:

```yml
version: "3.1"

services:
  mysql:
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    volumes:
      - data_mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: example
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8081:8080

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    volumes:
      - data_grafana:/var/lib/grafana
    ports:
      - 3000:3000
    environment:
      - VIRTUAL_HOST=grafana.local
      - VIRTUAL_PORT=3000

  proxy:
    image: jwilder/nginx-proxy
    container_name: proxy
    restart: always
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ~/Documents/configs/proxy/vhost.d:/etc/nginx/vhost.d

volumes:
  data_mysql:
    external: false
  data_grafana:
    external: false

```

That being said and shown, I still can't access the grafana api.
