### ISSUE TITLE
x-forwarded-for docker-compose network

### ISSUE THREAD

**Issue by La-source** [jwilder/nginx-proxy#1287]
Hello,

By setting `nginx-proxy` with `docker-compose` and an external network the remote ip address is the internal IP address and not the client IP address.

```
version: '2'

services:
  app:
    image: node:12-alpine
    restart: always
    command: sh -c "npm install && npm start"
    working_dir: /app
    expose:
      - 3000
    volumes:
      - ./dist:/app
    environment:
      - VIRTUAL_HOST=domain.com
      - VIRTUAL_PORT=3000
  proxy:
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./vhost.d:/etc/nginx/vhost.d
      - ./certs:/etc/nginx/certs:ro
      - ./html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      - ENABLE_IPV6=true
    logging:
      driver: "none"

networks:
  default:
    external:
      name: nginx-proxy
```

Result:
```
'x-real-ip': '172.23.0.1',
'x-forwarded-for': '172.23.0.1',
'x-forwarded-proto': 'https',
'x-forwarded-ssl': 'on',
'x-forwarded-port': '443',
```
