### ISSUE TITLE
HTTP 503 for only one docker-compose while every other works

### ISSUE THREAD

**Issue by CodeAndChoke** [jwilder/nginx-proxy#1305]
Following is my docker-compose for a domain. The network's name is correct.
```
version: '2'
services:
   glutenfree:
     container_name: glutenfree
     image: nginx
     restart: always
     expose:
       - '80'
     environment:
       - VIRTUAL_HOST=glutenfree***********.com
       - VIRTUAL_PORT=80
     networks:
       - webproxy
networks:
  webproxy:
    external: true
```

Following is logs of the nginx-proxy every time I try to start my container.

```
nginx-letsencrypt    | 2019/07/17 04:14:10 Received event die for container c251b20f27a7
nginx-letsencrypt    | 2019/07/17 04:14:10 Received event stop for container c251b20f27a7
nginx-letsencrypt    | 2019/07/17 04:14:11 Received event start for container c251b20f27a7
```

I check the config file of nginx and the virtual host does not even being created.
