### ISSUE TITLE
Unpredictable behaviour

### ISSUE THREAD

**Issue by mindrunner** [jwilder/nginx-proxy#1343]
Not sure what the real issue is, but I see our webservices constantly not being reachable. I figured out the following:

```
  app:
    image: image:${docker_tag}
    restart: always
    command: run --prod
    networks:
      - proxy-tier
    expose:
      - 9000
    environment:
      - VIRTUAL_HOST=<url>
      - VIRTUAL_PORT=9000
      - VIRTUAL_NETWORK=nginx-proxy
      - LETSENCRYPT_HOST=<utl>
      - LETSENCRYPT_EMAIL=<email>
    depends_on:
      - mongodb
      - redis

  celery:
    image: image:${docker_tag}
    networks:
      - proxy-tier
    restart: always
    command: queue
    depends_on:
      - redis

```

Note, the specialities:

- Two containers running the same image with different entry points
- The dockerfile for `image`, exposes Port 9000

Thus, both app and celery expose the same port, but only one of which is supposed to be reachable from outside via SSL. Should be obvious by this config.

However, after spinning everything up, nginx (sometimes, not always) seem to route to the celery app port 9000, resulting in a connection-refused.

Is this an unsupported setup? Or just a weird bug?

Edit: Follow-Up / X-Post from 
https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/issues/583
