### ISSUE TITLE
502 Gateway error with uWSGI/Flask

### ISSUE THREAD

**Issue by failing** [jwilder/nginx-proxy#1358]
Currently been wrapping my head around for this a day and not really sure where I'm going wrong. 

Currently, I am running one container fine which is serving my main website from my server. 

I am trying to start another container at a subdomain but keep getting 502 Gateway errors which seem to be an issue with how I'm exposing the ports etc.

my main app file 
```from flask import *
from flask_pymongo import PyMongo
from bson import ObjectId
import json


class JSONEncoder(json.JSONEncoder):
    def default(self, o):
        if isinstance(o, ObjectId):
            return str(o)
        return json.JSONEncoder.default(self, o)


app = Flask(__name__)
......
```

Uwsgi.ini
```
[uwsgi]
socket = :9009
module = routes:app
post-buffering = 1
processes = 1
threads = 1
```

my docker-compose.yml file

``` 
version: '3'

services:
    web:
        build:
            context: .
        image: ubuntu:latest
        entrypoint: uwsgi --ini uwsgi.ini
        container_name: flaskapp
        restart: always
        depends_on:
            - mongo
        environment:
          VIRTUAL_HOST: sub.domain.com
          LETSENCRYPT_HOST: sub.domain.com
          LETSENCRYPT_EMAI: email
          VIRTUAL_PROTO: uwsgi

        links:
          - mongo
    mongo:
        image: mongo:4.2.1-bionic
        restart: always
        ports:
            - "27017:27017"
        container_name: mongo_database
networks:
  default:
    external:
      name: nginx-proxy
```

and finally my Dockerfile

```
FROM python:3.7-stretch

ARG requirements
RUN apt-get update

RUN mkdir application

COPY app/ /application
WORKDIR /application
RUN pip install -r requirements.txt

EXPOSE 9009
```

Honestly not really sure where I'm going wrong here. I'm pretty new with Docker so I could completely be doing this wrong but any help would be appreciated. Cheers

**Comment by failing** [comment]
Fixed it!

Just need to put `network_mode: bridge` in the docker-compose.yml file. 

Updated Dockerfile and docker-compose.yml file if anyone else runs into similar issues.

```
version: '3'

services:
    web:
        build:
            context: .
        image: ubuntu:latest
        entrypoint: python routes.py
        container_name: flaskapp
        restart: always
        depends_on:
            - mongo
        environment:
          VIRTUAL_HOST: DOMAIN
          LETSENCRYPT_HOST: DOMAIN
          LETSENCRYPT_EMAI: SUB
          VIRTUAL_PORT: 5000
        links:
          - mongo
        network_mode: bridge
    mongo:
        image: mongo:4.2.1-bionic
        restart: always
        ports:
            - "27017:27017"
        container_name: mongo_database
        network_mode: bridge
networks:
  default:
    external:
      name: nginx-proxy
```

```
FROM python:3.7-stretch

ARG requirements
RUN apt-get update

RUN mkdir application

COPY app/ /application
WORKDIR /application
RUN pip install -r requirements.txt

EXPOSE 5000
```
