### ISSUE TITLE
how  implementat load balance?

### ISSUE THREAD

**Issue by alan6666-erp** [jwilder/nginx-proxy#1364]
Hi , I want  implement load balance , 
I want to determine if this is correct , 
mutil container (  same VIRTUAL_HOST  ),  the VIRTUAL_PORT can be the same or different ,
like web , web2 container.
Is it as simple as  implement load balancing?
tjank you.

```yaml
version: '3.5'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    restart: always
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - ./vhost.d:/etc/nginx/vhost.d

  web:
    restart: always
    image: web
    depends_on:
      - db
    environment:
      - VIRTUAL_HOST=www.hello.com
      - VIRTUAL_NETWORK=nginx-proxy
      -  VIRTUAL_PORT=8087
    expose:
      - "8087"

  web2:
    restart: always
    image: web2
    depends_on:
      - db
    environment:
      - VIRTUAL_HOST=www.hello.com
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=8087
    expose:
      - "8087"

 .......

volumes:
  certs:
  html:
  dhparam:
  db-data:
```
