### ISSUE TITLE
502 Bad Gateway when I use jwilder/nginx-proxy with my a docker container

### ISSUE THREAD

**Issue by nocturnesound** [jwilder/nginx-proxy#1384]
Hi there,
I have an error with jwilder/nginx-proxy. 
Interesting moment, when my a docker container launched without jwilder/nginx-proxy:
`curl -I 172.18.0.3/api_123456` 
`HTTP/1.1 200 OK
Server: nginx/1.13.8
Date: Wed, 22 Jan 2020 17:03:38 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 1623806
Connection: keep-alive
X-Powered-By: Express
Access-Control-Allow-Origin: *
ETag: W/"18c6fe-cMPFn0zmRG/WvsZoTNGmv+2OjUs"
`

With started jwilder/nginx-proxy:
`curl -I 172.18.0.3/api_123456` 
`HTTP/1.1 502 Bad Gateway
Server: nginx/1.13.8
Date: Wed, 22 Jan 2020 17:04:10 GMT
Content-Type: text/html
Content-Length: 173
Connection: keep-alive`

**Commands:**
Create network
`docker network create nginx-proxy`

Run jwilder/nginx-proxy
`docker run -d -p 80:80 --name nginx-proxy --net nginx-proxy -v /var/run/docker.sock:/tmp/docker.sock jwilder/nginx-proxy`

Run the app
`docker run -d --name xxx.fakedomain.test --expose 80 --net nginx-proxy -e VIRTUAL_HOST=xxx.fakedomain.test -e VIRTUAL_PORT=80 play:v1.1 bash`

In my an app I have nginx proxy (80 port):
```
location /api_123456 {
    proxy_set_header   X-Forwarded-For $remote_addr;
    proxy_set_header   Host $http_host;
    proxy_pass         http://localhost:8081/api_123456;        
}
```

**Comment by 234BUG** [comment]
I believe I am experiencing the same issue, I have everything set up according to documentation and the configuration the reverse proxy container generates looks like it should be working, but no matter what I try it always results in 502.

`version: "3"
services:
        jwilder-proxy:
                image: jwilder/nginx-proxy
                ports:
                        - 80:80
                        - 443:443
                volumes:
                        - /opt/ssl:/etc/nginx/certs
                        - /var/run/docker.sock:/tmp/docker.sock
                restart: always
        sonarr:
                image: linuxserver/sonarr
                container_name: sonarr
                ports:
                        - 8989:8989
                environment:
                        - VIRTUAL_HOST=sonarr.intranet
                        - VIRTUAL_PROTO=https
                        - PUID=1000
                        - PGID=1000
                        - TZ=Europe/Zagreb
                volumes:
                        - /opt/docker/sonarr:/config
                        - /ESXi_NAS:/tv
                        - /ESXi_NAS:/downloads
                restart: unless-stopped
        radarr:
                image: linuxserver/radarr
                container_name: radarr
                ports:
                        - 7878:7878
                environment:
                        - VIRTUAL_HOST=radarr.intranet
                        - VIRTUAL_PROTO=https
                        - PUID=1000
                        - PGID=1000
                        - TZ=Europe/Zagreb
                volumes:
                        - /opt/docker/radarr:/config
                        - /ESXi_NAS:/movies
                        - /ESXi_NAS:/downloads
                restart: unless-stopped`

`# If we receive X-Forwarded-Proto, pass it through; otherwise, pass along the
# scheme used to connect to this server
map $http_x_forwarded_proto $proxy_x_forwarded_proto {
  default $http_x_forwarded_proto;
  ''      $scheme;
}
# If we receive X-Forwarded-Port, pass it through; otherwise, pass along the
# server port the client connected to
map $http_x_forwarded_port $proxy_x_forwarded_port {
  default $http_x_forwarded_port;
  ''      $server_port;
}
# If we receive Upgrade, set Connection to "upgrade"; otherwise, delete any
# Connection header that may have been passed to this server
map $http_upgrade $proxy_connection {
  default upgrade;
  '' close;
}
# Apply fix for very long server names
server_names_hash_bucket_size 128;
# Default dhparam
ssl_dhparam /etc/nginx/dhparam/dhparam.pem;
# Set appropriate X-Forwarded-Ssl header
map $scheme $proxy_x_forwarded_ssl {
  default off;
  https on;
}
gzip_types text/plain text/css application/javascript application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript;
log_format vhost '$host $remote_addr - $remote_user [$time_local] '
                 '"$request" $status $body_bytes_sent '
                 '"$http_referer" "$http_user_agent"';
access_log off;
                ssl_protocols TLSv1.2 TLSv1.3;
                ssl_ciphers 'ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384';
                ssl_prefer_server_ciphers off;
resolver 127.0.0.11;
# HTTP 1.1 support
proxy_http_version 1.1;
proxy_buffering off;
proxy_set_header Host $http_host;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection $proxy_connection;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $proxy_x_forwarded_proto;
proxy_set_header X-Forwarded-Ssl $proxy_x_forwarded_ssl;
proxy_set_header X-Forwarded-Port $proxy_x_forwarded_port;
# Mitigate httpoxy attack (see README for details)
proxy_set_header Proxy "";
server {
        server_name _; # This is just an invalid value which will never trigger on a real hostname.
        listen 80;
        access_log /var/log/nginx/access.log vhost;
        return 503;
}
# radarr.intranet
upstream radarr.intranet {
                                ## Can be connected with "drexl_default" network
                        # radarr
                        server 192.168.144.2:7878;
}
server {
        server_name radarr.intranet;
        listen 80 ;
        access_log /var/log/nginx/access.log vhost;
        return 301 https://$host$request_uri;
}
server {
        server_name radarr.intranet;
        listen 443 ssl http2 ;
        access_log /var/log/nginx/access.log vhost;
        ssl_session_timeout 5m;
        ssl_session_cache shared:SSL:50m;
        ssl_session_tickets off;
        ssl_certificate /etc/nginx/certs/intranet.crt;
        ssl_certificate_key /etc/nginx/certs/intranet.key;
        add_header Strict-Transport-Security "max-age=31536000" always;
        location / {
                proxy_pass https://radarr.intranet;
        }
}
# sonarr.intranet
upstream sonarr.intranet {
                                ## Can be connected with "drexl_default" network
                        # sonarr
                        server 192.168.144.4:8989;
}
server {
        server_name sonarr.intranet;
        listen 80 ;
        access_log /var/log/nginx/access.log vhost;
        return 301 https://$host$request_uri;
}
server {
        server_name sonarr.intranet;
        listen 443 ssl http2 ;
        access_log /var/log/nginx/access.log vhost;
        ssl_session_timeout 5m;
        ssl_session_cache shared:SSL:50m;
        ssl_session_tickets off;
        ssl_certificate /etc/nginx/certs/intranet.crt;
        ssl_certificate_key /etc/nginx/certs/intranet.key;
        add_header Strict-Transport-Security "max-age=31536000" always;
        location / {
                proxy_pass https://sonarr.intranet;
        }
}
`

**Comment by JCSynthTux** [comment]
```
---
version: "2"
services:

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - VIRTUAL_HOST=YOURDOMAINNAMEHERE
      - PUID=994
      - PGID=993
      - TZ=Europe/Berlin
    volumes:
      - ./conf:/config
      - /mnt/Filme:/movies
      - /mnt/Downloads:/downloads
    network_mode: NGINXNETWORKNAMEHERE 
    restart: unless-stopped
```
Setting `network_mode` to the network name of the nginx container (default is default_nginx) solved it for me.
See [here](https://docs.docker.com/compose/compose-file/#network_mode) for more information.

**Comment by sgtcoder** [comment]
> 

It's doesn't seem like nginx is getting it's own network, so it throws an error. Do you have the network config for the nginx container?

**Comment by alexandebryakin** [comment]
In my case I've been exposing the wrong port...


Here is the working `docker-compose` file:
```yml
version: "3.9"

services:
  proxy:
    # [TAKEN FROM]: https://blog.harveydelaney.com/hosting-websites-using-docker-nginx/
    restart: always
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - ./docker/certs:/etc/nginx/certs:ro

  ssl-companion:
    # [TAKEN FROM]: https://blog.harveydelaney.com/hosting-websites-using-docker-nginx/
    restart: always
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: ssl-companion
    environment:
      # TODO: comment out or remove after finishing everything up
      #       This is a URI for staging env of letsencrypt with expanded rate limits for testing purposes
      ACME_CA_URI: https://acme-staging-v02.api.letsencrypt.org/directory
    volumes:
      - ./docker/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    volumes_from:
      - proxy
    depends_on:
      - proxy

  weuse-production:
    restart: always
    image: weuse-production
    container_name: weuse-production
    expose:
      - 80 # This is the port specified in the `nginx.conf`
    environment:
      - VIRTUAL_HOST=some-domain.com
      - VIRTUAL_PORT=80 # This is the port specified in the `nginx.conf`
      - LETSENCRYPT_HOST=some-domain.com
      - LETSENCRYPT_EMAIL=your-email@some-domain.com
```

Here is the `nginx.conf` file:
```nginx
server {
  listen 80;
  
  location / {
    root /usr/share/nginx/html;
    index index.html index.htm;
    try_files $uri $uri/ /index.html =404;
  }
  
  include /etc/nginx/extra-conf.d/*.conf;
}
```

Here is the `Dockerfile` for the `weuse-production` image:
```Dockerfile
FROM nginx:1.15

WORKDIR /app

# COPY ./build .
COPY ./build/ /usr/share/nginx/html
# Copy the default nginx.conf provided by tiangolo/node-frontend
COPY ./docker/nginx.conf /etc/nginx/conf.d/default.conf
```
