### ISSUE TITLE
Ssh connection refused. Problem with port?

### ISSUE THREAD

**Issue by 89ece6d9e021e** [jwilder/nginx-proxy#1387]
Hello Guys,

I tried to create question on google group but I gen message that group doesn't exitst so I decided to create topic here.

I'm trying to setup gitlab working with nginx-proxy. I have a problem ( probably ) with ports. 

MY_PROBLEM: I'm not able to finish
`git clone git@gitlab.<myCoolDomain>:<myProjectGroup>/<myProject>.git`.
I get:
```
Cloning into <myProject>...
ssh: connect to host gitlab.<myCoolDomain> port 22: Connection timed out
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Could you tell me what I'm doing wrong?

Below you can find my docker-compose file configuration:

```
### N G I N X ###
  nginxServer:
    image: nginx:latest
    container_name: nginxServer
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/docker/nginx/certs:/etc/nginx/certs"
      - "/docker/nginx/vhost.d:/etc/nginx/vhost.d"
      - "/docker/nginx/conf.d:/etc/nginx/conf.d"
      - "/docker/nginx/html:/usr/share/nginx/html"

  ### D O C K E R - G E N ###
  #
  # Don't forget about that:
  # curl https://raw.githubusercontent.com/jwilder/nginx-proxy/master/nginx.tmpl > /path/to/nginx.tmpl
svirt_sandbox_file_t /path/to/volume )
  dockerGen:
    image: jwilder/docker-gen:latest
    container_name: dockerGen
    restart: always
    depends_on:
      - nginxServer
    volumes_from:
      - nginxServer
    volumes:
      - "/docker/nginx/templates:/etc/docker-gen/templates"
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
    command:
      "-notify-sighup nginxServer -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf"
    security_opt:
      - label:type:docker_t

  ### L E T S - E N C R Y P T ###
  letsEncrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion:latest
    container_name: nginxLE
    restart: always
    environment:
      NGINX_PROXY_CONTAINER: "nginxServer"
      NGINX_DOCKER_GEN_CONTAINER: "dockerGen"
    depends_on:
      - nginxServer
    volumes_from:
      - nginxServer
    volumes:
      - "/docker/nginx/certs:/etc/nginx/certs"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    security_opt:
      - label:type:docker_t

## G I T L A B ##
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    hostname: gitlab.<myCoolDomain>
    restart: always
    ports:
      - "8080:80"
      - "2222:22"
    environment:
      VIRTUAL_HOST: gitlab.<myCoolDomain>
      # VIRTUAL_PORT: 80,2222
      LETSENCRYPT_HOST: gitlab.<myCoolDomain>
      LETSENCRYPT_EMAIL: office@<myCoolDomain>
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.<myCoolDomain>'
        gitlab_rails['gitlab_shell_ssh_port'] = 2222
        letsencrypt['enabled'] = false
        nginx['enable'] = true
        nginx['redirect_http_to_https'] = false
    volumes:
      - /docker/gitlab/config:/etc/gitlab
      - /docker/gitlab/gitlab/logs:/var/log/gitlab
      - /docker/gitlab/gitlab/data:/var/opt/gitlab
    depends_on:
      - nginxServer
      - dockerGen
      - letsEncrypt
```
