### ISSUE TITLE
docker-compose: file exists at %!s(MISSING), can't create volume there

### ISSUE THREAD

**Issue by dayglojesus** [jwilder/nginx-proxy#141]
I'm have been using `nginx-proxy` with `docker-compose` on CentOS 7 successfully, but after updating Docker using the latest yum package (from 1.5.0-1.el7 to 1.5.0-28.el7.centos), I began receiving an error.

``` Bash
# docker-compose --verbose up -d
Compose version 1.1.0
Docker base_url: http+unix://var/run/docker.sock
Docker version: KernelVersion=3.10.0-123.el7.x86_64, Arch=amd64, ApiVersion=1.18, Version=1.5.0-dev, GitCommit=fc0329b/1.5.0, Os=linux, GoVersion=go1.3.3
docker containers <- (all=True)
docker containers -> (list with 0 items)
Creating munkicluster_proxy_1...
docker containers <- (all=True)
docker containers -> (list with 0 items)
docker create_container <- (name=u'webcluster_proxy_1', image=u'jwilder/nginx-proxy:latest', environment={}, volumes={u'/app/nginx.tmpl': {}}, detach=True, ports=[u'443'])
file exists at %!s(MISSING), can't create volume there
```

Here is the `docker-compose` service:

``` YAML
# THIS DOESN'T WORK
proxy:
  image: jwilder/nginx-proxy
  privileged: true
  volumes:
    - templates/nginx.tmpl:/app/nginx.tmpl
    - /var/run/docker.sock:/tmp/docker.sock
    - certs:/etc/nginx/certs
  ports:
    - "443:443"
```

As you can see, I am replacing the default `nginx.tmpl`with my own custom config. This appears to be the source of the issue -- if I remove this volume directive, the build succeeds.

``` YAML
# THIS WORKS
proxy:
  image: jwilder/nginx-proxy
  privileged: true
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock
    - certs:/etc/nginx/certs
  ports:
    - "443:443"
```

Of course, the proxy will not function as I need it without the extra configuration contained in the cstom template, but the container will build without error.

Moreover, if I instead run the equivalent command using just `docker`, it executes normally:

``` Bash
docker run --privileged \
  -d --name proxy \
  -v /webcluster/templates/nginx.tmpl:/app/nginx.tmpl \
  -v /var/run/docker.sock:/tmp/docker.sock \
  -v /webcluster/certs:/etc/nginx/certs \
  -p "80:80" jwilder/nginx-proxy 
```

I'm guessing this may be only indirectly related to `nginx-proxy`, but if anybody knows a little more about the cause appreciate your input.

Thanks,

B.

**Comment by md5** [comment]
I just got the same error testing your `docker-compose.yaml` in a directory that was missing `templates/nginx.tmpl`. When I did that, `docker` created the `templates/nginx.tmpl` as a directory in my home directory. I think the issue is that it then tries to bind mount over `/app/nginx.tmpl`, expecting it to be a directory, then fails when it sees that it's a file instead.

**Comment by dayglojesus** [comment]
Interesting. After reading this, I tried moving the custom `nginx.tmpl` into `templates/app` and then using...

```YAML
proxy:
  image: jwilder/nginx-proxy
  privileged: true
  volumes:
    - templates/app:/app
    - /var/run/docker.sock:/tmp/docker.sock
    - certs:/etc/nginx/certs
  ports:
    - "443:443"
```

This nukes the /app directory, but the container DOES build.

Do you think it is safe to assume this is a problem with `docker-compose`?
