### ISSUE TITLE
How to use with docker-compose?

### ISSUE THREAD

**Issue by francisbesset** [jwilder/nginx-proxy#150]
Hello,
Thank you for your awesome works!

I use docker-compose to run more containers linked (nginx / mysql / php).
But the option `environment` does not work when I specify VIRTUAL_HOST=mydomain.org:
``` yaml
nginx:
    image: nginx:1.7
    volumes:
        - nginx:/etc/nginx/conf.d:ro
        - public_html:/var/www/public_html:ro
    environment:
        - VIRTUAL_HOST=mydomain.org
```

And I run my containers with this command: `docker-compose up -d`

But `mydomain.org` return a 503 status code.
If I use `docker-compose run -d -e VIRTUAL_HOST=mydomain.org nginx` it works !

Is it possible to specify VIRTUAL_HOST in docker-composer.yml and run simply `docker-compose up -d`?
