### ISSUE TITLE
Custom Nginx Configuration per Host doesn't work with docker-compose?

### ISSUE THREAD

**Issue by sspross** [jwilder/nginx-proxy#151]
I'm trying to define custom nginx configrations per host, like written in the readme. But it seems to don't work as expected:
```
...
nginx:
  image: jwilder/nginx-proxy
  volumes_from:
    - myapp
  volumes:
    - /source/nginx:/etc/nginx/vhost.d:ro
    - /var/run/docker.sock:/tmp/docker.sock
  ports:
    - '80:80'
  links:
    - myapp:myapp
```

```
[~/projects/test]$ docker-compose run nginx bash              
root@f200c1c476c7:/app#
root@f200c1c476c7:/app# ls -l
total 32
-rw-r--r-- 1 root root 1076 Apr  9 22:10 Dockerfile
-rw-r--r-- 1 root root 1079 Apr  9 22:10 LICENSE
-rw-r--r-- 1 root root  129 Apr  9 22:10 Procfile
-rw-r--r-- 1 root root 8385 Apr  9 22:10 README.md
-rw-r--r-- 1 root root 5493 Apr  9 22:10 nginx.tmpl
root@f200c1c476c7:/app# ls -l /etc/nginx/vhost.d
total 0
root@f200c1c476c7:/app# ls -l /source/nginx/
total 8
-rw-r--r-- 1 1000 staff 957 Apr 24 07:17 dockerhost.me
```

Shouldn't I see my vhost config files in `/etc/nginx/vhost.d` as well, if I mount `/source/nginx:/etc/nginx/vhost.d:ro`or didn't I understand how to use it?

**Edit**

I just tried it with plain docker and it doesn't work either. I think I'm missing something here...

```
[~/projects/test]$ docker run -it -v /source/nginx:/etc/nginx/vhost.d:ro --volumes-from webapp_1 jwilder/nginx-proxy /bin/bash
root@0325aa175254:/app# ls -l
total 32
-rw-r--r-- 1 root root 1076 Apr  9 22:10 Dockerfile
-rw-r--r-- 1 root root 1079 Apr  9 22:10 LICENSE
-rw-r--r-- 1 root root  129 Apr  9 22:10 Procfile
-rw-r--r-- 1 root root 8385 Apr  9 22:10 README.md
-rw-r--r-- 1 root root 5493 Apr  9 22:10 nginx.tmpl
root@0325aa175254:/app# ls -l /source/nginx
total 8
-rw-r--r-- 1 1000 staff 957 Apr 24 07:17 dockerhost.me
root@0325aa175254:/app# ls -l /etc/nginx/vhost.d/
total 0
```
