### ISSUE TITLE
SSL Setup Funky?

### ISSUE THREAD

**Issue by scouttyg** [jwilder/nginx-proxy#193]
I figure this is definitely a problem with something I'm doing, but I've been frustratingly trying for a few days to get something setup without success, so I want to double check my sanity.

I have a docker-compose file that looks like this:

```yml
cache:
  image: memcached

db:
  image: postgres
  ports:
    - "5432"

app:
  build: .
  command: bundle exec puma -C config/puma.rb
  environment:
    SECRET_KEY_BASE: abcdefg
    VIRTUAL_HOST: docker.local
    VIRTUAL_PORT: 80
    RAILS_ENV: production
    RACK_ENV: production
  links:
    - db
    - cache
  env_file:
    - '.env'

proxy:
  image: jwilder/nginx-proxy:latest
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - "/var/run/docker.sock:/tmp/docker.sock:ro"
    - "config/docker/certs:/etc/nginx/certs"
```

I also wrote in my ```/etc/hosts``` file a record for docker.local:

```txt
# Docker Servers
192.168.59.103  docker.local
```

When I do ```docker-compose up```, everything looks good:

```bash
db_1    | LOG:  database system was shut down at 2015-07-03 22:28:21 UTC
db_1    | LOG:  MultiXact member wraparound protections are now enabled
db_1    | LOG:  database system is ready to accept connections
db_1    | LOG:  autovacuum launcher started
app_1   | Puma starting in single mode...
app_1   | * Version 2.10.2 (ruby 2.2.0-p0), codename: Robots on Comets
app_1   | * Min threads: 0, max threads: 1
app_1   | * Environment: production
proxy_1 | forego     | starting nginx.1 on port 5000
proxy_1 | forego     | starting dockergen.1 on port 5100
proxy_1 | dockergen.1 | 2015/07/03 22:28:36 Generated '/etc/nginx/conf.d/default.conf' from 4 containers
proxy_1 | dockergen.1 | 2015/07/03 22:28:36 Running 'nginx -s reload'
proxy_1 | dockergen.1 | 2015/07/03 22:28:36 Watching docker events
app_1   | * Listening on tcp://0.0.0.0:8080
app_1   | Use Ctrl-C to stop
```

But when I try to access it via curl, nothing happens.

**On http: (This looks right, its redirecting to the https version of the site)**
```bash
curl http://docker.local -v
* Rebuilt URL to: http://docker.local/
* Hostname was NOT found in DNS cache
*   Trying 192.168.59.103...
* Connected to docker.local (192.168.59.103) port 80 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.37.1
> Host: docker.local
> Accept: */*
> 
< HTTP/1.1 301 Moved Permanently
* Server nginx/1.9.2 is not blacklisted
< Server: nginx/1.9.2
< Date: Fri, 03 Jul 2015 22:29:25 GMT
< Content-Type: text/html
< Transfer-Encoding: chunked
< Connection: keep-alive
< Location: https://docker.local/
< 
* Connection #0 to host docker.local left intact
```
**On https: (uh oh! Connection refused!)**
```bash
curl https://docker.local -v
* Rebuilt URL to: https://docker.local/
* Hostname was NOT found in DNS cache
*   Trying 192.168.59.103...
* connect to 192.168.59.103 port 443 failed: Connection refused
* Failed to connect to docker.local port 443: Connection refused
* Closing connection 0
curl: (7) Failed to connect to docker.local port 443: Connection refused
```

I run ```docker-compose run proxy bash``` to check the config files, and see the following:

**Are the certs there? Yes!**
```bash
root@a8b80218fd71:/etc/nginx# ls certs/
docker.local.crt  docker.local.key
```
**Is the default nginx config file loaded with the correct setup? Doesn't look like it...**
```bash
root@a8b80218fd71:/etc/nginx# cat conf.d/default.conf 
server {
    listen       80;
    server_name  localhost;

    #charset koi8-r;
    #access_log  /var/log/nginx/log/host.access.log  main;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
    }

    #error_page  404              /404.html;

    # redirect server error pages to the static page /50x.html
    #
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }

    # proxy the PHP scripts to Apache listening on 127.0.0.1:80
    #
    #location ~ \.php$ {
    #    proxy_pass   http://127.0.0.1;
    #}

    # pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000
    #
    #location ~ \.php$ {
    #    root           html;
    #    fastcgi_pass   127.0.0.1:9000;
    #    fastcgi_index  index.php;
    #    fastcgi_param  SCRIPT_FILENAME  /scripts$fastcgi_script_name;
    #    include        fastcgi_params;
    #}

    # deny access to .htaccess files, if Apache's document root
    # concurs with nginx's one
    #
    #location ~ /\.ht {
    #    deny  all;
    #}
}
```

I'm not sure what I'm doing wrong here -- I don't seem to see any errors anywhere, but nothing is making it through. Any thoughts?

**Comment by scouttyg** [comment]
It looks like things work when I run them separately, IE I run this first:

```docker run -d -p 80:80 -p 443:443 -v ~/projects/docker-rails-test/config/docker/certs:/etc/nginx/certs -v /var/run/docker.sock:/tmp/docker.sock:ro jwilder/nginx-proxy```

And then run
```
docker-compose run app
```

But I'm not sure why that would be.. Perhaps a docker-compose issue?

**Comment by davemcom** [comment]
Have you considered changing the order, putting the definition for the
proxy at the head of the Docker Compose file?

**Comment by scouttyg** [comment]
Hmm, after hours of frustration, it seems to just work. I didn't even have to reorder, I just built again, and it seems to work.

The one minor change I made (but even when I unmade it, it seemed to work), was this:

```yml
app:
  build: .
  command: bundle exec puma -C config/puma.rb
  environment:
    SECRET_KEY_BASE: abcdefg
    VIRTUAL_HOST: docker.local
    VIRTUAL_PORT: 80
    RAILS_ENV: production
    RACK_ENV: production
  links:
    - proxy
    - cache
    - db

  env_file:
    - '.env'
```

According to https://github.com/docker/compose/issues/235, processes will start in dependency order, so since "app" is the process triggering the proxy to reload it's config (through the VIRTUAL_HOST variable), perhaps it needs a link to proxy so that the proxy is already started before the app launches. Potentially getting out of order (as @davemcom seemed to imply) might make it so that the proxy never reloads its configuration.
