### ISSUE TITLE
multi-port expose error

### ISSUE THREAD

**Issue by uptownhr** [jwilder/nginx-proxy#208]
``2015/07/29 18:20:28 template error: template: nginx.tmpl:69:33: executing "nginx.tmpl" at <$container.Addresses>: wrong type for value; expected []*main.RuntimeContainer; got []main.Address``

This occurs when image has multiple ports exposed. Sample image,

```
FROM node


RUN mkdir /var/www
WORKDIR /var/www

COPY ./package.json /var/www/package.json
COPY ./postback.js /var/www/postback.js


RUN npm install
CMD node postback.js
EXPOSE 80 443
```

Ho I run the container
```
postback:
  image: sample image
  ports:
  - "80"
  - "443"
  environment:
    VIRTUAL_HOST: sample.com
```

Let me know what I else I can provide.
