### ISSUE TITLE
configuration not updating

### ISSUE THREAD

**Issue by blankenshipz** [jwilder/nginx-proxy#219]
I'm trying to add SSL for a container that I'm creating with `docker-compose` and I've found that the `nginx-proxy` container I'm running will not update its configuration unless I run the container with the `docker` binary. 

Here's an example content for `docker-compose.yml`

```yaml
test:
  image: ubuntu:latest
  command: /bin/bash
  ports:
    - "2015:2015"
  environment:
    - VIRTUAL_HOST=^bar\.foo\.*
    - VIRTUAL_PORT=2015
    - CERT_NAME=foo
# docker-compose run --rm test
```

Here's the command that creates the test container with `docker` that `nginx-proxy` recognizes

```bash
docker run -it --rm  -p "2015:2015" -e 'VIRTUAL_HOST=^bar\.foo\.*' -e 'VIRTUAL_PORT=2015' -e 'CERT_NAME=foo' ubuntu bash
```

Here's the command that I'm using for `nginx-proxy`

```bash
docker run -it --rm -p 443:443 -v ./certs:/etc/nginx/certs -v /var/run/docker.sock:/tmp/docker.sock:ro jwilder/nginx-proxy
```

From what I can tell from `docker inspect` the environment variables inside of the containers are identical. 

I'm on `docker` *1.8.0*, `compose` *1.3.3* and `boot2docker` *1.8.0*

Can someone confirm this behaviour?
