### ISSUE TITLE
ERROR: open Procfile: no such file or directory

### ISSUE THREAD

**Issue by bilby91** [jwilder/nginx-proxy#236]
I don't know if this is an issue with docker-compose, I'm really new to docker so don't get mad at me :).

```
proxy:
  image: jwilder/nginx-proxy
  ports:
    - "80:80"
  volumes:
    - "/var/run/docker.sock:/tmp/docker.sock"
  volumes_from:
    - web
db:
  image: postgres
web:
  build: .
  volumes:
    - .:/app
  links:
    - db
  environment:
    VIRTUAL_HOST: app.dev
```

If I try so start the containers with compose and give the nginx container a container volume with `volumes_from:` I get this issue with the Procfile.

`proxy_1 | ERROR: open Procfile: no such file or directory`

If I remove the volumes_from: the container starts succesfully.

Also, If I run the container with the `docker` command line: `docker run -p 80:80 --volumes-from=c25c0356833f -v /var/run/docker.sock:/tmp/docker.sock:ro jwilder/nginx-proxy` there is no problem at all.

My Dockerfile looks like this:

```
FROM ruby:2.2.0

RUN apt-get update -qq && apt-get install -y build-essential

# Postgres support
RUN apt-get install -y libpq-dev

# Nokogiri support
RUN apt-get install -y libxml2-dev libxslt1-dev

# JS runtime
RUN apt-get install -y nodejs

ENV APP_HOME /app

RUN mkdir $APP_HOME
RUN mkdir $APP_HOME/tmp
RUN mkdir $APP_HOME/log

# Copy the Gemfile and Gemfile.lock into the image.
# Temporarily set the working directory to where they are.
WORKDIR /tmp
ADD Gemfile Gemfile
ADD Gemfile.lock Gemfile.lock

# Install ruby dependencies
RUN bundle install

# Add app to container
ADD . $APP_HOME

# Add container working directory
WORKDIR $APP_HOME

# Expose puma port
EXPOSE 3000

# Precompile js/scss assets
RUN bundle exec rake assets:precompile

# Expose the assets directory
VOLUME ["/app/public"]

# Run puma server
CMD bundle exec puma -C /app/puma.rb
```

Any idea ?
