### ISSUE TITLE
htpasswd folder doesn't work anymore / no basic auth

### ISSUE THREAD

**Issue by Emporea** [jwilder/nginx-proxy#2423]
I had previously configured this setup, which involved several files for domains in the htpasswd folder to enable basic authentication.

I recently created a new setup on a different machine using the same Docker Compose files and domain names, but encountered an issue where basic authentication no longer functions as intended. Instead of prompting for authentication, the system simply opens the sites directly.

I then deleted all htpasswd files and recreated them using the apache2-utils tool. I checked that these files were visible in the proxy docker container, which they were.

No error messages or other indications of failure were observed.

Dockerfile:
```dockerfile
FROM nginxproxy/nginx-proxy:alpine
COPY uploadsize.conf /etc/nginx/conf.d/uploadsize.conf

# I also tried this, instead of mounting via docker-compose, but this also didn't work.
#ADD htpasswd /etc/nginx/htpasswd 
```
```yaml
...
  proxy:
    build: ./proxy
    restart: unless-stopped
    container_name: proxy
    ports:
      - 80:80
      - 443:443
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    volumes:
      - ./proxy/htpasswd:/etc/nginx/htaccess:ro # doesnt work anymore.
      - proxy_certs:/etc/nginx/certs:z,ro
      - proxy_vhost.d:/etc/nginx/vhost.d:z
      - proxy_html:/usr/share/nginx/html:z
      - /var/run/docker.sock:/tmp/docker.sock:z,ro

  letsencrypt-companion:
    image: nginxproxy/acme-companion
    restart: unless-stopped
    container_name: letsencrypt-companion
    volumes:
      - proxy_certs:/etc/nginx/certs:z
      - proxy_acme:/etc/acme.sh:z
      - proxy_vhost.d:/etc/nginx/vhost.d:z
      - proxy_html:/usr/share/nginx/html:z
      - /var/run/docker.sock:/var/run/docker.sock:z,ro
...
```
