### ISSUE TITLE
health_check

### ISSUE THREAD

**Issue by chromerobv** [jwilder/nginx-proxy#251]
is there anyway to set up a custom health_check ?

**Comment by jwilder** [comment]
You could use a custom template.

**Comment by chromerobv** [comment]
yeah. just not sure vanilla nginx can do upstream health_checks. would have to recompile nginx with something like  nginx_upstream_check_module unless someone maybe knows a way to do it without having to recompile ?

**Comment by gingerlime** [comment]
@chromerobv curious to know if you figured out a way to do it?

**Comment by cadesalaberry** [comment]
I am wondering the same as well...

**Comment by danihodovic** [comment]
Here is a template that uses labels to
- group containers in a virtual hosts by `nginx_host`
- provide the port nginx will forward traffic to with `nginx_port`
- provide upstream server options with `nginx_upstream_opts`
- provide nginx active nginx health check options with `nginx_health_check_opts` (requires Nginx plus)

It's very rudimentary and I haven't tested it yet, but it's a good starting point. Here's where I found the various health checking options: https://docs.nginx.com/nginx/admin-guide/load-balancer/http-health-check/

```
{{ range $host, $containers := groupBy . "Labels.nginx_host" }}
upstream {{ $host }} {
  {{ range $index, $container := $containers }}
  server {{ $container.Name }}:{{ index $container.Labels "nginx_port"}} {{ index $container.Labels "nginx_upstream_opts" }};
  {{ end }}
}
{{ end }}


{{ range $host, $containers := groupBy . "Labels.nginx_host" }}
server {
  server_name {{ $host }};
  listen 80;

  location / {
    proxy_pass http://{{ $host }};
    {{ if index (first $containers).Labels "nginx_health_check_opts" }}
    healthcheck {{ index (first $containers).Labels "nginx_health_check_opts" }};
    {{ end }}
  }
}
{{ end }}
```

For example, the following docker-compose.yml:
```
---
version: '2'
services:
  docker_gen:
    image: jwilder/docker-gen
    command: -watch /etc/docker-gen/templates/dani.tmpl /dani
    volumes:
      - '/var/run/docker.sock:/tmp/docker.sock:ro'
      - './templates:/etc/docker-gen/templates'

  api_1:
    image: jwilder/whoami
    labels:
      nginx_host: foo
      nginx_port: '4444'
      nginx_upstream_opts: 'max_fails=3 fail_timeout=30s slow_start=30s'
      nginx_health_check_opts: 'uri=/some/path interval=10 fails=3 passes=2'

  api_2:
    image: jwilder/whoami
    labels:
      nginx_host: bar
      nginx_port: '5555'
```

Produces the following output:

```
upstream bar {
  server default_api_2_1:5555 ;
}
upstream foo {
  server default_api_1_1:4444 max_fails=3 fail_timeout=30s slow_start=30s;
}
server {
  server_name bar;
  listen 80;
  location / {
    proxy_pass http://bar;
  }
}
server {
  server_name foo;
  listen 80;
  location / {
    proxy_pass http://foo;
    healthcheck uri=/some/path interval=10 fails=3 passes=2;
  }
}
```
