### ISSUE TITLE
Serving http/1.1 not http2

### ISSUE THREAD

**Issue by jh197033** [jwilder/nginx-proxy#2628]
I am using the following docker compose to bring up nginx proxy:

```yaml
services:

  ams_nginx_proxy:
    image: nginxproxy/nginx-proxy
    container_name: ams_nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /home/docker/AMS/AMS_Solution/Docker/Volumes/nginx_config/my_config.conf:/etc/nginx/conf.d/my_config.conf:ro
      - /home/docker/AMS/AMS_Solution/Docker/Volumes/nginx_config/vhost/www.xxx.com_location_override:/etc/nginx/vhost.d/www.xxx.com_location_override
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    restart: unless-stopped
    networks:
        ams_network:
          ipv4_address: 10.0.0.6

  ams_nginx_proxy_acme:
    image: nginxproxy/acme-companion
    container_name: ams_nginx_proxy_acme
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - acme:/etc/acme.sh
    environment:
      - DEFAULT_EMAIL=webmaster@xxx.com
      - NGINX_PROXY_CONTAINER=ams_nginx_proxy
    restart: unless-stopped
    networks:
        ams_network:
          ipv4_address: 10.0.0.7

networks:
  ams_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/24

volumes:
  certs:
  vhost:
  html:
  acme:
```

And then docker compose to bring up a website:

```yaml
ams_accounting_web:
        image: ams_accounting_web_amd64:latest
        container_name: ams_accounting_web
        ports:
            - 1102:1102
        environment:
            - VIRTUAL_HOST=accounting.xxx.com
            - LETSENCRYPT_HOST=accounting.xxx.com
            - ASPNETCORE_URLS=http://+:1102
            - ASPNETCORE_ENVIRONMENT=Production
        volumes:
            # - /home/docker/AMS/AMS_Solution/Docker/Volumes/website_config/AMS_UI/AMS_Accounting/AMS.Accounting.Web/appsettings.Production.json:/app/appsettings.Production.json
            - /home/docker/AMS/AMS_Solution/Docker/Volumes/website_data/ams_resources/media:/media
            - /home/docker/AMS/AMS_Solution/Docker/Volumes/website_data/ams_accounting/wwwroot:/wwwroot
        restart: always
        networks:
            ams_nginx_proxy_ams_network:
              ipv4_address: 10.0.0.12
```

All works ok, but when using google dev tools I get the error that I am using http1.1 and not http2 or 3, what can I do to serve the latest protocol?

<img width="701" alt="Image" src="https://github.com/user-attachments/assets/e7054acb-6b2e-4f6a-866e-0842aad4e1d3" />
