### ISSUE TITLE
Docker Machine: certificate signed by unknown authority

### ISSUE THREAD

**Issue by slnovak** [jwilder/nginx-proxy#280]
Hi,

I'm unable to run nginx-proxy via Docker Machine + Compose on OS X. My configuration is:

```yaml
nginx:
  container_name: nginx
  image: jwilder/nginx-proxy
  ports:
    - 80:80
  environment:
    DOCKER_HOST:
```

Nginx-proxy is able to resolve the Docker daemon (via `DOCKER_HOST`), however I'm receiving the exception:

```
nginx_1 | dockergen.1 | 2015/11/02 23:20:08 Unable to ping docker daemon: Get https://192.168.99.103:2376/_ping: x509: certificate signed by unknown authority
```

Should nginx-proxy be using Docker client [implementation](https://github.com/fsouza/go-dockerclient#using-with-tls) (`NewClientFromEnv`) that reads from the host environment for this situation?

**Comment by md5** [comment]
If that's you're whole `docker-compose.yml`, then you're only giving it `DOCKER_HOST` from the surrounding environment. You're missing all the `DOCKER_TLS_*` variables, so it can't do what you suggest.

**Comment by md5** [comment]
You'll also need to mount in the directory that holds the certificates and private key at the same path where they're found outside the VM.

**Comment by md5** [comment]
Actually, I may have spoke to soon about the interpolation: https://github.com/docker/compose/pull/1765

**Comment by slnovak** [comment]
Ah! Thanks for the heads up. I was able to get it to work with:

```yaml
nginx:
  container_name: nginx
  image: jwilder/nginx-proxy
  ports:
    - 80:80
  environment:
    DOCKER_HOST:
    DOCKER_TLS_VERIFY:
    DOCKER_CERT_PATH:
  volumes:
    - ${DOCKER_CERT_PATH}:${DOCKER_CERT_PATH}
```

nginx-proxy starts up fine and picks up containers as expected.

Thanks for pointing me in the right direction!
