### ISSUE TITLE
What to put in /etc/hosts

### ISSUE THREAD

**Issue by Danielss89** [jwilder/nginx-proxy#354]
Hi
I'm trying to setup this image so i can go to "test.dev" in my browser, but i'm not sure what to put in my /etc/hosts file. Right now i'm using my docker ip and that's not working "No data received".

This is the config in docker-compose.yml:
```
nginx:
  image: jwilder/nginx-proxy
  dns:
    - 8.8.8.8
    - 8.8.4.4
  environment:
    VIRTUAL_HOST: "test.dev"
  links:
    - php
  expose:
    - "80"
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro
  volumes_from:
    - application
```

**Comment by jwilder** [comment]
It should be your docker host ip.

**Comment by Danielss89** [comment]
I've tried that:
```
➜  Proteinbuddet git:(master) ✗ docker-machine ip prl-dev
10.211.55.148
```
And added `10.211.55.148 test.dev` to hosts file.

**Comment by Danielss89** [comment]
```
nginx:
  image: jwilder/nginx-proxy
  links:
    - php
  ports:
    - "11005:80"
  volumes_from:
    - application
  environment:
    VIRTUAL_HOST: "test.dev"
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro
```

and the nginx config created looks like this:
```
root@5f7c7e3c8585:/etc/nginx/conf.d# cat default.conf 
# If we receive X-Forwarded-Proto, pass it through; otherwise, pass along the
# scheme used to connect to this server
map $http_x_forwarded_proto $proxy_x_forwarded_proto {
  default $http_x_forwarded_proto;
  ''      $scheme;
}
# If we receive Upgrade, set Connection to "upgrade"; otherwise, delete any
# Connection header that may have been passed to this server
map $http_upgrade $proxy_connection {
  default upgrade;
  '' close;
}
gzip_types text/plain text/css application/javascript application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript;
log_format vhost '$host $remote_addr - $remote_user [$time_local] '
                 '"$request" $status $body_bytes_sent '
                 '"$http_referer" "$http_user_agent"';
access_log off;
# HTTP 1.1 support
proxy_http_version 1.1;
proxy_buffering off;
proxy_set_header Host $http_host;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection $proxy_connection;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $proxy_x_forwarded_proto;
server {
	server_name _; # This is just an invalid value which will never trigger on a real hostname.
	listen 80;
	access_log /var/log/nginx/access.log vhost;
	return 503;
}
upstream test.dev {
			# proteinbuddet_nginx_1
			server 172.17.0.5:80;
}
server {
	server_name test.dev;
	listen 80 ;
	access_log /var/log/nginx/access.log vhost;
	location / {
		proxy_pass http://test.dev;
	}
}
```
