### ISSUE TITLE
Error under Separate Containers: /etc/docker-gen/templates/nginx.tmpl  is a directory.

### ISSUE THREAD

**Issue by hyp530** [jwilder/nginx-proxy#390]
"Then start the docker-gen container with the shared volume and template". is mentioned in README. Accordingly, I tried by creating a nginx.tmpl in /etc/docker-gen/templates at host (of the docker daemon), but failed to make it works. The container exited in no time after docker run . I found the error in docker logs of the container saying that " /etc/docker-gen/templates/nginx.tmpl is a directory", and don't understand that.

Could you kindly guide me where to set up the nginx.tmpl to start with.

**Comment by helderco** [comment]
How are you declaring your volume on docker run?

**Comment by hyp530** [comment]
Sorry, this question is connected to Nginx-gen.
I exactly follow [https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion](url):
------------------------------------------------------------
 docker run -d -p 80:80 -p 443:443 \
    --name nginx \
    -v /etc/nginx/conf.d  \
    -v /etc/nginx/vhost.d \
    -v /usr/share/nginx/html \
    -v /path/to/certs:/etc/nginx/certs:ro \
    nginx
--------------------------------------------------------------------------------
docker run -d \
    --name nginx-gen \
    --volumes-from nginx \
    -v /path/to/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro \
    -v /var/run/docker.sock:/tmp/docker.sock:ro \
    jwilder/docker-gen \
    -notify-sighup nginx -watch -only-exposed -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
-------------------------------------------------------------------------------------------------
The first one Nginx works normally, but the second one Docker-gen exited in no time. The docker log shows:
2016/03/15 01:24:42 unable to parse template: read /etc/docker-gen/templates/nginx.tmpl: is a directory
-------------------------------------------------------------------------------------------------
I think I don't have the directory /etc/docker-gen/templates/nginx.tmpl at Host. This warning is not clear to me that I don't know how or where to provide nginx.tmpl for parsing. I tried by creating /etc/docker-gen/templates/nginx.tmpl at my Host, but it failed as well.

Could you kindly tell me how to make it? Thank you very much.

**Comment by helderco** [comment]
Have you updated your host paths, such as `/path/to/nginx.tmpl`?

**Comment by hyp530** [comment]
I don't update anything. I just entered the commands exactly following the instructions.

**Comment by kumavis** [comment]
same error here, using the example verbatim https://github.com/fatk/docker-letsencrypt-nginx-proxy-companion-examples/blob/master/docker-compose/v1/simple-site/docker-compose.yml

**Comment by jousch** [comment]
I did a workaround: Mount the folder, not the file.

Seems like there are some issues on the "docker side" ?!

**Comment by hyp530** [comment]
It worked finally after I copied a nginx.tmpl for mounting to the container.

**Comment by stephan-nordnes-eriksen** [comment]
I am having this issue with docker-compose. Any idea on how to fix this?

**Comment by pascalandy** [comment]
@stephan-nordnes-eriksen How do you expect people to help you? It's like asking « who can make me rich ».

Pascal
twitter.com/_pascalandy

**Comment by stephan-nordnes-eriksen** [comment]
"I am having this issue with docker-compose", aka. "I have the same problem as described above when using docker-compose". I have been searching fra a solution for 6 hours, but I am unable to find a solution. Which steps can I take to resolve my issue? Apparently someone in this thread has already solved this issue since it is closed, but not shown exactly how they solved it. Maybe someone can share their knowledge with me?

What more should I have written @pascalandy ?

Also: who can make me rich

**Comment by pascalandy** [comment]
Well I'm just saying that your question is way too vague. Only my IMHOL :)

**Comment by kumavis** [comment]
fwiw i ended up with this setup:
```
nginx-proxy:
  image: jwilder/nginx-proxy
  container_name: nginx-proxy
  restart: always
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - ../../../volumes/proxy/certs:/etc/nginx/certs:ro
    - /etc/nginx/vhost.d
    - /usr/share/nginx/html
    - /var/run/docker.sock:/tmp/docker.sock:ro
  environment:
    DEFAULT_HOST: "yourwebsite.com"

letsencrypt-nginx-proxy-companion:
  image: jrcs/letsencrypt-nginx-proxy-companion
  container_name: letsencrypt-nginx-proxy-companion
  restart: always
  volumes_from:
    - nginx-proxy
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock:ro"
    - "../../../volumes/proxy/certs:/etc/nginx/certs:rw"
```

**Comment by stephan-nordnes-eriksen** [comment]
I ended up migrating the service into a Dockerfile, and use the `build` feature in docker-compose. This seems to solve my issue.

**Comment by MastaP** [comment]
> It worked finally after I copied a nginx.tmpl for mounting to the container.

Worked for me as well, but this manual step sucks. It should be done for each new host. Also, there are multiple versions of this file and not all of them work. Why is it hard to come of with a generic solution instead of everyone finding their own workarounds?

**Comment by murbanowicz** [comment]
I created Dockerfile:
```
  GNU nano 2.5.3                                                      File: Dockerfile                                                                                                                  

FROM jwilder/docker-gen

# VOLUME ["/var/run/docker.sock:/var/run/docker.sock"]
# COPY /var/run/docker.sock /tmp/docker.sock
COPY ./volumes/proxy/templates/nginx.tmpl /etc/docker-gen/templates/nginx.tmpl


ENTRYPOINT ["/usr/local/bin/docker-gen", "-notify-sighup", "nginx", "-watch", "-only-exposed", "-wait", "5s:30s", "/etc/docker-gen/templates/nginx.tmpl", "/etc/nginx/conf.d/default.conf"]

```
and changed my docker-compose:
```
nginx-gen:
    build: ../../../
    container_name: nginx-gen
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"

    volumes_from:
      - nginx
```
but it fails to build...
>Step 2/3 : COPY ./volumes/proxy/templates/nginx.tmpl /etc/docker-gen/templates/nginx.tmpl
>ERROR: Service 'nginx-gen' failed to build: lstat volumes/proxy/templates/nginx.tmpl: no such file or directory
