### ISSUE TITLE
Ordering of the different redirections

### ISSUE THREAD

**Issue by antho1404** [jwilder/nginx-proxy#399]
I have a problem when I want to redirect my different applications via the proxy, I have in my docker compose multiple services I want to redirect to some specific urls, something like that:

- api1 to api1.domain.tld
- api2 to api2.domain.tld
- frontend to *.domain.tld

When i start all this, the ```ngix.tmpl``` takes all my services and create the right upstreams but because of the ```groupByMulti``` which order by alphabetical order, my *.domain.tld is set first so my api is not reachable 

Is there any way to do so ? The possibility to set the order for the redirections, maybe I missed something in the documentation. I know I could use a regex but it's not really convenient to use a regex without all my other subdomains.

**Comment by thomasleveil** [comment]
Have you tried to use  `DEFAULT_HOST` ?

**Comment by antho1404** [comment]
Sorry for the really late answer, I was working on some other stuffs, I tried to use ```DEFAULT_HOST``` without success... Do you have any exemple to make it works with an api and a frontend app that match all subdomains, I've tried many configuration with no success :(

Here is a simplification of my actual docker-compose file

```
nginx-proxy:
  image: jwilder/nginx-proxy
  volumes:
    - ./certs:/etc/nginx/certs:ro
    - /etc/nginx/vhost.d
    - /usr/share/nginx/html
    - /var/run/docker.sock:/tmp/docker.sock
  ports:
    - "80:80"
    - "443:443"
# environment:
#   - DEFAULT_HOST=domain.tld

api:
  build: './api'
  ports:
    - "3000:3000"
  environment:
    - VIRTUAL_HOST=api.domain.tld
    - VIRTUAL_PORT=3000

frontend:
  build: './frontend'
  ports:
    - "8080:8080"
  environment:
#   - DEFAULT_HOST=domain.tld
    - VIRTUAL_HOST=*.domain.tld
    - VIRTUAL_PORT=8080
  links:
    - api
```
