### ISSUE TITLE
Proxy only works when using PORTS in docker-compose but not EXPOSE 

### ISSUE THREAD

**Issue by dj-hedgehog** [jwilder/nginx-proxy#410]
I've got a Nginx-proxy (default config) and Gitlab-Instance running on the same host.
`git.myhost.com` points to the host IP.
When starting Gitlab with `expose:` port 8100 like in the `docker-compose.yml` below I get a `502 Bad Gateway` upon accessing http://git.myhost.com. When I expose it through `ports` it works though.

The generated `/etc/nginx/conf.d/default.conf` in the nginx-proxy container looks fine:

    upstream git.myhost.com {
                    # 2ab9168d-c69e-4725-8c20-31a194ad8d07
                    server 172.17.0.13 vhost;
    }
    server {
            server_name git.myhost.com;
            listen 80 ;
            access_log /var/log/nginx/access.log vhost;
            location / {
                    proxy_pass http://git.myhost.com;
            }
    }

**What am I doing wrong?**

Here's Gitlab's `docker-compose.yml`:

    gitlab-server:
      hostname: git.myhost.com
      expose:
      - "8100"
      ports:
      - 8101:22/tcp
    #  - 8100:8100/tcp THIS WORKS BTW
      labels:
        io.rancher.sidekicks: gitlab-data
      environment:
        GITLAB_OMNIBUS_CONFIG: |
          external_url 'http://git.myhost.com'
          gitlab_rails['gitlab_shell_ssh_port'] = 8101
        VIRTUAL_HOST: git.myhost.com
        VIRTUAL_PORT: 8100
      image: gitlab/gitlab-ce:latest
      volumes_from:
      - gitlab-data

    gitlab-data:
      labels:
        io.rancher.container.start_once: 'true'
      entrypoint:
      - /bin/true
      hostname: gitdata
      image: gitlab/gitlab-ce:latest
      volumes:
      - /etc/gitlab:/etc/gitlab
      - /var/log/gitlab:/var/log/gitlab
      - /var/opt/gitlab:/var/opt/gitlab

**Comment by wader** [comment]
Looking at the [gitlab/gitlab-ce:latest Dockerfile](https://hub.docker.com/r/gitlab/gitlab-ce/~/dockerfile/) is has `EXPOSE 443 80 22`. That means that if you don't provide any `VIRTUAL_PORT` nginx-proxy will forward to port 80 on the container. Note that the forwarding is done on the internal docker network so you don't have to publish any port. So I would try to just remove all ports, expose and `VIRTUAL_PORT`configuration from the docker-compose file. Like this:

```
gitlab-server:
  hostname: git.myhost.com
  labels:
    io.rancher.sidekicks: gitlab-data
  environment:
    GITLAB_OMNIBUS_CONFIG: |
      external_url 'http://git.myhost.com'
      gitlab_rails['gitlab_shell_ssh_port'] = 8101
    VIRTUAL_HOST: git.myhost.com
  image: gitlab/gitlab-ce:latest
  volumes_from:
  - gitlab-data

# ...
```

But it's a bit weird that you get it working using 8100:8100 hmm. Also see #395 which is similar.
