### ISSUE TITLE
Nginx redirection is causing 504 Time-Outs for half of all requests.

### ISSUE THREAD

**Issue by dj-hedgehog** [jwilder/nginx-proxy#420]
Ever since I started using nginx-proxy to route my traffic to my Gitlab containers I'm starting to 504 Timeouts for like 50% of the requests to Gitlab web interface. Without using Nginx-proxy it works flawless.

**What can I do about this?**

```
gitlab-server:
  hostname: git.myhost.com
  ports:
  - 8101:22/tcp
  labels:
    io.rancher.sidekicks: gitlab-data
  environment:
    GITLAB_OMNIBUS_CONFIG: |
      external_url 'http://git.myhost.com'
      gitlab_rails['gitlab_shell_ssh_port'] = 8101
    VIRTUAL_HOST: git.myhost.com
  image: gitlab/gitlab-ce:latest
```
