### ISSUE TITLE
docker-compose error: ERROR: for nginx-proxy  Container command

### ISSUE THREAD

**Issue by sandrodz** [jwilder/nginx-proxy#423]
```
nginx-proxy:
  image: jwilder/nginx-proxy
  ports:
    - "80:80"
    - "443:443"
  restart: always
  environment:
    - DEFAULT_HOST=njord.weare.de.com
  volumes:
    - /srv/certs:/etc/nginx/certs:ro
    - /var/run/docker.sock:/tmp/docker.sock:ro
    - /etc/nginx/vhost.d
    - /usr/share/nginx/html
```

this errors out with: ERROR: for nginx-proxy  Container command '/app/docker-entrypoint.sh' not found or does not exist.

running it as `docker` command works perfectly

**Comment by wader** [comment]
Can you try with verbose? `docker-compose --verbose up` etc? look for `/app` volumes etc. Also might be useful to use run a have a look around `docker-compose run --rm nginx-proxy bash`.
Did this happen on first run or did you do up with different volumes etc?

**Comment by sandrodz** [comment]
actually, I believe I mis interpreted my issue. I've problem when running my full script. When i ran it separately it works.

so:

sudo docker-compose up -d nginx-proxy works fine
sudo docker-compose up -d gives errors
```
nginx-proxy:
  image: jwilder/nginx-proxy
  ports:
    - "80:80"
    - "443:443"
  restart: always
  environment:
    - DEFAULT_HOST=njord.weare.de.com
  volumes:
    - /srv/certs:/etc/nginx/certs:ro
    - /var/run/docker.sock:/tmp/docker.sock:ro
    - /etc/nginx/vhost.d
    - /usr/share/nginx/html


nginx-certs:
  image: jrcs/letsencrypt-nginx-proxy-companion
  volumes:
    - /srv/certs:/etc/nginx/certs:rw
    - /var/run/docker.sock:/var/run/docker.sock:ro
  volumes_from:
    - nginx-proxy


gitlab:
  image: gitlab/gitlab-ce:8.6.5-ce.0
  hostname: gitlab.weare.de.com
  ports:
    - "80"
    - "443"
    - "104.238.171.15:22:22"
  restart: always
  environment:
    - VIRTUAL_HOST=gitlab.weare.de.com
  volumes:
    - /srv/gitlab/config:/etc/gitlab
    - /srv/gitlab/logs:/var/log/gitlab
    - /srv/gitlab/data:/var/opt/gitlab
```
