### ISSUE TITLE
possible to use nginx-proxy as front-end for bare php-fpm

### ISSUE THREAD

**Issue by sandrodz** [jwilder/nginx-proxy#437]
So far, we I've following:

```
nginx-proxy:
  image: jwilder/nginx-proxy
  container_name: nginx-proxy
  ports:
    - "80:80"
    - "443:443"
  restart: always
  environment:
    - DEFAULT_HOST=njord.weare.de.com
  volumes:
    - /srv/certs:/etc/nginx/certs:ro
    - /var/run/docker.sock:/tmp/docker.sock:ro
    - ./vhost.d:/etc/nginx/vhost.d
    - /usr/share/nginx/html


nginx-certs:
  image: jrcs/letsencrypt-nginx-proxy-companion
  container_name: nginx-certs
  volumes:
    - /srv/certs:/etc/nginx/certs:rw
    - /var/run/docker.sock:/var/run/docker.sock:ro
  volumes_from:
    - nginx-proxy
```

this works great with containers that include nginx+backend inside, like gitlab container. But I'm having trouble using bare php7-fpm container. like:

```
php7-fpm:
  image: php:7-fpm
  container_name: php7-fpm
  expose:
    - "9001"
  restart: always
  volumes:
    - /srv/www:/var/www/html
```

any ideas? is this even possible?

**Comment by wader** [comment]
What error do you get? why expose 9001? [Dockerfile](https://github.com/docker-library/php/blob/0783dc544c4db755d177fc7eb16dfce7a53b8383/7.0/fpm/Dockerfile) seems to expose 9000. If you need to expose more than one port read about multiple ports in the README file.

**Comment by sandrodz** [comment]
you are right about `9000` port, I switched to that.

I'm receiving 502 bad gateway.

**Comment by wader** [comment]
Nice, so works now?

**Comment by sandrodz** [comment]
not really :) I'm up for world of pain it seems... now I get server not found error. So for easier troubleshooting I'm including all the docker configs:

```
php7-fpm:
  image: php:7-fpm
  container_name: php7-fpm
  hostname: shop.weare.de.com
  ports:
    - "127.0.0.1:9000:9000"
  restart: always
  environment:
    VIRTUAL_HOST: shop.weare.de.com
    LETSENCRYPT_HOST: shop.weare.de.com
    LETSENCRYPT_EMAIL: support@weare.de.com
  volumes:
    - /srv/www/shop.weare.de.com:/var/www/html
```

nginx-proxy and certs are same as in op.

and I'm trying to add relevant vhost/shop.weare.de.com, if I keep it empty I get 502 bad gateway. if I put php-fpm directive inside:

```
location ~ \.php$ {
   fastcgi_pass shop.weare.de.com:9000;
   fastcgi_index index.php;
}
```

everything stops to work, even other docker containers that automagically worked with nginx-proxy
