### ISSUE TITLE
redirect www to non-www

### ISSUE THREAD

**Issue by sandrodz** [jwilder/nginx-proxy#444]
Is it possible to use nginx-proxy to redirect www to non-www?

I've another nginx under nginx-proxy, when I redirect inside that sub-nginx only https://www is redirected to https://non-www.

Without https it just shows 503 Service Temporarily Unavailable.

**Comment by wader** [comment]
So you only have `VIRTUAL_HOST=www.domain,domain` and do not set `VIRTUAL_PROTO ` or `HTTPS_METHOD`?
And to be clear this is how it behaves?
https://www.domain -> https://domain
https://domain -> serves site
http://www.domain -> 503
http://domain -> https://domain

Maybe generated config would be nice to see

**Comment by sandrodz** [comment]
Hey,

lets go through the example, it will be easier :) so: 

https://wiseadvices.com - all is dandy.
https://www.wiseadvices.com - not found.
http://www.wiseadvices.com - 503 Service Temporarily Unavailable

nginx-proxy
```
nginx-proxy:
  image: jwilder/nginx-proxy
  container_name: nginx-proxy
  ports:
    - "80:80"
    - "443:443"
  restart: always
  volumes:
    - /srv/certs:/etc/nginx/certs:ro
    - /var/run/docker.sock:/tmp/docker.sock:ro
    - ./vhost.d:/etc/nginx/vhost.d
    - /usr/share/nginx/html
```

nginx webserver
```
webserver:
  image: nginx:latest
  container_name: webserver
  ports:
    - "127.0.0.1::80"
    - "127.0.0.1::443"
  links:
    - php5-fpm-alpine
    - php7-fpm-alpine
  restart: always
  environment:
    VIRTUAL_HOST: wiseadvices.com
    LETSENCRYPT_HOST: wiseadvices.com
    LETSENCRYPT_EMAIL: support@weare.de.com
  volumes:
    - ./sites:/etc/nginx/sites
    - ./nginx.conf:/etc/nginx/nginx.conf
    - ./nginx-wp-common.conf:/etc/nginx/nginx-wp-common.conf
    - /srv/www:/www
```

**Comment by wader** [comment]
Ok i think the easiest it to just have:
```
VIRTUAL_HOST: www.wiseadvices.com,wiseadvices.com
LETSENCRYPT_HOST: www.wiseadvices.com,wiseadvices.com
```
Maybe it is possible to do a generic www.domain -> domain redirect somehow with nginx but if you want to do redirect for https://www.domain you will still need a *.domain cert (i don't think letsencrypt support that yet) or have a www.domain cert.

**Comment by sandrodz** [comment]
actually it shouldn't be this way.

nginx-proxy receives both 80 and 443 requests, on everything that has correct dns. So it should be possible to redirect all incoming traffic from www to non www.

On normal nginx install i'd do:

```
server {
         server_name "~^www\.(.*)$" ;
         return 301 $scheme://$1$request_uri ;
}
```

**Comment by wader** [comment]
Yes for http it would work but for https you would need to have valid certificates for all www.* domains you want to redirect.

**Comment by sandrodz** [comment]
okay so what I did in the end is:

```
VIRTUAL_HOST: www.wiseadvices.com,wiseadvices.com
LETSENCRYPT_HOST: wiseadvices.com
```
notice I don't generate ssl for the www version.

and inside second nginx under nginx-proxy I did:

```
server {
         server_name "~^www\.(.*)$" ;
         return 301 $scheme://$1$request_uri ;
}
```

**Comment by amankapoor** [comment]
Hey @sandrodz, I have a similar issue #985. Could you please tell me how you added new server block in the /conf.d/default file? You did it manually, or is there some other way?

**Comment by sandrodz** [comment]
@amankapoor in the end, best option was to:
```
VIRTUAL_HOST: www.wiseadvices.com,wiseadvices.com
LETSENCRYPT_HOST: www.wiseadvices.com,wiseadvices.com
```
and do redirect on the proxied web server

**Comment by hk0i** [comment]
Using multiple VIRTUAL_HOST separated by comma doesn't seem to work for me.
The reverse proxy gets the request, but does nothing. When I check my proxy's nginx config it only shows the non-www upstream. Is there anything else I could try here?

**Comment by Nottt** [comment]
This is not working for me :/ 

I also have a nginx under the nginx-proxy and I have same virtual_host and letsencrypt_host 

```
     VIRTUAL_HOST: drive.domain.app,www.drive.domain.app
      VIRTUAL_PORT: 443
      VIRTUAL_PROTO: https
      LETSENCRYPT_HOST: drive.domain.app,www.drive.domain.app
```

And added this settings to the nginx that is under this nginx docker:

```server {
         server_name "~^www\.(.*)$" ;
         return 301 $scheme://$1$request_uri ;
}```

And still nothing... I can access the www. just fine, with no https errors or anything but won't redirect to cut the www.

**Comment by witten** [comment]
Another option is to use a separate redirect container like https://hub.docker.com/r/morbz/docker-web-redirect/ to redirect www.example.com traffic to example.com. Even works with https if you configure Let's Encrypt on that redirect container.

**Comment by ngocanh** [comment]
I didn't want to create load on the upstreams for a simple redirect. Either an additional intermediate proxy (nginx/apache) as described above or vhost conf for your www.domain.net on nginx-proxy.

_app env_
`
    environment:
      - VIRTUAL_HOST=domain.net,www.domain.net
      - LETSENCRYPT_HOST=domain.net,www.domain.net
`

_nginx-proxy_
`
    volumes:
      - ./data/vhost.d/www.domain.net.conf:/etc/nginx/vhost.d/www.domain.net
`

_www.domain.net.conf_
`
if ($http_host = "www.domain.net") {
    rewrite ^(.*)$ https://domain.net$1 permanent;
}
`

I know
> if is evil

... but only in certain nginx sections

**Comment by terryzwt** [comment]
Here is my sample to resove the problem.
```
version: "3"
services:
  www-redirect:
    image: schmunk42/nginx-redirect
    container_name: example.com-www-redirect
    environment:
      - VIRTUAL_HOST=example.com
      - HTTPS_METHOD=nohttps
      - SERVER_REDIRECT=www.example.com
      - SERVER_REDIRECT_SCHEME=https
```
