### ISSUE TITLE
Docker for Mac supported?

### ISSUE THREAD

**Issue by mattgi** [jwilder/nginx-proxy#445]
Does this work on Docker for Mac and, if so, what environment and volume values are required?

**Comment by mattgi** [comment]
```
nginx:
  image: jwilder/nginx-proxy
  environment:
    - DOCKER_HOST=172.17.0.1:2375
```

in Beta 10
