### ISSUE TITLE
HTTPS_METHOD "noredirect" and docker-compose

### ISSUE THREAD

**Issue by johnrom** [jwilder/nginx-proxy#466]
Hi all,

I'm currently unable to figure out how to configure the https method through docker-compose. I have a bit of a convoluted setup, but hopefully you'll be able to pick out whatever issue I'm having here:

### docker-compose.yml
``` 
front:
  container_name: front
  extends:
    file: docker-dev-common.yml
    service: front

testhttp:
  container_name: testhttp
  extends:
    file: docker-dev-common.yml
    service: wp_site
  volumes_from:
    - testhttp_www
  environment:
    - HTTPS_METHOD=noredirect
    - VIRTUAL_HOST=testhttp.local
  links:
    - testhttp_db:mysql
```

### docker-dev-common.yml
```
front:
  restart: always
  image: jwilder/nginx-proxy
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock
    - ./_conf/front/nginx.conf:/etc/nginx/conf.d/custom.conf
    - ./_conf/certs:/etc/nginx/certs
  ports:
    - "80:80"
    - "443:443"

wp_site:
  restart: always
  image: johnrom/docker-wordpress-wp-cli-xdebug
  working_dir: /var/www/html
  expose:
    - "80"
    - "443"
  environment:
    - XDEBUG_CONFIG
```

The certs exist, and work (causing a redirect to https). The environment variable made it to testhttp:

### testhttp env
```
[
    {
        [...]
        "Config": {
            "Env": [
                "HTTPS_METHOD=noredirect",
                "VIRTUAL_HOST=testhttp.local",
                "XDEBUG_CONFIG=remote_host=192.168.99.1",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "PHP_INI_DIR=/usr/local/etc/php",
                "PHP_EXTRA_BUILD_DEPS=apache2-dev",
                "PHP_EXTRA_CONFIGURE_ARGS=--with-apxs2",
                "GPG_KEYS=0BD78B5F97500D450838F95DFE857D9A90D90EC1 6E4F6AB321FDC07F2C332E3AC2BF0BC433CFC8B3",
                "PHP_VERSION=5.6.20",
                "PHP_FILENAME=php-5.6.20.tar.xz",
                "PHP_SHA256=2b87d40213361112af49157a435e0d4cdfd334c9b7c731c8b844932b1f444e7a",
                "WORDPRESS_VERSION=4.5",
                "WORDPRESS_SHA1=439f09e7a948f02f00e952211a22b8bb0502e2e2"
            ],
        }
        [...]
    }
]
```

My custom.conf only contains: `client_max_body_size 256m;`

However, at the end of the day, I'm still getting the following in `default.conf`:

### default.conf
```
upstream testhttp.local {
                        # testhttp
                        server 172.17.0.28:80;
}
server {
        server_name testhttp.local;
        listen 80 ;
        access_log /var/log/nginx/access.log vhost;
        return 301 https://$host$request_uri;
}
server {
        server_name testhttp.local;
        listen 443 ssl http2 ;
        access_log /var/log/nginx/access.log vhost;
        ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
5-DES-CBC3-SHA;!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB--More--
        ssl_prefer_server_ciphers on;
        ssl_session_timeout 5m;
        ssl_session_cache shared:SSL:50m;
        ssl_certificate /etc/nginx/certs/testhttp.local.crt;
        ssl_certificate_key /etc/nginx/certs/testhttp.local.key;
        add_header Strict-Transport-Security "max-age=31536000";
        location / {
                proxy_pass http://testhttp.local;
        }
}
```

Any idea why the "HTTPS_METHOD=noredirect" environment variable isn't working after a `docker-compose down && docker-compose up -d` ?

- I've deleted the default.conf and confirmed that it is recreated after `down` and `up`

**Comment by wader** [comment]
Strange. Could it be that you have multiple containers with `VIRTUAL_HOST=testhttp.local` running somehow?

**Comment by johnrom** [comment]
Nope, I do have phpmyadmin.testhttp.local running and also webgrind.testhttp.local running, however they all have the "noredirect" option

```
### testhttp_start ###

testhttp_www:
  container_name: testhttp_www
  extends:
    file: docker-dev-common.yml
    service: wp_files
  volumes:
    - ./testhttp/www:/var/www/html
  volumes_from:
    - testhttp_webgrind

testhttp:
  container_name: testhttp
  extends:
    file: docker-dev-common.yml
    service: wp_site
  volumes_from:
    - testhttp_www
  environment:
    - VIRTUAL_HOST=testhttp.local
    - HTTPS_METHOD=noredirect
  links:
    - testhttp_db:mysql

testhttp_db:
  container_name: testhttp_db
  extends:
    file: docker-dev-common.yml
    service: wp_db
  volumes:
    - testhttp_db_volume:/var/lib/mysql

testhttp_pma:
  container_name: testhttp_pma
  extends:
    file: docker-dev-common.yml
    service: wp_pma
  environment:
    - VIRTUAL_HOST=phpmyadmin.testhttp.local
    - HTTPS_METHOD=noredirect
  links:
    - testhttp_db:mysql

testhttp_webgrind:
  container_name: testhttp_webgrind
  extends:
    file: docker-dev-common.yml
    service: wp_webgrind
  environment:
    - VIRTUAL_HOST=webgrind.testhttp.local
    - HTTPS_METHOD=noredirect
  volumes:
    - /tmp

### testhttp_end ###
```

### docker-dev-common.yml
```
wp_files:
  image: johnrom/docker-wordpress-wp-cli-xdebug
  command: /bin/true

wp_site:
  restart: always
  image: johnrom/docker-wordpress-wp-cli-xdebug
  working_dir: /var/www/html
  expose:
    - "80"
    - "443"
  environment:
    - XDEBUG_CONFIG

wp_db:
  restart: always
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: ***

wp_data:
  image: mariadb
  command: /bin/true

wp_pma:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      - PMA_HOST=mysql
      - PMA_USER=***
      - PMA_PASSWORD=***
      - PHP_UPLOAD_MAX_FILESIZE=256M
    expose:
      - "80"
      - "443"

wp_webgrind:
    image: clue/webgrind
    restart: always
    expose:
      - "80"
      - "443"
```
