### ISSUE TITLE
jrcs/letsencrypt-nginx-proxy-companion won't work with HTTPS_METHOD=nohttp

### ISSUE THREAD

**Issue by olivergrahl** [jwilder/nginx-proxy#471]
I think, when using `HTTPS_METHOD=nohttp`, `letsencrypt-nginx-proxy-companion` cannot be used any more.

### Example
```
nginx-proxy:
  image: 'jwilder/nginx-proxy:latest'
  ports:
    - '80:80'
    - '443:443'
  volumes:
    - '/var/run/docker.sock:/tmp/docker.sock:ro'
    - /usr/share/nginx/html
    - /etc/nginx/vhost.d
nginx-proxy-letsencrypt:
  image: 'jrcs/letsencrypt-nginx-proxy-companion:latest'
  volumes:
    - /etc/nginx/certs
    - '/var/run/docker.sock:/var/run/docker.sock:ro'
  volumes_from:
    - nginx-proxy
web:
  image: 'php:5.6-apache'
  environment:
    - HTTPS_METHOD=nohttp
    - LETSENCRYPT_EMAIL=me@test.com
    - LETSENCRYPT_HOST=www.test.com
    - LETSENCRYPT_TEST=true
    - VIRTUAL_HOST=www.test.com

```
### Result
Nginx will return 503 on http://www.test.com/.well-known/acme-challenge/X, because HTTP is not allowed/configured for the host.

Any ideas?
