### ISSUE TITLE
how to set proxy for a container's app running on port 3050?

### ISSUE THREAD

**Issue by rcholic** [jwilder/nginx-proxy#489]
I have an app running on the port number `3050` in a docker container, exposed to the host, and I would like to use this `nginx-proxy` to point url like `http://localhost/users` to point/proxy to `http://localhost:3050/users`.

I have this block in my `docker-compose.yml` file:

```
 nginx_service:
   image: jwilder/nginx-proxy
   container_name: nginx_server
   ports:
    - "80:80"
    - "443:443"
   volumes:
    - ./ssl_certs:/etc/nginx/certs
    - /var/run/docker.sock:/tmp/docker.sock:ro
```

After I bring up the docker containers, I can open `http://localhost:3050/users`, but not `http://localhost/users`, which gives me 503 error for Service Temporarily Unavailable. 

Maybe I am getting the whole idea wrong, could someone help or correct me if my understanding is wrong? Thanks!

**Comment by wader** [comment]
Make sure your app container and nginx-proxy are connected to a common network. It should not be a problem to use on a non-standard web port in the container as long as the container only exposes one port, otherwise you need to give nginx-proxy a hint (VIRTUAL_PORT).

Is this a verison 2 docker compose config?

**Comment by rcholic** [comment]
@wader yes, this is a version 2 docker compose config, below is what I have in the `docker-compose.yml` file:

I have this block in my `docker-compose.yml` file:
```
     nginx_proxy:
       image: jwilder/nginx-proxy
       container_name: nginx_server
       ports:
        - "80:80"
        - "443:443"
       volumes:
        - ./ssl_certs:/etc/nginx/certs
        - /var/run/docker.sock:/tmp/docker.sock:ro
```

Below is the container defined in `docker-compose.yml` that runs my app on the port 3000 exposed to the host:
```
    api:
       build: .
       container_name: api
       environment:
        - VIRTUAL_HOST=net.myservice.api
        - VIRTUAL_PROTO=https
       volumes:
        - "./API:/host"
       links:
        - Mongo:Mongo
       ports:
        - "3000:3000"
```
Do you spot anything wrong? Thanks

**Comment by wader** [comment]
Ok, what i think is missing is that the proxy and web app containers need to share a common network. Take a look at how to configure external networks with docker compose.

**Comment by rcholic** [comment]
I don't think the problem was because of the network, because the containers should be on the same `default network`.  After doing some search and many tries of different settings, I was able to put together a working `docker-compose.yml`.

**The key to making it work is following:**

set the VIRTUAL_HOST=port in the nginx reverse proxy container, this port should be the port that my node.js app runs in its container (not the port mapped on the host!)
If you want the nginx reverse proxy to be on https, you should set up an SSL certificate, but should set http (not https) to the environment variable VIRTUAL_PROTO=http in the web app container.
Below is the working docker-compose.yml:
```
nginx_service:
   image: jwilder/nginx-proxy
   container_name: nginx_server
   ports:
    - "80:80"
    - "443:443"
   volumes:
    - ./ssl_certs:/etc/nginx/certs
    - /var/run/docker.sock:/tmp/docker.sock:ro
   environment:
    - VIRTUAL_PORT=3000  # 3050 port on host does not work!


api:
   build: .
   container_name: api
   environment:
    - VIRTUAL_HOST=service.myserver.com
    - VIRTUAL_PROTO=http   # should be http even if you use https to the proxy, because node.js uses http!
   volumes:
    - "./API:/host"
   links:
    - Mongo:Mongo
   ports:
    - "3050:3000"
```
Hope this will help someone landing on this page from a search engine some day! Thanks @wader
