### ISSUE TITLE
Error running notify command: nginx -s reload

### ISSUE THREAD

**Issue by soupman99** [jwilder/nginx-proxy#491]
Used this to start 2 containers.

```
version: '2'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  whoami:
    image: jwilder/whoami
    container_name: whoami
    environment:
      - VIRTUAL_HOST=whoami.local
```
Then I try to add another container to the mix:
`docker run -d -e VIRTUAL_HOST=whoami3.local jwilder/whoami`
But then I get this error:
`Error running notify command: nginx -s reload, exit status 1`

OSX 10.11.5
Docker version 1.12.0-rc2, build 906eacd, experimental
