### ISSUE TITLE
Websockets result in 502.

### ISSUE THREAD

**Issue by HendrikRoth** [jwilder/nginx-proxy#495]
Hello,

i am trying to get websockets running in nginx-proxy.

i expose the ports 8080 (expressjs app) and 4441 (ws server).

so my docker-compose config looks like this:

```
my-websocket-app:
  ports:
    - 3000:8080
    - 3001:4441
  environment:
    - VIRTUAL_HOST=www.mypage.com
    - VIRTUAL_PORT=8080
```

I also tried to create a second app running with the same container, to be sure to listen internally to 4441/websocket instead of the 8080 port for the node express app.

```
my-websocket-app-socket:
  ports:
    - 3001:4441
  environment:
    - VIRTUAL_HOST=ws.mypage.com
    - VIRTUAL_PORT=4441
```

but i always receive an 502 for the websocket (wss). nginx-proxy is using letsencrypt ssl cerificates here.
Any idea how i could fix/ detect the real error for this?

**Comment by wader** [comment]
So expressjs app and ws server are running in two different containers? can you give full compose config for containers and how you start nginx-proxy?

You can dump generated nginx config with `docker exec <nginx-proxy-container> cat /etc/nginx/conf.d/default.conf`.

**Comment by HendrikRoth** [comment]
At the moment i am running two containers, but it is the same image. Normally i would like to run this in just one container. I'm running it in two containers at the moment because i don't know how to make both ports accessable?

docker-compose.yml:
```
nginx-proxy:
        container_name: nginx-proxy
        image: jwilder/nginx-proxy
        ports:
                - 80:80
                - 443:443
        volumes:
                - /var/run/docker.sock:/tmp/docker.sock:ro
                - /data/proxy/certs:/etc/nginx/certs:ro
                - /data/proxy/htpasswd:/etc/nginx/htpasswd:ro
                - /data/proxy/vhost.d:/etc/nginx/vhost.d
                - /data/proxy/proxy.conf:/etc/nginx/conf.d/my_proxy.conf:ro
                - /etc/nginx/vhost.d
                - /usr/share/nginx/html
                #- /data/proxy/default.conf:/etc/nginx/conf.d/extra.conf:ro
        environment:
                - DEFAULT_HOST=www.pagisto.com

nginx-proxy-certs:
        container_name: proxy-certs
        image: jrcs/letsencrypt-nginx-proxy-companion
        volumes_from:
                - nginx-proxy
        volumes:
                - /data/proxy/certs:/etc/nginx/certs:rw
                - /var/run/docker.sock:/var/run/docker.sock:ro

mypage-main:
        container_name: mypage-main
        image: mypage-main
        ports:
                - 3027:8080
        links:
                - couchdb:db
        volumes:
                - /data/ssh:/root/.ssh:ro
        environment:
                - VIRTUAL_HOST=main.mypage.com
                - WS_HOST=wss://main.mypage.com
                - WS_PORT=80
                - VIRTUAL_PORT=8080

mypage-ws:
        container_name: mypage-ws
        image: mypage-main
        ports:
                - 3028:4441
                                                                                                                                                                                                                                                   413,17        93%
        ports:
                - 3028:4441
        links:
                - couchdb:db
        volumes:
                - /data/ssh:/root/.ssh:ro
        environment:
                - VIRTUAL_HOST=ws.mypage.com
                - WS_HOST=wss://ws.mypage.com
                - WS_PORT=443
                - VIRTUAL_PORT=4441
```

and the /etc/nginx/conf.d/default.conf:

```
# If we receive X-Forwarded-Proto, pass it through; otherwise, pass along the
# scheme used to connect to this server
map $http_x_forwarded_proto $proxy_x_forwarded_proto {
  default $http_x_forwarded_proto;
  ''      $scheme;
}
# If we receive Upgrade, set Connection to "upgrade"; otherwise, delete any
# Connection header that may have been passed to this server
map $http_upgrade $proxy_connection {
  default upgrade;
  '' close;
}
gzip_types text/plain text/css application/javascript application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript;
log_format vhost '$host $remote_addr - $remote_user [$time_local] '
                 '"$request" $status $body_bytes_sent '
                 '"$http_referer" "$http_user_agent"';
access_log off;
# HTTP 1.1 support
proxy_http_version 1.1;
proxy_buffering off;
proxy_set_header Host $http_host;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection $proxy_connection;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $proxy_x_forwarded_proto;
server {
	server_name _; # This is just an invalid value which will never trigger on a real hostname.
	listen 80;
	access_log /var/log/nginx/access.log vhost;
	return 503;
}
upstream mypage.com {
			# mypage-about
			server 172.17.0.2:8080;
}
server {
	server_name mypage.com;
	listen 80 ;
	access_log /var/log/nginx/access.log vhost;
	return 301 https://$host$request_uri;
}
server {
	server_name mypage.com;
	listen 443 ssl http2 ;
	access_log /var/log/nginx/access.log vhost;
	ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
	ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA;
	ssl_prefer_server_ciphers on;
	ssl_session_timeout 5m;
	ssl_session_cache shared:SSL:50m;
	ssl_certificate /etc/nginx/certs/mypage.com.crt;
	ssl_certificate_key /etc/nginx/certs/mypage.com.key;
	add_header Strict-Transport-Security "max-age=31536000";
	include /etc/nginx/vhost.d/mypage.com;
	location / {
		proxy_pass http://mypage.com;
                include /etc/nginx/vhost.d/mypage.com_location;
	}
}
upstream ws.mypage.com {
			# mypage-ws
			server 172.17.0.16:4441;
}
server {
	server_name ws.mypage.com;
	listen 80 ;
	access_log /var/log/nginx/access.log vhost;
	return 301 https://$host$request_uri;
}
server {
	server_name ws.mypage.com;
	listen 443 ssl http2 ;
	access_log /var/log/nginx/access.log vhost;
	ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
	ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA;
	ssl_prefer_server_ciphers on;
	ssl_session_timeout 5m;
	ssl_session_cache shared:SSL:50m;
	ssl_certificate /etc/nginx/certs/ws.mypage.com.crt;
	ssl_certificate_key /etc/nginx/certs/ws.mypage.com.key;
	add_header Strict-Transport-Security "max-age=31536000";
	location / {
		proxy_pass http://ws.mypage.com;
	}
}
upstream www.mypage.com {
			# mypage-www
			server 172.17.0.10:8080;
}
server {
	server_name www.mypage.com;
	listen 80 default_server;
	access_log /var/log/nginx/access.log vhost;
	return 301 https://$host$request_uri;
}
server {
	server_name www.mypage.com;
	listen 443 ssl http2 default_server;
	access_log /var/log/nginx/access.log vhost;
	ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
	ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA;
	ssl_prefer_server_ciphers on;
	ssl_session_timeout 5m;
	ssl_session_cache shared:SSL:50m;
	ssl_certificate /etc/nginx/certs/www.mypage.com.crt;
	ssl_certificate_key /etc/nginx/certs/www.mypage.com.key;
	add_header Strict-Transport-Security "max-age=31536000";
	location / {
		proxy_pass http://www.mypage.com;
                include /etc/nginx/vhost.d/www.mypage.com_location;
	}
}
```
