### ISSUE TITLE
Compose using already running nginx-proxy container

### ISSUE THREAD

**Issue by b3nk3** [jwilder/nginx-proxy#499]
Hi,

I have a running nginx-proxy container and a ghost container using the proxy. I have started these with the `docker run -d etc` command.

I am planning to build a wordpress container, and I wish to use my running image, and I am building this with docker-compose.

Can I somehow add my env to the compose file, so my localhost site would be proxied to my other domain?

**Comment by wader** [comment]
Not sure i follow what you want to do. To use compose together with nginx-proxy is most just to have:
```yml
version: "2"
services:
    ... cut ...
    environment:
      - VIRTUAL_HOST=example.com
```
Any maybe make sure the containers are sharing common network etc

**Comment by b3nk3** [comment]
So I have the below compose file, and now I assume I am having the connection problem due to the containers not sharing the same network. Essentially, I'd like to have the mysql server to have a port on the localhost and so I could use it with other containers? Does it make sense?

I am really new to docker.. and compose as well.
```
version: '2'
services:
  db:
    image: mysql:5.7
    volumes:
      - "./.data/db:/var/lib/mysql"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=wordpress
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    links:
      - db
    ports:
      - "127.0.0.1:8000:80"
    restart: always
    environment:
      - VIRTUAL_HOST=mydomain.co.uk
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_PASSWORD=wordpress
```

**Comment by wader** [comment]
Hi again, yes i think so too. Take a look at this comment https://github.com/jwilder/nginx-proxy/issues/478#issuecomment-230502324

You want to also access the db container from the host or from other containers?

**Comment by b3nk3** [comment]
So I have 2 containers running as below

```
CONTAINER ID        IMAGE                 COMMAND                  CREATED             STATUS              PORTS                         NAMES
de53e38974fe        ghost                 "/entrypoint.sh npm s"   5 days ago          Up 4 hours          127.0.0.1:2368->2368/tcp      blog
0fde6e87dfb4        jwilder/nginx-proxy   "/app/docker-entrypoi"   6 days ago          Up 4 hours          0.0.0.0:80->80/tcp, 443/tcp   proxy
```
With a yaml file I am creating a wordpress-mysql-phpmyadmin triumph. As per the yaml below:

```
version: '2'
services:
  mysql:
      image: mysql:5.7
      environment:
        - MYSQL_ROOT_PASSWORD=password
        - MYSQL_DATABASE=wordpress
  web:
      image: wordpress
      links:
        - mysql
        - proxy
      ports:
        - "127.0.0.1:8080:80"
      environment:
        - WORDPRESS_DB_PASSWORD=password
        - VIRTUAL_HOST=mydomain.co.uk

  phpmyadmin:
    image: corbinu/docker-phpmyadmin
    links:
      - mysql
    ports:
      - "127.0.0.1:8181:80"
    environment:
      - MYSQL_USERNAME=wordpress
      - MYSQL_ROOT_PASSWORD=wordpress
```

It starts on the localhost and works perfectly both on my mac and on my DO server. However I cannot map it to a domain via nginx-proxy. Not on my mac (something.local) nor the server, which has ubuntu 16.04.

Any Idea?
