### ISSUE TITLE
Disable Logs

### ISSUE THREAD

**Issue by stevezau** [jwilder/nginx-proxy#503]
Hi There,

Do you have any way to disable the logging within nginx-proxy?

We use logging solutions to pull logs from all docker containers console logs. We don't want the nginx-proxy logs.

I would disable collecting logs from that container but the solution we are using does not have 'exclude' container filters, only include.

Last resort is for me to build a dockerfile based off your image?

**Comment by philicious** [comment]
Same for me:

I would require the original nginx access/error logs to feed them into Graylog via GELF or syslog logging driver. However nginx-proxy outputs them to STDOUT but with color codes like 
```
[0;36;1mnginx.1 | [0macme.com 141.8.143.143 - - [12/Jul/2016:13:34:36 +0000] "GET /rew...
```
So there are several ways I could get them how I want them, however I havent found a way to disable the nginx-proxy output. (which also includes the docker-gen output)

If theres no simple config to disable the output, I'd appreciate a hint on code where I could do it "manually"

**Comment by wader** [comment]
Maybe https://github.com/kitpages/nginx-proxy/pull/1 is interesting? hopefully only thing needed is to also /dev/null docker-gen

**Comment by philicious** [comment]
thx for the hint  @wader 

I also meanwhile found #165 which is quite similar and the suggested solution of running nginx/docker-gen in separate containers and thereby avoiding forego, seemed to work for that guy. 
So I'll try that.

I'm not sure if that would help @stevezau tho

**Comment by afefelov** [comment]
Hi guys, I'm using graylog and rsyslog to pass logs into it.
I spent up to 4 hours to find out proper solution and finally came with following:

You should add rsyslog conf file like that /etc/rsyslog.d/30-docker.conf:

```
module(load="mmexternal")
if $syslogtag contains 'nginx' then action(type="mmexternal" binary="/usr/bin/strip_ansi_colors.py" interface.input="msg" )
```

while /usr/bin/strip_ansi_colors.py looks like:

```
#! /usr/bin/python

import sys
import re
import json

def onInit():
	""" Do everything that is needed to initialize processing (e.g.
	    open files, create handles, connect to systems...)
	"""
	pass


def onReceive(msg):
	"""This is the entry point where actual work needs to be done. It receives
	   the messge from rsyslog and now needs to examine it, do any processing
	   necessary. The to-be-modified properties (one or many) need to be pushed
	   back to stdout, in JSON format, with no interim line breaks and a line
	   break at the end of the JSON. If no field is to be modified, empty
	   json ("{}") needs to be emitted.
	   Note that no batching takes place (contrary to the output module skeleton)
	   and so each message needs to be fully processed (rsyslog will wait for the
	   reply before the next message is pushed to this module).
	"""
	ansi_escape = re.compile(r'#033[^m]*m') # ansi colors
	msg = ansi_escape.sub('', msg)
	nginx_escape = re.compile(r"\s+nginx.*\|\s+") # duplicating nginx call
	msg = nginx_escape.sub('', msg)
	print json.dumps({'msg': msg})

def onExit():
	""" Do everything that is needed to finish processing (e.g.
	    close files, handles, disconnect from systems...). This is
	    being called immediately before exiting.
	"""
	# most often, nothing to do here


"""
-------------------------------------------------------
This is plumbing that DOES NOT need to be CHANGED
-------------------------------------------------------
Implementor's note: Python seems to very agressively
buffer stdouot. The end result was that rsyslog does not
receive the script's messages in a timely manner (sometimes
even never, probably due to races). To prevent this, we
flush stdout after we have done processing. This is especially
important once we get to the point where the plugin does
two-way conversations with rsyslog. Do NOT change this!
See also: https://github.com/rsyslog/rsyslog/issues/22
"""
onInit()
keepRunning = 1
while keepRunning == 1:
	msg = sys.stdin.readline()
	if msg:
		msg = msg[:-1] # remove LF
		onReceive(msg)
		sys.stdout.flush() # very important, Python buffers far too much!
	else: # an empty line means stdin has been closed
		keepRunning = 0
onExit()
sys.stdout.flush() # very important, Python buffers far too much!
```

how logs look before:

```
Mar 11 16:23:26 example.com nginx[15004]: #033[0;36;1mdockergen.1 | #033[0;31;1m2017/03/11 15:23:26 Generated '/etc/nginx/conf.d/default.conf' from 1 containers
Mar 11 18:07:10 example.com nginx[15004]: #033[0;33;1mnginx.1    | #033[0mexample.com 195.255.255.255 - - [11/Mar/2017:17:07:10 +0000] "GET / HTTP/1.1" 503 214 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/602.4.8 (KHTML, like Gecko) Version/10.0.3 Safari/602.4.8"
```

and now
```
Mar 11 18:50:49 example.com nginx[15004]: dockergen.1 | 2017/03/11 17:50:49 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification 'nginx -s reload'
Mar 11 18:50:51 example.com nginx[15004]: example.com 195.64.208.216 - - [11/Mar/2017:17:50:51 +0000] "GET / HTTP/1.1" 503 214 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/602.4.8 (KHTML, like Gecko) Version/10.0.3 Safari/602.4.8"
```

**Comment by catmeme** [comment]
I appreciate all the hard work jwilder has put into this (was super easy to get started with this docker image, thank you), but I realized my development environment was starting to diverge from my production setup too much, with "untrusted" or harder to maintain code.

My solution was to move to the official nginx image, define a static docker network, and then manually write out my vhosts, and confs. This is a more manual solution, but it's using an official image and is more aligned with my production deployment. YMMV.

Below is an example of such a setup with two python wsgi apps served by gunicorn behind the proxy.

**docker-compose.yml**

```yml
version: '2'
services:
     Databases
     postgres:
        ports:
            - "5432:5432"
        networks:
            mydocker-net:
                ipv4_address: 172.20.238.201
     app_auth:
        command: ./bin/wait-for-services.sh postgres gunicorn -c config/gunicorn.conf.py --reload -b "0.0.0.0:8011" --chdir src auth:app
        expose:
            - "8011"
        networks:
            mydocker-net:
                ipv4_address: 172.20.238.11
     app_web:
        command: ./bin/wait-for-services.sh postgres gunicorn -c config/gunicorn.conf.py --reload -b "0.0.0.0:8012" --chdir src web:app
        expose:
            - "8012"
        networks:
            mydocker-net:
                ipv4_address: 172.20.238.12

    # Entrypoint
    nginx_proxy:
        ports:
            - "80:80"
            - "443:443"
        networks:
            mydocker-net:
                ipv4_address: 172.20.238.5
                aliases:
                    - auth.coolapp.local
                    - web.coolapp.local

networks:
    mydocker-net:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.20.238.0/24
                  gateway: 172.20.238.1

```

**default.conf**

```
# If we receive X-Forwarded-Proto, pass it through; otherwise, pass along the
# scheme used to connect to this server
map $http_x_forwarded_proto $proxy_x_forwarded_proto {
  default $http_x_forwarded_proto;
  ''      $scheme;
}
# If we receive Upgrade, set Connection to "upgrade"; otherwise, delete any
# Connection header that may have been passed to this server
map $http_upgrade $proxy_connection {
  default upgrade;
  '' close;
}
gzip_types text/plain text/css application/javascript application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript;
log_format vhost '$host $remote_addr - $remote_user [$time_local] '
                 '"$request" $status $body_bytes_sent '
                 '"$http_referer" "$http_user_agent"';
access_log off;
# HTTP 1.1 support
proxy_http_version 1.1;
proxy_buffering off;
proxy_set_header Host $http_host;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection $proxy_connection;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $proxy_x_forwarded_proto;
proxy_connect_timeout       600;
proxy_send_timeout          600;
proxy_read_timeout          600;
send_timeout                600;

# Mitigate httpoxy attack (see README for details)
proxy_set_header Proxy "";
server {
        server_name _; # This is just an invalid value which will never trigger on a real hostname.
        listen 80;
        access_log /var/log/nginx/access.log vhost;
        return 503;
}


#
# START EDITING BELOW HERE
#

upstream auth.coolapp.local {
        server 172.20.238.11:8011;
}
server {
        server_name auth.coolapp.local;
        listen 80;
        access_log /var/log/nginx/access.log vhost;
        include /etc/nginx/vhost.d/auth.coolapp.local;
        location / {
                proxy_pass http://auth.coolapp.local;
        }
}

upstream web.coolapp.local {
        server 172.20.238.10:8012;
}
server {
        server_name web.coolapp.local;
        listen 80;
        access_log /var/log/nginx/access.log vhost;
        include /etc/nginx/vhost.d/web.coolapp.local;
        location / {
                proxy_pass http://web.coolapp.local;
        }
}
```

**web.coolapp.local.conf** *(sites-available)*

```
keepalive_timeout 5;

# path for static files
root /application/static;

location /static/ {
    alias /application/static/;
    autoindex off;
}

location @proxy_to_app {
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    # enable this if and only if you use HTTPS
    proxy_set_header X-Forwarded-Proto https;
    proxy_set_header Host $http_host;
    # we don't want nginx trying to do something clever with
    # redirects, we set the Host: header above already.
    proxy_redirect off;
    proxy_pass http://web.coolapp.local;
    proxy_http_version 1.1;
    proxy_pass_header Server;
}

error_page 500 502 503 504 /500.html;
location = /500.html {
    root /application/static/errors;
}
```
