### ISSUE TITLE
Prevent 301 Moved permanently to proxy location

### ISSUE THREAD

**Issue by RafaelKr** [jwilder/nginx-proxy#524]
Hi, I have the following setup:

nginx-proxy is started with docker-compose up -d
```
version: '2'

services:
    nginx-proxy:
        container_name: nginx-proxy
        image: jwilder/nginx-proxy
        restart: unless-stopped
        networks:
            - default
        ports:
            - "80:80"
        volumes:
            - "/var/run/docker.sock:/tmp/docker.sock:ro"
```

Then I have running Apache in a new container and serving a project with
```
version: '2'

services:
    my-domain:
        image: RafaelKr/apache:latest
        networks:
            - my-domain
            - nginx-proxy
        expose:
            - "3000"
        restart: unless-stopped
        environment:
            VIRTUAL_HOST: "my-domain.dev"
        volumes:
            - "./generated:/var/www:ro"

networks:
    my-domain:
    nginx-proxy:
        external:
            name: nginxproxy_default
```

If I make a request to `http://my-domain.dev/contact/`, everything is working fine, but if I use `http://my-domain.dev/contact`, then I get a status code `301 Moved permanently` and a header `Location: http://my-domain.dev:3000/contact/`. It tries to redirect me to the container and fails then, because the port is only exposed to the nginx-network.

I have set a proxy_redirect in my /etc/nginx/conf.d/default.conf like this:
```
server {
        server_name my-domain.dev;
        listen 80 ;
        access_log /var/log/nginx/access.log vhost;
        location / {
                proxy_pass http://my-domain.dev/;
                proxy_redirect http://my-domain.dev:3000/ http://my-domain.dev/;
        }
}
```
and also tried some other posibilities (`proxy_redirect default;`, `proxy_redirect off;`, `proxy_redirect http://my-domain.dev:3000/(.*) http://my-domain.dev/$1;`, ...), but nothing worked as expected.

Do you know any possibility to change this behavior with the nginx-config? Or do I have to change the configuration of Apache? (What I would like to avoid!)

**Update:**
To clarify: I would like to have this redirect, but without the port.
And before somone is asking: Yes, I did a `service nginx reload` after changing something in the config.
