### ISSUE TITLE
[SSL] What to do when a server exposes only port 80?

### ISSUE THREAD

**Issue by peperunas** [jwilder/nginx-proxy#528]
I have several services that expose only port 80 thus being insecure.
I'd like to access them through HTTPS so I put a docker-compose config like this:

```
  shortener:
   image: local/shortener
   environment:
   - VIRTUAL_HOST=example.org
   - VIRTUAL_PROTO=https
   - VIRTUAL_PORT=80
```

But when I try to access the page I get this in the logs:

`[error] 32#32: *1 SSL_do_handshake() failed (SSL: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol) while SSL handshaking to upstream, client: 5.91.126.59, server: example.org, request: "GET /favicon.ico HTTP/1.1", upstream: "https://172.18.0.7:80/favicon.ico", host: "example.org", referrer: "https://example.org"`

What should I do?
