### ISSUE TITLE
mounting volume

### ISSUE THREAD

**Issue by berdof** [jwilder/nginx-proxy#546]
I'm a little bit confused. I am dockerizing yii framework app.
And stock with some issues.
For instance when I call `__FILE__` inside my php script it says that the directory is `/app` but the mounted volume is in `/www/html/jnet`. A lot off yii scripts are based on __FILE__ magic so I want get it to work. 

here is my docker-compose: 
```
nginx-proxy:
  image: jwilder/nginx-proxy
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock
    - /home/berdof/docker/vhost.d:/etc/nginx/vhost.d
    - /usr/share/nginx/html

jnetapp:
  image: baseimg
  restart: always
  links:
    - mariadb:mysql
  environment:
    - VIRTUAL_HOST=jnet.im
  volumes_from:
    - jnet_data

mariadb:
  image: mariadb
  restart: always
  environment:
    - MYSQL_ROOT_PASSWORD=123456
    - MYSQL_DATABASE=root
  volumes_from:
    - jnet_dbdata

jnet_dbdata:
  image: busybox
  container_name: jnet_dbdata
  volumes:
    - /www/mysql/jnet:/var/lib/mysql

jnet_data:
  image: busybox
  container_name: jnet_data
  volumes:
    - /www/html/jnet:/var/www/html


```

Am I doing something wrong? 
Also when I connect to nginx container I can see that it's current dirrectory is /app . 

Thanks for any help!
Btw this is really great proxy!
