### ISSUE TITLE
Error running notify command: nginx -s reload, exit status 1

### ISSUE THREAD

**Issue by aneumeier** [jwilder/nginx-proxy#547]
Hi,

With this docker-compose file:

```
version: "2"

services:
  proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./certs:/etc/nginx/certs"
      - "/etc/nginx/vhost.d"
      - "/usr/share/nginx/html"
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
[...]
```

I receive the following error immediately after starting the container:

> nginx-proxy    | dockergen.1 | 2016/08/27 19:08:03 Running 'nginx -s reload'
> nginx-proxy    | dockergen.1 | 2016/08/27 19:08:03 Error running notify command: nginx -s reload, exit status 1

This happens since updating docker to 1.12.1, I am not aware of other changes.

Running `nginx -s reload` from a one-off container gives the following:

> 2016/08/27 19:12:28 [notice] 7#7: signal process started
> 2016/08/27 19:12:28 [error] 7#7: open() "/var/run/nginx.pid" failed (2: No such file or directory)
nginx: [error] open() "/var/run/nginx.pid" failed (2: No such file or directory)

Anything I can change?
