### ISSUE TITLE
Recommended configuration w/ docker-compose

### ISSUE THREAD

**Issue by corradio** [jwilder/nginx-proxy#552]
Hi,

I have several stacks (i.e. applications) running on a server based on multiple docker-compose configurations. They all, by default, run on their own bridge network.
What is the recommended way of running the nginx-proxy? I tried to run it on the host network, but it didn't work (it creates empty `upstream` sections).
The only workaround I found for now is to have both the proxy and the different backends join the same default bridge network.

**Comment by RafaelKr** [comment]
This is my current solution:

```
version: '2'

services:
    example:
        image: RafaelKr/apache
        networks:
            - example
            - nginx-proxy
        restart: unless-stopped
        environment:
            VIRTUAL_HOST: "www.example.dev"
        volumes:
            - "./src:/var/www:ro"

networks:
    example:
    nginx-proxy:
        external:
            name: nginxproxy_default
```

**Comment by corradio** [comment]
Thanks, that's the best I have for now :)

**Comment by RafaelKr** [comment]
Here I also have my configuration I'm using for WordPress:
```
version: '2'

services:
    db:
        image: mariadb
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: "change_me"
            MYSQL_DATABASE: "change_me"
            MYSQL_USER: "change_me"
            MYSQL_PASSWORD: "change_me"
        networks:
            - change_me_net
        volumes:
            - ../data/docker/db:/var/lib/mysql

    wordpress:
        depends_on:
            - db
        image: suedsolutions/wordpress
        restart: unless-stopped
        hostname: change_me
        environment:
            VIRTUAL_HOST: www.change_me.dev
            WORDPRESS_DB_HOST: maria.db
            WORDPRESS_DB_NAME: "change_me"
            WORDPRESS_DB_USER: "change_me"
            WORDPRESS_DB_PASSWORD: "change_me"
            WORDPRESS_TABLE_PREFIX: "change_me"
        networks:
            - change_me_net
            - nginx-proxy
        links:
            - db:maria.db
        volumes:
            - ../data/docker/wordpress:/var/www/html
            - ./src/themes:/var/www/html/wp-content/themes:ro
            - ../data/docker/logs:/var/log/apache2

networks:
    change_me_net:
    nginx-proxy:
        external:
            name: nginxproxy_default
```
There you can see, that I have one network for the apps internal communication (`change_me_net`) and for the services which should be available through a Virtual Host I also add the network `nginx-proxy`.

Hope this helps you and maybe some others. :)

**Comment by CWSpear** [comment]
Is there an advantage to @RafaelKr's technique over just setting `nginx-proxy`'s to the default?

```
networks:
  default:
    external:
      name: pandora_default
```

Then you don't need a `networks` entry under any of the services. i.e., take @RafaelKr's example and change it thusly:

```
version: '2'

services:
    db:
        image: mariadb
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: "change_me"
            MYSQL_DATABASE: "change_me"
            MYSQL_USER: "change_me"
            MYSQL_PASSWORD: "change_me"
        volumes:
            - ../data/docker/db:/var/lib/mysql

    wordpress:
        depends_on:
            - db
        image: RafaelKr/wordpress
        restart: unless-stopped
        hostname: change_me
        environment:
            VIRTUAL_HOST: www.change_me.dev
            WORDPRESS_DB_HOST: maria.db
            WORDPRESS_DB_NAME: "change_me"
            WORDPRESS_DB_USER: "change_me"
            WORDPRESS_DB_PASSWORD: "change_me"
            WORDPRESS_TABLE_PREFIX: "change_me"
        links:
            - db:maria.db
        volumes:
            - ../data/docker/wordpress:/var/www/html
            - ./src/themes:/var/www/html/wp-content/themes:ro
            - ../data/docker/logs:/var/log/apache2

networks:
    default:
        external:
            name: nginxproxy_default
```

**Comment by mausquirk** [comment]
To understand the complete picture: Can you also publish the docker-compose-file for the proxy itself?

**Comment by CWSpear** [comment]
@mausquirk 

```yaml
version: '2'

services:
  nginx-proxy:
    restart: always
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    networks:
      - nginxproxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

# this creates a network we can connect to in other docker-compose 
# files called `nginxproxy_default` as an *external* network (see other comment) 
networks:
  nginxproxy:
```

You can add in automatic SSL via Lets Encrypt with something like:

```yaml
version: '2'

services:
  nginx-proxy:
    restart: always
    image: jwilder/nginx-proxy
    container_name: pandora_nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    networks:
      - nginxproxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - certs:/etc/nginx/certs:ro

  letsencrypt-nginx-proxy-companion:
    restart: always
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: pandora_letsencrypt-nginx-proxy-companion
    volumes_from:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs:rw

volumes:
  certs:
    driver_opts:
      type: none
      device: /data/letsencrypt-nginx-proxy-companion/certs/
      o: bind

networks:
  nginxproxy:
```

**Comment by murbanowicz** [comment]
Gents, I used this config provided by @CWSpear but looking at `docker stats` proxy-companion is using 100% of CPU. What is wrong? How to debug it ?

**Comment by murbanowicz** [comment]
Hi Gents,
I spent like 2 hrs trying to sort it out by myself but I can't find the way.

I am using docker-compose for nginx-proxy and letsencrypt companion together.

This is my `docker-compose.yml` for them:
```
version: '2'                                                                                                             
                                                                                                                         
services:                                                                                                                
  nginx-proxy:                                                                                                           
    restart: always                                                                                                      
    image: jwilder/nginx-proxy                                                                                           
    container_name: proxy_nginx-proxy                                                                                    
    ports:                                                                                                               
      - 80:80                                                                                                            
      - 443:443                                                                                                          
    networks:                                                                                                            
      - nginxproxy                                                                                                       
    volumes:                                                                                                             
      - /var/run/docker.sock:/tmp/docker.sock:ro                                                                         
      - /etc/nginx/vhost.d                                                                                               
      - /usr/share/nginx/html                                                                                            
      - /data/letsencrypt-nginx-proxy-companion/certs/:/etc/nginx/certs:ro                                               
                                                                                                                         
  letsencrypt-nginx-proxy-companion:                                                                                     
networks:
      - nginxproxy                                                                                                       
    restart: always                                                                                                      
    image: jrcs/letsencrypt-nginx-proxy-companion                                                                        
    container_name: proxy_letsencrypt-nginx-proxy-companion                                                              
    volumes_from:                                                                                                        
      - nginx-proxy                                                                                                      
    volumes:                                                                                                             
      - /var/run/docker.sock:/var/run/docker.sock:ro                                                                     
      - /data/letsencrypt-nginx-proxy-companion/certs/:/etc/nginx/certs:rw           

networks:                                                                                                                
  nginxproxy:                                                                                                            
    external:                                                                                                            
      name: nginxproxy     
```
Not sure if it is working really correctly as calling my VPS IP giving nginx 503 error.

Going further I have my wordpress container.
```
version: '2'                                                                                                             
                                                                                                                         
services:                                                                                                                
  db:                                                                                                                    
    image: mysql:8                                                                                                       
    volumes:                                                                                                             
      - /var/docker-images/neopolis/mysql:/var/lib/mysql                                                                 
    restart: always                                                                                                      
    environment:                                                                                                         
      MYSQL_ROOT_PASSWORD: pass                                                                              
      MYSQL_DATABASE: wp_neopolis                                                                                        
      MYSQL_USER: neopolis                                                                                               
      MYSQL_PASSWORD: pass                                                                                  
                                                                                                                         
  wordpress:                                                                                                             
    depends_on:                                                                                                          
      - db                                                                                                               
    image: wordpress:latest                                                                                              
    hostname: mydomain.com 
networks:                                                                                                            
      - nginxproxy                                                                                                       
    links:                                                                                                               
       - db                                                                                                              
    expose:                                                                                                              
      - "80"                                                                                                             
    ports:                                                                                                               
      - "127.0.0.1:8080:80"                                                                                              
    restart: always                                                                                                      
    environment:                    
    VIRTUAL_HOST: mydomain.com                                                                                          
      WORDPRESS_DB_NAME: wp_neopolis                                                                                     
      WORDPRESS_DB_HOST: db:3306                                                                                         
      WORDPRESS_DB_PASSWORD: pass                                                                            
    volumes:                                                                                                             
      - /var/www/neopolis:/var/www/html/                                                                                 
                                                                                                                         
networks:                                                                                                                
  nginxproxy:                                                                                                            
    external:              
     name: nginxproxy  
```
When I check nginx conf in nginx-proxy container, I see upstream but port never changes no matter what I put in expose or porst. I was trying many different combinations, always getting error (connection refused, not nginx page).

It redirects from http to https so something is happening but nothing correct...

**Comment by TeoTN** [comment]
I just wonder... how is this even possible that noone cares about this issue for a year now?

**Comment by pqvst** [comment]
There seem to be two different issues here.

### 1. General docker-compose issues:
I found this repo, and it works flawlessly for me:
https://github.com/evertramos/docker-compose-letsencrypt-nginx-proxy-companion

### 2. Run multiple applications on the same server with one proxy:
Unfortunately this is a docker-compose limitation. I've put together a simple example demonstrating how I've solved it (based on the above solution):
https://github.com/pqvst/multi-app-docker-compose-letsencrypt-nginx-proxy

**Comment by j16sdiz** [comment]
Since the nginx-proxy have access to the `/var/run/docker.sock` already, can we have the nginx-docker connect to some network automatically?

There are codes in https://github.com/jwilder/nginx-proxy/blob/master/test/conftest.py already, can we reuse the code?

**Comment by kimonoki** [comment]
I'm trying to make docker-compose work with other docker containers. Is there a way to setup this?

**Comment by HasBert** [comment]
For anyone who's interested using docker-compose v3+ with [nginx-proxy](https://github.com/jwilder/nginx-proxy) and [docker-letsencrypt-nginx-proxy-companion](https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion) and have problems setting up a container on https, [here](https://github.com/buchdag/letsencrypt-nginx-proxy-companion-compose) is a sample docker-compose.yml project.

Unlike if you start your containers with `docker run` command the docker-letsencrypt-nginx-proxy-companion container doesn't know the id of the nginx-proxy container, so you have to pass the container name (id) in an environment variable to docker-letsencrypt-nginx-proxy-companion. Like that:
```ỳaml
version: '3.7'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ....

  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-proxy-letsencrypt
    ....
    environment: 
      NGINX_PROXY_CONTAINER: nginx-proxy
```

In docker-compsoe v3+ we also have the problem, that the `volumes_from` tag is not available anymore, so you need to setup named volumes. Check out my working docker-compose.yml file. As a application which should be hosted under https I choose phpmyadmin for testing purpose.
**NOTE**: you need to create a network beforehand with `docker network create nginx-proxy`.
```yaml
version: '3.7'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro

  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-proxy-letsencrypt
    restart: always
    volumes:
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment: 
      NGINX_PROXY_CONTAINER: nginx-proxy

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on: 
      - nginx-letsencrypt
      - nginx-proxy
    expose: 
      - 80
    environment:
      MYSQL_ROOT_PASSWORD: super_password
      VIRTUAL_HOST: your.dns.domain
      LETSENCRYPT_HOST: your.dns.domain

volumes:
  conf:
  vhost:
  html:
  certs:

networks:
  default:
    external:
      name: nginx-proxy
```

Cheers
