### ISSUE TITLE
VIRTUAL_PORT=8080 doesn't work on second container

### ISSUE THREAD

**Issue by Rocks360** [jwilder/nginx-proxy#554]
Hello, 
 I have the following two docker-compose.yml files:

```
version: '2'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  coming-soon:
    image: afrosckick/coming-soon
    container_name: afroschick-coming-soon
    environment:
      - VIRTUAL_HOST=afroschick.de, www.afroschick.de
```
and
```
version: '2'
services:
  Jenkins:
    image: Jenkins
    container_name: jenkins
    ports:
      - "50000:50000"
    volumes:
      - /var/jenkins_home
    environment:
      - VIRTUAL_PORT=8080
      - VIRTUAL_HOST=jenkins.domain.de, www.domain.de, jenkins.domain.de, www.jenkins.domain.de
```
After the "docker-compose up command in for the two files that are in differed folders located all the docker containers running.

```
CONTAINER ID        IMAGE                    COMMAND                  CREATED             STATUS              PORTS                                NAMES
20e6fa899f94        jenkins                  "/bin/tini -- /usr/lo"   10 minutes ago      Up 10 seconds       8080/tcp, 0.0.0.0:50000->50000/tcp   jenkins
91d03f089cfd        jwilder/nginx-proxy      "/app/docker-entrypoi"   3 days ago          Up 3 days           0.0.0.0:80->80/tcp, 443/tcp          nginx-proxy
1940ac48ea84        afrosckick/coming-soon   "httpd-foreground"       3 days ago          Up 3 days           80/tcp                               afroschick-coming-soon
```

I get the above output when I run "docker ps" command.  But the jenkins container is still not accessible with any of the domains given by the VIRTUAL-HOST environment variable. But the "afroschick-coming-soon" container is accessible by its domain dress given by the VIRTUAL-HOST environment variable. Maybe is it a problem that the domains given by the VIRTUAL-HOST environment variable contains letters like ä,ü ?

**Comment by wader** [comment]
Hi, i think the problem is that the nginx-proxy container does not share any network with the "Jenkins" service container. In older version of docker-compose all containers where connected to the bridge network but in newer version each docker-compose project instead creates a <project_name>_default network.

I do something like this:

Run just nginx-proxy in docker-compose config:
```
version: '2'
services:
  nginx:
    ... other config ....
    networks:
     - nginx-proxy

networks:
  nginx-proxy:
    external:
      name: nginx-proxy
```

In other docker-compose configs with services that should be proxied:
```
version: '2'
services:
  app:
    ... other config ...
    environment:
      - VIRTUAL_HOST=...
    networks:
     - nginx-proxy

networks:
  nginx-proxy:
    external:
      name: nginx-proxy
```

This will make nginx-proxy and the proxied services all join a network called "nginx-proxy" (confusingly i also named the compose network alias "nginx-proxy"). You can check the config with `docker network ls` and `docker network inspect nginx-proxy`.

**Comment by Rocks360** [comment]
Thank you for your fast answer. I will try your solution and comment if that fixed it or not. 
:)

**Comment by Rocks360** [comment]
I updated the two docker-compose.yml files to the following:
first:
```
version: '2'
      
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - nginx-proxy
      
  coming-soon:
    image: afrosckick/coming-soon
    container_name: afroschick-coming-soon
    environment:
      - VIRTUAL_HOST=afroschick.de, www.afroschick.de
    networks:
      - nginx-proxy

networks:
   nginx-proxy:
    external:
      name: nginx-proxy
```
second:
```
version: '2'
services:
  Jenkins:
    image: Jenkins
    container_name: jenkins
    ports:
      - "50000:50000"
    volumes:
      - /var/jenkins_home
    environment:
      - VIRTUAL_PORT=8080
      - VIRTUAL_HOST=jenkins.mydomain.de, www.jenkins.mydomain.de
    networks:
      - nginx-proxy 
      
networks:
  nginx-proxy:
    external:
      name: nginx-proxy
```
the "docker ps" gives now the following output again: 
```
CONTAINER ID        IMAGE                    COMMAND                  CREATED             STATUS              PORTS                                NAMES
c658b52d0796        jenkins                  "/bin/tini -- /usr/lo"   3 minutes ago       Up 3 seconds        8080/tcp, 0.0.0.0:50000->50000/tcp   jenkins
2a3f9078935a        jwilder/nginx-proxy      "/app/docker-entrypoi"   15 minutes ago      Up 15 minutes       0.0.0.0:80->80/tcp, 443/tcp          nginx-proxy
1c49ba3284f4        afrosckick/coming-soon   "httpd-foreground"       15 minutes ago      Up 15 minutes       80/tcp                               afroschick-coming-soon
```
and the "docker network inspect nginx-proxy" returns the following:
```
[
    {
        "Name": "nginx-proxy",
        "Id": "84ee6c9040167db05c8316d39a219ce9653ac39cd4c82d7cc0ff287fc947fd3d",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": {},
            "Config": [
                {
                    "Subnet": "172.20.0.0/16",
                    "Gateway": "172.20.0.1/16"
                }
            ]
        },
        "Internal": false,
        "Containers": {
            "1c49ba3284f4b54c3f989a643521464f33862350db67f74deb8a8fc1467beb01": {
                "Name": "afroschick-coming-soon",
                "EndpointID": "be9a437fb24f932ed904bab2f9f3476fd23374e5e5a4900b2c2c8613a143d1d4",
                "MacAddress": "02:42:ac:14:00:02",
                "IPv4Address": "172.20.0.2/16",
                "IPv6Address": ""
            },
            "2a3f9078935a420b9c5d4dc290043d6784f3b706cf20df5c39c7c4e0f48daa15": {
                "Name": "nginx-proxy",
                "EndpointID": "f629edcbeac150fb32ddd906e2c4b97cd6ce67e12b6c91009e9c50a16cc7df64",
                "MacAddress": "02:42:ac:14:00:03",
                "IPv4Address": "172.20.0.3/16",
                "IPv6Address": ""
            },
            "c658b52d0796c45eab54b3ac6591627e2781cf76132a3117bb37d7c7edd5c70b": {
                "Name": "Jenkins",
                "EndpointID": "a1c0776497e38a75bca50e2ca78d7dd666d3b3359bd841f3b507e0379c64daa7",
                "MacAddress": "02:42:ac:14:00:04",
                "IPv4Address": "172.20.0.4/16",
                "IPv6Address": ""
            }
        },
        "Options": {},
        "Labels": {}
    }
]
```
To me it looks all fine. I don't get any errors. But jenkins is still "503 Service Temporarily Unavailable" over the browser.
