### ISSUE TITLE
Can't get example to work

### ISSUE THREAD

**Issue by lukasoppermann** [jwilder/nginx-proxy#583]
Hey,

I am trying to get the simple example from the readme to work. I am using docker on my mac. I copied the `docker-compose.yml` straight from the page:

```
version: '2'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  whoami:
    image: jwilder/whoami
    container_name: whoami
    environment:
      - VIRTUAL_HOST=whoami.local
```

I added the following to my `hosts` file:

```
127.0.0.1 whoami.local
```

Afterwards I ran `docker-compose up -d`. No error, nothing. But when I view `whoami.local` in the browser or via the curl command I only get the `nginx` page:

```
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
    body {
        width: 35em;
        margin: 0 auto;
        font-family: Tahoma, Verdana, Arial, sans-serif;
    }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>
```

Please advise, thanks.
