### ISSUE TITLE
Custom Nginx Configuration "Per-VIRTUAL_HOST" not working

### ISSUE THREAD

**Issue by JulienFauconnier** [jwilder/nginx-proxy#584]
Like the title said:
```
$ docker run -d -p 80:80 -p 443:443 -v /path/to/vhost.d:/etc/nginx/vhost.d:ro -v /var/run/docker.sock:/tmp/docker.sock:ro jwilder/nginx-proxy
$ { echo 'server_tokens off;'; echo 'client_max_body_size 100m;'; } > /path/to/vhost.d/app.example.com

```
Doest'nt work at all

```
In logs nginx d'ont see changes:
dockergen.1 | 2016/09/25 22:16:18 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification 'nginx -s reload'
dockergen.1 | 2016/09/25 22:16:18 Watching docker events
dockergen.1 | 2016/09/25 22:16:18 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification 'nginx -s reload'
dockergen.1 | 2016/09/25 22:16:36 Received event start for container 09056c8e05ef
dockergen.1 | 2016/09/25 22:16:36 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification 'nginx -s reload'
dockergen.1 | 2016/09/25 22:16:36 Received event die for container 09056c8e05ef
dockergen.1 | 2016/09/25 22:16:37 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification 'nginx -s reload'
dockergen.1 | 2016/09/25 22:16:44 Received event start for container 7466cea03db7
dockergen.1 | 2016/09/25 22:16:45 Received event start for container 0c1a221f6d00
dockergen.1 | 2016/09/25 22:16:46 Generated '/etc/nginx/conf.d/default.conf' from 4 containers
dockergen.1 | 2016/09/25 22:16:47 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification 'nginx -s reload'
```

and later i have
`nginx.1    | 2016/09/25 22:25:37 [error] 34#34: *93 client intended to send too large body: 9239688 bytes, client: 92.88.250.224, server: cloud.nemesis.gdn, request: "PUT /remote.php/webdav/Mi3/Pictures/IMG_1945Apres.jpg HTTP/1.1", host: "cloud.nemesis.gdn"`

My docker-compose file:

```
nginx-proxy:
  image: jwilder/nginx-proxy
  container_name: nginx-proxy
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - /etc/nginx/certs:/etc/nginx/certs:ro
    - /usr/share/nginx/html
    - /etc/nginx/vhost.d:/etc/nginx/vhost.d:ro
    - /var/run/docker.sock:/tmp/docker.sock:ro

```
