### ISSUE TITLE
Wrong cert used for host. A.B.C.com used instead of B.C.com

### ISSUE THREAD

**Issue by joshstrange** [jwilder/nginx-proxy#591]
I have nginx-proxy setup with the companion containers to handle https for my 2 urls but for some reason the wrong cert is being used for the one at a higher level.

Example:

api.dev.foo.com and dev.foo.com and when I hit api.dev.foo.com I get a valid certificate but when I try to access dev.foo.com it throws an https warning and when I inspect the cert I can see it's using the api.dev.foo.com cert.

I ssh'd into the machine and looked at the docker volume and there are certs for both api.dev.foo.com and dev.foo.com. I use rancher to deploy these containers and I just took over this from someone else, it used to work but broke sometime recently. Below is the docker-compose contents for these sites (urls hidden)

```
web-frontend:
  environment:
    LETSENCRYPT_EMAIL: accounts@XXXXXXXX.com
    LETSENCRYPT_HOST: dev.XXXXXXXX.com
    VIRTUAL_HOST: dev.XXXXXXXX.com
  tty: true
  image: XXXXXXXX
  stdin_open: true
web-api:
  environment:
    LETSENCRYPT_EMAIL: accounts@XXXXXXXX.com
    LETSENCRYPT_HOST: api.dev.XXXXXXXX.com
    VIRTUAL_HOST: api.dev.XXXXXXXX.com
  tty: true
  image: XXXXXXXX
  stdin_open: true
```

Any help would be awesome, thanks!
