### ISSUE TITLE
504 Gateway Time-out

### ISSUE THREAD

**Issue by returntrip** [jwilder/nginx-proxy#594]
I am getting a time out error when using docker-gen with nginx and letsencrypt. I think it might be due to a configuration issue in my docker-compose.yml and I wanted to ask for some help.

I have added the nginx.tmpl with

`curl https://raw.githubusercontent.com/jwilder/nginx-proxy/master/nginx.tmpl > nginx.tmpl`

I have added the bridge network with 

`docker network create -d bridge nginx-proxy`

The letsencrypt certificates are retreived and installed in the correct folders and I can see the certificate is valid (the browser will retrive the certificate after the time out).

Here is also my docker-compose.yml. I have substituted my domain with a dummy one.

```
version: "2"

services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/etc/nginx/conf.d"
      - "/etc/nginx/vhost.d"
      - "/usr/share/nginx/html"
      - "../../../volumes/proxy/certs:/etc/nginx/certs:ro"
    networks:
      - proxy-tier
  nginx-gen:
    image: jwilder/docker-gen
    container_name: nginx-gen
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "/home/user/wordpress/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro"
    volumes_from:
      - nginx
    entrypoint: /usr/local/bin/docker-gen -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-nginx-proxy-companion
    volumes_from:
      - nginx
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "../../../volumes/proxy/certs:/etc/nginx/certs:rw"
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=nginx-gen

  wordpress:
    image: wordpress
    container_name: wordpress
    ports:
      - 8000:80
    environment:
      - WORDPRESS_DB_PASSWORD=example
      - VIRTUAL_HOST=blog.dummy.com
      - VIRTUAL_NETWORK=nginx-proxy
      - LETSENCRYPT_HOST=blog.dummy.com
      - LETSENCRYPT_EMAIL=user@gmail.com
    networks:
      - proxy-tier
      - default
 
  mysql:
    image: mariadb
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=example
    networks:
      - proxy-tier
      - default

networks:
  proxy-tier:
    external:
      name: nginx-proxy
```

I have also:

- tested the wordpress container by mapping to port 8000 on the host (see above in docker-compose) and it worked
- exposed wordpress container port 80 with no success

Thanks in advance for your help.

**Comment by wader** [comment]
Hi, does the "wordpress" image expose any port or more then one port? make sure it exports correct ports and maybe use `VIRTUAL_PORT` if nginx-proxy uses the wrong port.

How does the generated config look? check with `docker exec <nginx-proxy-container> cat /etc/nginx/conf.d/default.conf`?

Does nginx-proxy log anything interesting?

What modifications have you done to the default template?

**Comment by returntrip** [comment]
Thanks for your reply.

The wordpress image exposes only port 80 and I have also tried to use VIRTUAL_PORT=80 but without success.

The nginx config seems fine, although I am no expert. Pasting it below.

I have not modified the original nginx.tmpl

The Nginx logs do not produce any noticeable error.

I will test with a different app to see what happens.
```
# If we receive X-Forwarded-Proto, pass it through; otherwise, pass along the
# scheme used to connect to this server
map $http_x_forwarded_proto $proxy_x_forwarded_proto {
  default $http_x_forwarded_proto;
  ''      $scheme;
}
# If we receive Upgrade, set Connection to "upgrade"; otherwise, delete any
# Connection header that may have been passed to this server
map $http_upgrade $proxy_connection {
  default upgrade;
  '' close;
}
gzip_types text/plain text/css application/javascript application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript;
log_format vhost '$host $remote_addr - $remote_user [$time_local] '
                 '"$request" $status $body_bytes_sent '
                 '"$http_referer" "$http_user_agent"';
access_log off;
# HTTP 1.1 support
proxy_http_version 1.1;
proxy_buffering off;
proxy_set_header Host $http_host;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection $proxy_connection;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $proxy_x_forwarded_proto;
# Mitigate httpoxy attack (see README for details)
proxy_set_header Proxy "";
server {
	server_name _; # This is just an invalid value which will never trigger on a real hostname.
	listen 80;
	access_log /var/log/nginx/access.log vhost;
	return 503;
}
upstream blog.dummy.com {
				## Can be connect with "wordpress_default" network
			# wordpress
			server 172.19.0.2:80;
}
server {
	server_name blog.dummy.com;
	listen 80 ;
	access_log /var/log/nginx/access.log vhost;
	return 301 https://$host$request_uri;
}
server {
	server_name blog.dummy.com;
	listen 443 ssl http2 ;
	access_log /var/log/nginx/access.log vhost;
	ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
	ssl_ciphers 'ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:ECDHE-ECDSA-DES-CBC3-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:DES-CBC3-SHA:!DSS';
	ssl_prefer_server_ciphers on;
	ssl_session_timeout 5m;
	ssl_session_cache shared:SSL:50m;
	ssl_session_tickets off;
	ssl_certificate /etc/nginx/certs/blog.dummy.com.crt;
	ssl_certificate_key /etc/nginx/certs/blog.dummy.com.key;
	ssl_dhparam /etc/nginx/certs/blog.dummy.com.dhparam.pem;
	add_header Strict-Transport-Security "max-age=31536000";
	include /etc/nginx/vhost.d/default;
	location / {
		proxy_pass http://blog.dummy.com;
	}
}
```

**Comment by wader** [comment]
Strange, i would expect some error being logged. How did you check the log, `docker-compose logs`?

You can manually check if nginx-proxy can reach wordpress by doing something like this:
```
$ docker exec -ti <nginx-proxy-conatiner> bash
$ ping 172.19.0.2 # IP from generate config
$ apt-get update && apt-get install netcat curl
$ nc -v 172.19.0.2:80
$ curl -v -H "Host: blog.dummy.com" http://172.19.0.2
```
How do you test btw? I alos noticed that nginx-gen is not part of the nginx-proxy network hmm?

**Comment by returntrip** [comment]
Thanks for the help I am now able to connect to the wordpress blog!

 `nc -v 172.19.0.2:80` was producing the following error: 
`172.19.0.2:80: forward host lookup failed: Unknown host`

Therefore I thought there was no routing between the wordpress and nginx images, so I added the `default` network to the nginx image and bang it worked....

Will test thoroughly and close this issue!

**Comment by wader** [comment]
Ok, good. But weird... they are both connected to the "proxy-tier" network?

**Comment by returntrip** [comment]
Yes and I have even removed from :

wordpress image and nginx image

```
 networks:
      - proxy-tier
```

And I have also removed the following external network:

```
networks:
  proxy-tier:
    external:
      name: nginx-proxy
```

Is it supposed to still work?!?! I thought that the external network nginx-proxy was required?!?!

This is the output of `docker network ls`
```

NETWORK ID          NAME                DRIVER              SCOPE
92d3d1bffb38        bridge              bridge              local               
ec2e22673b51        host                host                local               
1b18e275c36b        none                null                local               
e51cf6692e7b        wordpress_default   bridge              local
```

I am really confused now....  Hope someone can clarify please.
