### ISSUE TITLE
phpMyAdmin not working behind nginx-proxy?  #2002 - php_network_getaddresses

### ISSUE THREAD

**Issue by victor-lund** [jwilder/nginx-proxy#596]
I am having problems getting phpMyAdmin working behind the nginx-proxy server and i can't figure out what i am doing wrong.

My config files:

**docker/site/docker-compose.yml**
```
version: '2'
services:
  phpmyadmin:
    restart: always
    image: phpmyadmin/phpmyadmin
    links:
      - db
    environment:
      - VIRTUAL_HOST=db.mydomain.com
    networks:
      - nginx-proxy

  db:
    restart: always
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: asd
      MYSQL_DATABASE: asd
      MYSQL_USER: asd
      MYSQL_PASSWORD: asd
    volumes:
      - ./shared_db_volume:/var/lib/mysql/

  web:
    image: richarvey/nginx-php-fpm:php7
    container_name: containerc
    environment:
      - VIRTUAL_HOST=test.mydomain.com
    expose:
      - '80'
    volumes:
      - ./html:/var/www/html/
    restart: always
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    external:
      name: nginx-proxy
```

**docker/proxy/docker-compose.yml**
```
version: '2'
services:
  nginxproxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
     - nginx-proxy

networks:
  nginx-proxy:
    external:
      name: nginx-proxy
```

When i run this, i can access both the test.mydomain.com and db.mydomain,com without a problem. However - when trying to log in with my login credentials at db.mydomain.com, i get the following issue:
```
 #2002 - php_network_getaddresses: getaddrinfo failed: Name does not resolve — The server is not responding (or the local server's socket is not correctly configured). 
```

There is a way to solve the issue but it is not to my satisfaction:
The phpmyadmin service be set up in such a way that it bypasses the nginx-proxy network entirely - like this:

```
version: '2'
services:
  phpmyadmin:
    restart: always
    image: phpmyadmin/phpmyadmin
    links:
      - db
    ports:
      - 8080:80
##    environment:
##      - VIRTUAL_HOST=db.mydomain.com
##   networks:
##      - nginx-proxy
```
In this "solution", phpMyAdmin can be accessed at ***any*** subdomain at port 8080 (not very elegant. Note how all the connections to the network are commented out).

***What i want*** is to access my phpmyadmin login at a ***specific*** subdomain db.mydomain.com.

Preferably, the phpmyadmin service would be behind the nginx-proxy network, but if it is not possible i guess i can live without it...

Have spent days trying to crack this one, any help or guidelines would be very appreciated!

**Comment by wader** [comment]
Hi, try to change networks for "phpmyadmin" to:
 
```
networks:
  - default
  - nginx-proxy
```

Im quite sure compose will only join the networks specified for a service which means it will not automatically join the default network for the compose project.

**Comment by victor-lund** [comment]
Many thanks wader, that did it! It now works beautifully!

Closing.

**Comment by victor-lund** [comment]
Hello again, so I'm reopening this issue because I now have the exact same phpMyAdmin error message in a **multi-site / multi-database** situation. With two sites and two databases I have set up my config like this:

docker/**proxy**/docker-compose.yml (exakt same as my first post)

```
version: '2'
services:
  nginxproxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
     - nginx-proxy

networks:
  nginx-proxy:
    external:
      name: nginx-proxy
```

docker/**a**/docker-compose.yml
```
version: '2'
services:
  phpmyadmin:
    restart: always
    image: phpmyadmin/phpmyadmin
    links:
      - db
    environment:
      VIRTUAL_HOST: db.a.mydomain.com
    networks:
      - a
      - nginx-proxy

  db:
    restart: always
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - ./shared_db_volume:/var/lib/mysql/
    networks:
      - a

  web:
    image: richarvey/nginx-php-fpm:php7
    environment:
      - VIRTUAL_HOST=a.mydomain.com
    expose:
      - '80'
    volumes:
      - ./html:/var/www/html/
    restart: always
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    external:
      name: nginx-proxy
  a:
    external:
      name: a
```

docker/**b**/docker-compose.yml 
```
version: '2'
services:
  phpmyadmin:
    restart: always
    image: phpmyadmin/phpmyadmin
    links:
      - db
    environment:
      VIRTUAL_HOST: db.b.mydomain.com
    networks:
      - b
      - nginx-proxy

  db:
    restart: always
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - ./shared_db_volume:/var/lib/mysql/
    networks:
      - b

  web:
    image: richarvey/nginx-php-fpm:php7
    environment:
      - VIRTUAL_HOST=b.mydomain.com
    expose:
      - '80'
    volumes:
      - ./html:/var/www/html/
    restart: always
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    external:
      name: nginx-proxy
  b:
    external:
      name: b
```
The proxy and both of the two systems are startable, and i can reach the sites a.mydomain.com and b.mydomain.com. However, only the site **that is started first** can be properly accessed from phpMyAdmin.

Example: If i start docker/**a**/docker-compose.yml, before docker/**b**/docker-compose.yml I can with no issue login to **a**'s database from phpmyadmin at db.a.mydomain.com. However, after starting docker/**b**/docker-compose.yml, I get the nasty #2002 error when trying to login at db.b.mydomain.com. It still works perfectly with db.a.mydomain.com. (The opposite problem occurs when starting b before a).

At first I thought i could solve it by starting two separate networks - a and b (instead of using "default" one on both sites). This proved however fruitless.

So again, I am wondering what I'm missing.... Any hints would be much appreciated...!

**Comment by wader** [comment]
Hmm could it be that there is a conflict over the hostname "db"? try to use different names. I don't think you need the a and b network and can also remove the links (only needed if you want to have aliases)

**Comment by victor-lund** [comment]
So, this is _very_ peculiar...

When I change the name of the mariadb service from "db" to whatever, I cannot access the database through phpmyadmin at all - the #2002 error appears. (This is when I am setting up one site and database only).

It simply appears as if the only name of the database service is  "db" (!?). Is there a bug with the phpmyadmin image or maridb image? Have i done a spectacular oversight?

This is my config:
```
version: '2'
services:
  phpmyadmin:
    restart: always
    image: phpmyadmin/phpmyadmin
    links:
      - dba
    environment:
      VIRTUAL_HOST: db.a.mydomain.com
    networks:
      - default
      - nginx-proxy
  dba:
    restart: always
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MARIADB_DATABASE: dba
    volumes:
      - ./shared_db_volume:/var/lib/mysql/

  web:
    image: richarvey/nginx-php-fpm:php7
    environment:
      - VIRTUAL_HOST=a.mydomain.com
    expose:
      - '80'
    volumes:
      - ./html:/var/www/html/
    restart: always
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    external:
      name: nginx-proxy
``` 

To conclude, the above config does not work, but this (below) does...

```
version: '2'
services:
  phpmyadmin:
  ...
    links:
      - db
  ...
...
  db:
    restart: always
    image: mariadb
...
```

This is beyond frustrating.

**Comment by wader** [comment]
Did you change `PMA_HOST` for phpmyadmin/phpmyadmin? it seems to be `db` by default.

**Comment by victor-lund** [comment]
Hello again,

It looks like you were on to something using the PMA_HOST variable. In combination with adding an alias to the link between phpmyadmin and the database it was possible to change the name of the database service and still reach it with phpmyadmin:
```
...
  phpmyadmin-b:
    restart: always
    image: phpmyadmin/phpmyadmin
    links:
      - db-b:dbb #alias corresponding to the PMA_HOST variable
    environment:
      VIRTUAL_HOST: db.b.mydomain.com
      PMA_HOST: dbb #host 
    networks:
      - default
      - nginx-proxy
  db-b:
    restart: always
    image: mariadb
...
```

**However** - in spite having different names on all my services for the A and B sites, (phpmyadmin-a // phpmyadmin-b, db-a // db-b etc.) and using different host names - it appears to be some collision preventing my databases (or phpmyadmin sevices) to co-exist. I still get the **#2002** error when trying to access the second site that is started.

So, my setup looks like this now:

docker/a/docker-compose.yml
```
version: '2'
services:
  phpmyadmin-a:
    restart: always
    image: phpmyadmin/phpmyadmin
    links:
      - db-a:dba
    environment:
      VIRTUAL_HOST: db.a.mydomain.com
      PMA_HOST: dba
    networks:
      - default
      - nginx-proxy

  db-a:
    restart: always
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - ./shared_db_volume:/var/lib/mysql/

  web-a:
    image: richarvey/nginx-php-fpm:php7
    environment:
      - VIRTUAL_HOST=b.mydomain.com
    expose:
      - '80'
    volumes:
      - ./html:/var/www/html/
    restart: always
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    external:
      name: nginx-proxy
```

docker/b/docker-compose.yml
```
version: '2'
services:
  phpmyadmin-b:
    restart: always
    image: phpmyadmin/phpmyadmin
    links:
      - db-b:dbb
    environment:
      VIRTUAL_HOST: db.b.mydomain.com
      PMA_HOST: dbb
    networks:
      - default
      - nginx-proxy

  db-b:
    restart: always
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - ./shared_db_volume:/var/lib/mysql/

  web-b:
    image: richarvey/nginx-php-fpm:php7
    environment:
      - VIRTUAL_HOST=b.mydomain.com
    expose:
      - '80'
    volumes:
      - ./html:/var/www/html/
    restart: always
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    external:
      name: nginx-proxy
```

So to summarize, now both the site works "alone" but when both are running, I can only access the database which is connected to the site i start first. To clarify, the same example as i posted before is still valid:

>If i start docker/a/docker-compose.yml, before docker/b/docker-compose.yml I can with no issue login to a's database from phpmyadmin at db.a.mydomain.com. However, after starting docker/b/docker-compose.yml, I get the nasty #2002 error when trying to login at db.b.mydomain.com. It still works perfectly with db.a.mydomain.com. (The opposite problem occurs when starting b before a).


By the way - I also tried a setup with to separate networks "a" and "b" instead of connecting to the "default" network (I thought that maybe my problem was that both site's databases were hosted on the same network). Unfortunately, the exact same problem occurred. So - in spite having two separate networks and all services having different names there seems to be a collision...   

Could there be an issue with ports or IP's in some way? Any other ideas?
