### ISSUE TITLE
503 Unavailable when running example docker-compose.yml

### ISSUE THREAD

**Issue by peterpme** [jwilder/nginx-proxy#600]
Hello,

This looks amazing and I appreciate you putting it together!

That being said, I think I'm a bit lost when running the example:

```dockerfile
version: '2'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "8888:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
  whoami:
    image: jwilder/whoami
    container_name: whoami
    environment:
      - VIRTUAL_HOST=whoami.local
```

When I run this and hit `http://localhost:8888` in the browser, I get "503 Service Unavailable". I read through some of the other issues and this is supposed to occur if you're not running any containers. But I am running the `whoami` container aren't I?

When I run the curl command `curl -H "Host: whoami.local" localhost:8888` in the example, I do get the correct response but why do I need to pass a header to get that? What is this doing for me?

If there are any other resources I can take a look at that would be amazing!

Thanks again for your patience

**Comment by tevjef** [comment]
```yml
version: '2'
services:
  nginx-proxy: # defines a service that listens for containers with the `VIRTUAL_HOST` env
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "8888:80" # maps port 8888 on your host to port 80 on the container
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro # Used for getting container information e.g start, stop events, id, name, environment variables...
  whoami:  # defines a service, or rather, a simple HTTP server that responds with the container's hostname in response to a GET request
    image: jwilder/whoami
    container_name: whoami
    environment:
      - VIRTUAL_HOST=whoami.local # nginx-proxy looks for this env to generate a nginx config for this host name. 
```
Bringing up this service with generates a nginx configuration with a virtual host roughly like this
```
# A gross oversimplification 
server {
    server_name whoami.local;
    listen 80;
    location / {
    	proxy_pass 172.17.0.2:8000;
    }
}
server {
    server_name _; 
    listen 80;
    return 503
}
```
`curl -H "Host: whoami.local" localhost:8888` Sends a GET request with the `Host` header `whoami.local`.  Requests with this header with hit the first server block in the above nginx configuration. 

Your browser likely sends the request with the `Host` header set to `localhost`. Requests with any other `Host` header will hit the "catch all" in second server block, returning a  HTTP 503.
