### ISSUE TITLE
Docker-gen on separate container doesn't read vhost.d files

### ISSUE THREAD

**Issue by marcossantiago** [jwilder/nginx-proxy#617]
Hi guys, 

I am running docker-gen in a separate container from nginx and I am also using the nginx to serve my static files. It works fine locally, but as soon as I deploy on my servers, it seems that it's not reading the content of /etc/nginx/vhost.d folder, so my static folder is not being added to default.conf.

This is my docker-compose file:

```
myapp:
    build: .
    restart: always
    volumes:
      - /usr/src/app/
    expose:
      - 8001
    links:
      - db
      - redis
    environment:
      - VIRTUAL_HOST=dev.myapp.com
    command: /usr/src/app/bin/run_gunicorn.sh

  nginx:
    build: ./docker/nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - /etc/nginx/conf.d/
    volumes_from:
      - myapp

  dockergen:
    image: jwilder/docker-gen
    command: -notify-sighup nginx -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes_from:
      - nginx
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /nginx/:/etc/docker-gen/templates/
```

This is my nginx dockerfile:

```
FROM nginx:1.11.5

COPY vhost.d/ /etc/nginx/vhost.d/
```

And this is the content of /etc/nginx/vhost.d/dev.myapp.com:

`location /static {
    alias /usr/src/app/static;
}
`

Can someone give me a hand on this ?

Thanks in advance.

**Comment by wader** [comment]
Hi, when you say it works locally do you mean the same docker-compose config works? does the generated config look ok (exec into the container and cat `/etc/nginx/conf.d/default.conf`)? see anything interesting in the logs? file permission problem etc?

**Comment by marcossantiago** [comment]
File permissions are the same on both. Locally I can see `include /etc/nginx/vhost.d/dev.myapp.com;` on default.conf. 
How can I check the logs on dockergen ? Coudn't find anything on nginx logs...

**Comment by marcossantiago** [comment]
Just a quick note that everything else seems to be working fine. 
If I run `docker-compose scale myapp=2`, the requests are distributed correctly...

**Comment by wader** [comment]
If you run `docker-compose logs` you should see logs from all service containers and if docker-gen is complaining on something.

You can also test run docker-gen yourself with something like `docker-compose exec dockergen docker-gen /etc/docker-gen/templates/nginx.tmpl`. Might help to figure out whats going on.

**Comment by marcossantiago** [comment]
Thanks @wader  !

I just figure this out. Just couldn't wrap my head around why it was working fine locally and not on the server.

Dockergen wasn't able to see the vhost.d folder, therefore not able read those files. I just had to adjust my docker-compose by adding `/etc/nginx/vhost.d/` to volumes.

```
  nginx:
    build: ./docker/nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - /etc/nginx/conf.d/
      - /etc/nginx/vhost.d/
    volumes_from:
      - myapp
```
