### ISSUE TITLE
Hostname was NOT found in DNS cache

### ISSUE THREAD

**Issue by lucasjahn** [jwilder/nginx-proxy#629]
Hey there,

I have a setup based on docker-letsencrypt-nginx-proxy-companion running a django container and a wordpress container on the same Docker Host. I have added to domains to each of the container, so the wordpress container is reachable with mydomain.com and www.mydomain.com and the django container with subdomain.mydomain.com. This is configured in the VIRTUAL_HOST env and its working perfectly so far. I get all certificates and I can connect to each of them.

The main Issue I have now is, that the wordpress container needs to curl the django container and vice versa. But if I go into the django or wordpress container and try to make a call to e.g. subdomain.mydomain.com I get the following error:

> Hostname was NOT found in DNS cache

and then he tries to connect to the IP and is ending up in a timeout. If I make a curl from local or a different server I get a 200 without any problems on each of those. I read sth about a DNS resolve issue but atm I couldn't find a solution. Do you have a clue what I could do in this case?

Thanks in advance!

My Containers:

**Nginx Proxy Compose**
```
version: "2"

services: 
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/www/certificates:/etc/nginx/certs:ro"
      - "/etc/nginx/vhost.d"
      - "/usr/share/nginx/html"
      - "/var/run/docker.sock:/tmp/docker.sock:ro"

  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-nginx-proxy-companion
    restart: always
    volumes_from:
      - nginx-proxy
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/var/www/certificates:/etc/nginx/certs:rw"

networks:
  default:
    external:
      name: proxy-network
```

**Wordpress Compose**
```
version: '2'

services:
  mariadb:
    build:
      context: .
      dockerfile: build/env/mysql/Dockerfile
    env_file: .env
    restart: "always"
    ports:
      - 3306:3306
    environment:
       MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
       MYSQL_DATABASE: ${MYSQL_DATABASE}
       MYSQL_USER: ${MYSQL_USER}
       MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
       - prod-database:/var/lib/mysql


  php:
    build:
      context: .
      dockerfile: build/env/php-fpm/Dockerfile
    env_file: .env
    restart: "always"
    volumes:
      - ${SRC_APP_PERSISTENT}:/var/www/html
    links:
      - mariadb:mysql


  web:
    build:
      context: .
      dockerfile: build/env/nginx/Dockerfile
    restart: "always"
    links:
      - php:fpm
    volumes_from:
      - php
    environment:
      - VIRTUAL_HOST=mydomain.com,www.mydomain.com
      - VIRTUAL_PORT=443
      - VIRTUAL_NETWORK=proxy-network
      - LETSENCRYPT_HOST=mydomain.com,www.mydomain.com
      - LETSENCRYPT_EMAIL=info@mydomain.com
    ports:
      - "80"

volumes:
  prod-database:
    driver: local


networks:
  default:
    external:
      name: proxy-network
```

**Django Compose**
```
version: '2'

volumes:
  postgres_data_dev: {}
  postgres_backup_dev: {}

services:
  postgres:
    build: ./compose/postgres
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - postgres_backup_dev:/backups
    environment:
      - POSTGRES_USER=dbuser

  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-dev
    env_file: .env
    command: /start-dev.sh
    depends_on:
      - postgres
    environment:
      - POSTGRES_USER=dbuser
      - USE_DOCKER=yes
      - VIRTUAL_HOST=subdomain.mydomain.com
      - VIRTUAL_PORT=443
      - VIRTUAL_NETWORK=proxy-network
      - LETSENCRYPT_HOST=subdomain.mydomain.com
      - LETSENCRYPT_EMAIL=info@mydomain.com
    volumes:
      - .:/app
    ports:
      - "8000"
    links:
      - postgres

      - mailhog


  pycharm:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-dev
    depends_on:
      - postgres
    environment:
      - POSTGRES_USER=dbuser
    volumes:
      - .:/app
    links:
      - postgres


  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"

networks:
  default:
    external:
      name: proxy-network
```
