### ISSUE TITLE
It is not possible to restart container using docker-compose cmd

### ISSUE THREAD

**Issue by karlosmid** [jwilder/nginx-proxy#630]
Hi!

Here is docker-compose.yml:
```
proxy:
  build: ./nginx
  ports:
    - "5443:8000"
  volumes:
    - "/sl-data/nginx_certs:/etc/nginx/certs"
    - "/var/run/docker.sock:/tmp/docker.sock"
  net: "host"
```

And dockerfile:
```
FROM jwilder/nginx-proxy:latest
RUN apt-get update && apt-get install -qy \
        nginx
COPY slweb_proxy.conf /etc/nginx/conf.d
# frontend
RUN mkdir -p /app/frontend
ADD dist /app/frontend/
RUN chmod -R 705 /app/frontend
# frontend sa
RUN mkdir -p /app/frontend_sa
ADD dist /app/frontend/_sa
RUN chmod -R 705 /app/frontend_sa
# tool
RUN mkdir -p /app/tool
ADD dist_tool /app/tool/
RUN chmod -R 705 /app/tool
```

When we do:

`docker-compose stop proxy`  
`docker-compose up -d proxy`  

We got following error:

`proxy_1  | nginx.1    | 2016/11/11 11:32:28 [emerg] 15#15: duplicate "log_format" name "vhost" in /etc/nginx/conf.d/slweb_proxy.conf:4`

We need to do following in order to restart nginx:

`docker-compose rm -f proxy`  
`docker-compose build proxy`  
`docker-compose up -d proxy`
