### ISSUE TITLE
Example on how handle https on the reverse proxy

### ISSUE THREAD

**Issue by ArielGueta** [jwilder/nginx-proxy#631]
I have two containers:
1. client - expose port 3000
2. api - expose port 8000

I need the nginx-proxy to handle the https ( including redirecting http to https ) and talk to the containers http.
When I am running my code using http this works fine but when I'm trying with https I'm getting 502.
Someone please can help with short example on how to get running with this? thanks.

**Comment by wader** [comment]
Hi, can you share your full docker/docker-compose configuration?

**Comment by ArielGueta** [comment]
```
version: '2'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /home/certs:/etc/nginx/certs
  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    environment: 
      - NODE_ENV=production
      - VIRTUAL_HOST=clientlocal.com
    restart: always
  api:
    build: 
      context: .
      dockerfile: api/Dockerfile
    environment: 
      - NODE_ENV=production
      - MONGO_URL=mongodb://mongo/db
      - VIRTUAL_HOST=apilocal.com
    depends_on:
      - mongo
    restart: always
  mongo:
    image: mongo:3.3
    ports:
      - "27017:27017"
    volumes: 
     - /db/data:/data/db
    restart: always
```
