### ISSUE TITLE
Subdomain only works through port

### ISSUE THREAD

**Issue by mplacona** [jwilder/nginx-proxy#632]
Been bashing my head for too long on this, so decided to see if I can get some help over here.

Have a really basic setup now with `nginx-proxy` and a subdomain called `loginapi`. Took me ages to get this going, but I can now browse to http://loginapi.mydomain.com:8080 and see my API. I would like it to be exposed on port 80 though, but no matter what i seem to do, I can't quite get the right combination to get it working like that, and all I always get on http://loginapi.mydomain.com is a 502.

My docker compose looks like this:

```
version: "2"

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    links:
      - androidloginapi
    volumes:
      - "/etc/nginx/vhost.d"
      - "/usr/share/nginx/html"
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
    environment:
      STATIC_HOST: mydomain.com,www.mydomain.com

  androidloginapi:
    container_name: androidloginapi
    image: mplacona/androidloginapi
    expose:
      - "8080"
    entrypoint:
      - dotnet
      - bin/Release/netcoreapp1.0/publish/LoginAPI.dll
    environment:
      - VIRTUAL_HOST=loginapi.mydomain.com
      - VIRTUAL_PORT=80
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - LTTNG_UST_REGISTER_TIMEOUT=0
      - DOTNET_SDK_VERSION=1.0.0-preview2-003131
      - DOTNET_SDK_DOWNLOAD_URL=https://dotnetcli.blob.core.windows.net/dotnet/preview/Binaries/1.0.0-preview2-003131/dotnet-dev-debian-x64.1.0.0-preview2-003131.tar.gz
      - NUGET_XMLDOC_MODE=skip
      - ASPNETCORE_URLS=http://*:5050
    ports:
      - 8080:5050/tcp
    tty: true
    working_dir: /app
```

I know one of you will probably look at this and tell me what's wrong, but I seem to have tried every single possible combination and can't seem to hit the sweet spot.

I think the problem could be that perhaps I'm not really understanding how `VIRTUAL_PORT` and `expose` are actually related. Seems like changing `VIRTUAL_PORT` never really makes any difference.

My default.conf looks like this:

```
# If we receive X-Forwarded-Proto, pass it through; otherwise, pass along the
# scheme used to connect to this server
map $http_x_forwarded_proto $proxy_x_forwarded_proto {
  default $http_x_forwarded_proto;
  ''      $scheme;
}
# If we receive Upgrade, set Connection to "upgrade"; otherwise, delete any
# Connection header that may have been passed to this server
map $http_upgrade $proxy_connection {
  default upgrade;
  '' close;
}
gzip_types text/plain text/css application/javascript application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript;
log_format vhost '$host $remote_addr - $remote_user [$time_local] '
                 '"$request" $status $body_bytes_sent '
                 '"$http_referer" "$http_user_agent"';
access_log off;
# HTTP 1.1 support
proxy_http_version 1.1;
proxy_buffering off;
proxy_set_header Host $http_host;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection $proxy_connection;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $proxy_x_forwarded_proto;
# Mitigate httpoxy attack (see README for details)
proxy_set_header Proxy "";
server {
	server_name _; # This is just an invalid value which will never trigger on a real hostname.
	listen 80;
	access_log /var/log/nginx/access.log vhost;
	return 503;
}
upstream loginapi.mydomain.com {
				## Can be connect with "default" network
		# androidloginapi
		server 172.18.0.2 down;
}
server {
	server_name loginapi.mydomain.com;
	listen 80 ;
	access_log /var/log/nginx/access.log vhost;
	location / {
		proxy_pass http://loginapi.mydomain.com;
	}
}
```

Thanks in advance

**Comment by wader** [comment]
Hi, yes exported ports `VIRTUAL_PORT` can be a bit confusing. nginx-proxy does not need proxied containers to publish ports at all as it will talk to them over the internal docker network. `VIRTUAL_PORT` is which exposed container port on the internal docker network it should proxy to and if the container only exposes one port you don't need to specify it.

So i would do these changes:
Remove `links:` for nginx-proxy as docker-compose v2 will create a common network anyway.
Remove  `ports:` and `expose:` for androidloginapi
Make sure the image mplacona/androidloginapi  has `EXPORT 5050` (is that the port it listens to?)
Remove `VIRTUAL_PORT=80` for androidloginapi or change it to `VIRTUAL_PORT=5050` 

I think `server 172.18.0.2 down;` is generated because the template see that port 80 is not exposed.

**Comment by mplacona** [comment]
Thank you so much @wader.Made the changes and as expected, when I try to hit my application on port 8080, I'm, no longer able. However, if I then try to hit it on port 80, I'm still getting a 502.

To answer your question, my application indeed listens to port 5050, and the dockerfile looks like this:

```
FROM microsoft/dotnet:latest
COPY . /app
WORKDIR /app
 
RUN ["dotnet", "restore"]
RUN ["dotnet", "build"]
 
EXPOSE 5050/tcp
ENV ASPNETCORE_URLS http://*:5050
 
ENTRYPOINT ["dotnet", "bin/Release/netcoreapp1.0/publish/LoginAPI.dll"]
```

My docker-compose now looks like this:

```
version: "2"

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/etc/nginx/vhost.d"
      - "/usr/share/nginx/html"
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
    environment:
      STATIC_HOST: mydomain.com,www.mydomain.com

  androidloginapi:
    container_name: androidloginapi
    image: mplacona/androidloginapi
    entrypoint:
      - dotnet
      - bin/Release/netcoreapp1.0/publish/LoginAPI.dll
    environment:
      - VIRTUAL_HOST=loginapi.mydomain.com
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - LTTNG_UST_REGISTER_TIMEOUT=0
      - DOTNET_SDK_VERSION=1.0.0-preview2-003131
      - DOTNET_SDK_DOWNLOAD_URL=https://dotnetcli.blob.core.windows.net/dotnet/preview/Binaries/1.0.0-preview2-003131/dotnet-dev-debian-x64.1.0.0-preview2-003131.tar.gz
      - NUGET_XMLDOC_MODE=skip
      - ASPNETCORE_URLS=http://*:5050
    tty: true
    working_dir: /app
```

My nginx file has also changed now.

```
server {
	server_name _; # This is just an invalid value which will never trigger on a real hostname.
	listen 80;
	access_log /var/log/nginx/access.log vhost;
	return 503;
}
upstream loginapi.androidsecurity.info {
				## Can be connect with "default" network
			# androidloginapi
			server 172.18.0.3:5000;
}
server {
	server_name loginapi.mydomain.com;
	listen 80 ;
	access_log /var/log/nginx/access.log vhost;
	location / {
		proxy_pass http://loginapi.mydomain.com;
	}
}
```

**Comment by wader** [comment]
Hmm it seems like it's trying to connect to port 5000 on the container. Did you publish or expose 5000 in the compose config or accidentally typed `VIRTUAL_PORT=5000` instead of `VIRTUAL_PORT=5050`?

**Comment by mplacona** [comment]
I think we're very close. I had change the image to use port 5050 instead of 5000, but I think the image I actually had on my VPS wasn't actually up-to-date. The clue was this:

![wrong port](https://d1ro8r1rbfn3jf.cloudfront.net/ms_64922/2bu0zMyBSB6P9y0ZJ2OiWlc6ZfBmr9/1.%2Bplacona%2540placona-ubuntu%253A%2B%257E%2B%2528ssh%2529%2B2016-11-17%2B20-04-54.png?Expires=1479499516&Signature=FizTCxt1hK8c~bL~zN66zYpMsfnWem0D4~KA2DmzB6v7Vd6mAt8UCjeyrhfATYNYjpWckWr4zyJ395QmZZAx0tlk38YjcPAvq4VJkkGJ2Ut0tNvI5h2CfNJoiZdMslr2rKhRvL~2UHyS0zHvAp-JhplxMRIqlEKhDEjkKtFhNoPAp50V6nk0XN2o3YHHjR~cnANpDxKvoS-e86s4486wQz-6s7Ba-pxmntCXxSnULp~5-LP9PYJ11lDl05sfe2ejv0t6MgCXgx6Ga~7ZVsuQip4MeMUdLWV7TYCo8WHRHmwxsp~hqmc350mDiut66o8m-dN8SODntfSWdTfBS-jGWw__&Key-Pair-Id=APKAJHEJJBIZWFB73RSA)

Looking at my nginx file, it now seems to get generated to point to port 5050, and my container also starts on that port.

```
upstream loginapi.mydomain.com {
				## Can be connect with "placona_default" network
			# androidloginapi
			server 172.18.0.2:5050;
}
server {
	server_name loginapi.mydomain.com;
	listen 80 ;
	access_log /var/log/nginx/access.log vhost;
	location / {
		proxy_pass http://loginapi.mydomain.com;
	}
}
```

Trouble is, I now seem to get a 504 (Timeout) on that URL.

Really appreciate your help @wader. Think we're really close now.

**Comment by wader** [comment]
Nice. What URL do you get timeout for? anything interesting in the nginx-proxt log? tip is to use `curl -v <URL>` to debug so you're not fooled by redirects etc.

**Comment by mplacona** [comment]
Not a lot in the logs... And `curl -v` also gives me a 504

This is what the logs look like:

```
nginx.1    | 2016/11/17 20:33:50 [error] 24#24: *1 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 81.105.13.001, server: loginapi.mydomain.com, request: "GET / HTTP/1.1", upstream: "http://172.18.0.2:5050/", host: "loginapi.mydomain.com"
nginx.1    | loginapi.mydomain.com 81.105.13.001 - - [17/Nov/2016:20:33:50 +0000] "GET / HTTP/1.1" 504 585 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.98 Safari/537.36"
nginx.1    | 2016/11/17 20:34:50 [error] 24#24: *1 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 81.105.13.001, server: loginapi.mydomain.com, request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.18.0.2:5050/favicon.ico", host: "loginapi.mydomain.com", referrer: "http://loginapi.mydomain.com/"
nginx.1    | loginapi.mydomain.com 81.105.13.001 - - [17/Nov/2016:20:34:50 +0000] "GET /favicon.ico HTTP/1.1" 504 585 "http://loginapi.mydomain.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.98 Safari/537.36"
```

**Comment by wader** [comment]
Weird. So i guess it's time for exec into the nginx-proxy container and have a look :) try something like this: 
```
$ docker exec -ti <nginx-proxy-container-id> bash
$ ping 172.18.0.2 # or whatever IP androidloginapi has
# you can also install curl with:
$ apt-get update && apt-get install curl
$ curl -v http://172.18.0.2:5050
```

But the `while reading response header from upstream` part is a bit suspicious, kind of hints that it might actually connects but get no data. Can you see any log for the androidloginapi container?

**Comment by mplacona** [comment]
Humm that's super weird. it seems like it can see and access my application from within the nginx-proxy.

```
root@636760573ec6:/app# curl -v http://172.18.0.2:5050
* Rebuilt URL to: http://172.18.0.2:5050/
* Hostname was NOT found in DNS cache
*   Trying 172.18.0.2...
* Connected to 172.18.0.2 (172.18.0.2) port 5050 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.38.0
> Host: 172.18.0.2:5050
> Accept: */*
>
< HTTP/1.1 200 OK
< Date: Thu, 17 Nov 2016 21:18:10 GMT
< Transfer-Encoding: chunked
< Content-Type: text/plain; charset=utf-8
* Server Kestrel is not blacklisted
< Server: Kestrel
<
* Connection #0 to host 172.18.0.2 left intact
You can read more about this project in https://github.com/mplacona/LoginAPI
```

It just doesn't resolve when I try to access it via the browser.

**Comment by wader** [comment]
The only thing i can think of it that nginx-proxy will add some additional headers to the request done to the container, see https://github.com/jwilder/nginx-proxy/blob/master/nginx.tmpl#L48. Maybe try to add `-H "Connection: close" -H "Host: loginapi.mydomain.com"` to the test curl command and see if it stops working? might give some clue.

**Comment by wader** [comment]
If you google for "kestrel nginx proxy no response" there seems to actually be some issues. One even is about `Connection: close` it seems.

**Comment by mplacona** [comment]
You're absolutely right @wader. Thought I'd take some time away from it and look at it with fresh eyes this morning. As you saw in this in https://github.com/jwilder/nginx-proxy/issues/632#issuecomment-261355396 I was already making silly mistakes.

Googling "kestrel nginx proxy no response" totally helped here as I ended up in this issue https://github.com/aspnet/KestrelHttpServer/issues/468 and towards the end of it, a lot of people say that adding 

`proxy_set_header Connection keep-alive;` helped them out. Like I said in the beginning, I'm new to all this, so working out how to create and add my own `proxy.conf` to my container took some research, but was obviously worth a shot. And guess what? It totally paid off!

I'll leave everything documented here in case it becomes useful to anyone in the future.

Here's how I changed my docker-compose.yml file:

```
version: "2"

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./proxy.conf:/etc/nginx/proxy.conf"
      - "/etc/nginx/vhost.d"
      - "/usr/share/nginx/html"
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
    environment:
      STATIC_HOST: mydomain.com,www.mydomain.com

  androidloginapi:
    container_name: androidloginapi
    image: mplacona/androidloginapi
    entrypoint:
      - dotnet
      - bin/Release/netcoreapp1.0/publish/LoginAPI.dll
    environment:
      - VIRTUAL_HOST=loginapi.mydomain.com
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - LTTNG_UST_REGISTER_TIMEOUT=0
      - DOTNET_SDK_VERSION=1.0.0-preview2-003131
      - DOTNET_SDK_DOWNLOAD_URL=https://dotnetcli.blob.core.windows.net/dotnet/preview/Binaries/1.0.0-preview2-003131/dotnet-dev-debian-x64.1.0.0-preview2-003131.tar.gz
      - NUGET_XMLDOC_MODE=skip
      - ASPNETCORE_URLS=http://*:5050
    tty: true
    working_dir: /app
```

And here's what my proxy.conf file looks like:

```
# HTTP 1.1 support
proxy_http_version      1.1;
proxy_set_header        Connection      keep-alive;
proxy_set_header        Host            $host;
proxy_redirect          off;
proxy_buffering         off;
proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $proxy_x_forwarded_proto;
proxy_set_header        X-Real-IP       $remote_addr;
proxy_set_header Upgrade $http_upgrade;

# Mitigate httpoxy attack (see README for details)
proxy_set_header Proxy "";
```

As you can see, I used all the recommendations @jwilder suggests here https://github.com/jwilder/nginx-proxy#custom-nginx-configuration, but added some extra goodies which made it work with Kestrel.

Thank you so much for your help here, I don't think I would have found the solution without all your knowledge.
