### ISSUE TITLE
SSL support with docker-compose

### ISSUE THREAD

**Issue by llaine** [jwilder/nginx-proxy#633]
Trying to get things running using https.

```yaml
version: '2'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "4444:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs

  db:
    image: library/mariadb
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - "3306:3306"

  redis:
     image: redis
     ports:
       - "6379"

  app:
    build: .
    container_name: my_name
    command: bundle exec foreman start
    environment:
      - PORT=3000
      - REDIS_URL=172.18.0.2
      - VIRTUAL_HOST=my_name.com
    ports:
      - "8080:3000"
    links:
      - db
      - redis
    volumes:
      - .:/myapp

```

 ```
curl -k -I -H "Host: my_name.com" localhost:443
curl: (52) Empty reply from server
```

Query on port 80 works fines.

Any idea why the SSL support doesn't work ?

**Comment by lucasjahn** [comment]
Because you set the outside port to 4444 in here:

```
nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "4444:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs
``` 

so this should work

```
curl -k -I -H "Host: my_name.com" localhost:4444
```
