### ISSUE TITLE
specify nginx-proxy in multiple docker-compose files

### ISSUE THREAD

**Issue by vekexasia** [jwilder/nginx-proxy#644]
Hello,

i'm unsure if this is the right place. please forgive me if it's not.

I've two different microservices that needs to be "proxied" by `nginx-proxy` hence i've wrote 2 different `docker-compose.yml` files, one for each microservice. ex:

```yaml
version: '2'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "3000:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  whoami:
    image: jwilder/whoami
    container_name: whoami
    environment:
      - VIRTUAL_HOST=whoami.local
```

&

```yaml
version: '2'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "3000:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  test-second:
    build: .
    container_name: test-second
    environment:
      - VIRTUAL_HOST=second.local
```

whenever i start the second by issuing `docker-compose up` I get the following error: 
```
ERROR: for nginx-proxy  Cannot create container for service nginx-proxy: Conflict. The name "/nginx-proxy" is already in use by container 69e073a6a9ed72282c020ee213eafc75f1fca85acb4d2f206290962e3c8d3464. You have to remove (or rename) that container to be able to reuse that name.
```

While this is completely expected I was wondering how should I specify a dependency on `nginx-proxy` without having `docker-compose` to argue about a "duplicated" service.

**Comment by wader** [comment]
Hi, usually you run just one nginx-proxy and the make sure nginx-proxy and all containers that should be proxied shares a common network.

**Comment by vekexasia** [comment]
@wader thanks. So basically I would've not to specify nginx-proxy in docker-compose right?

**Comment by wader** [comment]
@vekexasia Yepp. But then instead do something like:
```
version: '2'
services:
    ...
    networks:
     - nginx-proxy

networks:
  nginx-proxy:
    external:
      name: nginx-proxy
```

And run nginx-proxy separately somehow connected to the same network.

**Comment by vekexasia** [comment]
thank you :)

**Comment by sakoht** [comment]
This has saved me from a lot of head-banging.   Second time I did better scanning github issues than stackoverflow. Thanks!

**Comment by christhomas** [comment]
I have done this, but when I try to access one of the services, I get 503 connection refused

I can open a shell into nginx-proxy and try to ping the ip addresses and they are ok, I have inspected the network and I can see the containers I need to see on there, but whenever I try to wget, or curl, I get 503.

any ideas?

**Comment by jeeftor** [comment]
This is how i do things locally - i make sure all my compose stuff is running `network_mode: bridge`

```
version: "3"
services:
 # The Mongo DB Container is just a straight up container direclty pulled form Docker HUB
  # It is seeded by mongo_seed container
  mongo:
    container_name: frn-mongo
    image: mongo
    expose:
      - "27017"
    environment:
      - VIRTUAL_HOST=frn-db.dev
    network_mode: bridge # See note at top for details on bridge mod
    
```
