### ISSUE TITLE
Not getting a new project recognized by nginx-proxy

### ISSUE THREAD

**Issue by lhridley** [jwilder/nginx-proxy#665]
I'm working on a development to production automated workflow using Docker in a production environment, and nginx-proxy to manage proxy services for web projects deployed to a server.  I have a wildcard certificate configured on the production server.  I've got nginx and docker-gen running as separate docker containers, using the following `docker-compose.yml` file:

```
version: '2'
services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/nginx/conf.d
      - /usr/local/certs:/etc/nginx/certs

  dockergen:
    image: jwilder/docker-gen
    container_name:  dockergen
    command: -notify-sighup nginx -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes_from:
      - nginx
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /usr/local/nginx/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl
    depends_on:
      - nginx
```

Running `docker-compose up -d` gives me the following available networks:
```
NETWORK ID          NAME                 DRIVER              SCOPE
18981ed45012        bridge               bridge              local               
7568a47b8bcb        host                 host                local               
63e532271ee9        nginxproxy_default   bridge              local               
f173f50b1fc3        none                 null                local  
```
I'm deploying a new project to this same server, which is configured with the following docker-compose files, started by chaining them when running `docker-compose up -d`:
**`docker-compose.yml`**
```
version: '2'

services:

  drupal:
    build: ./docker/drupal
    volumes:
      - drupal-themes:/var/www/html/themes
      - default-files:/var/www/html/sites/default/files
      - private-files:/var/www/private
      - ./drupal:/tmp/drupal

  db:
    image: mariadb:10.1.20
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
      MYSQL_DATABASE: drupal
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
    driver: local
  drupal-themes:
    driver: local
  default-files:
    driver: local
  private-files:
    driver: local
```

**`docker-compose-prod.yml`**
```
version: '2'
services:
  drupal:
    environment:
      - VIRTUAL_HOST=testproj.atomicci.com
    networks:
      - default
      - nginx-proxy
networks:
  default:
  nginx-proxy:
    external:
      name: nginxproxy_default
```

I'm getting a 503 when I try to pull up the project at http://testproj.atomicci.com (I would expect this to redirect to https://testproj.atomicci.com).  When I pull up https://testproj.atomicci.com I get "connection refused".  I tested the setup with the following docker-compose file, so I know the certs are configured correctly, and I got the desired behavior, which was a redirect from http://whoami.atomicci.com to https://whoami.atomicci.com (note, this is no longer in place on the production server, it was for testing only):

```
version: '2'
services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - /etc/nginx/conf.d
      - /usr/local/certs:/etc/nginx/certs

  dockergen:
    image: jwilder/docker-gen
    command: -notify-sighup nginx -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes_from:
      - nginx
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /usr/local/nginx/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl

  whoami:
    image: jwilder/whoami
    environment:
      - VIRTUAL_HOST=whoami.atomicci.com
```

In looking at the default.conf file for the nginx container, there are no entries for the drupal service, so I've got something configured incorrectly, but I can't figure out what.  I tried the following in `docker-compose-prod.yml` as well, with similar results:

```
networks:
  default:
  nginx-proxy:
    external:
      name: bridge
```

I'm sure there's something subtle I've missed, but I can't figure out what that might be.  Any assistance would be greatly appreciated.

### Update:  
I specifically declared a network for the nginx container called `bridge` as follows:

```
networks:
  bridge:
    driver: bridge
```
and added the following to both the nginx and dockergen services:
```
    networks:
      - bridge
```

This resulted in the following networks:
```
NETWORK ID          NAME                DRIVER              SCOPE
18981ed45012        bridge              bridge              local               
7568a47b8bcb        host                host                local               
dba4f383fde1        nginxproxy_bridge   bridge              local               
f173f50b1fc3        none                null                local 
```

I then added the following network declarations to my project's `docker-compose-prod` file:
```
    networks:
      - nginx-proxy
...
networks:
  nginx-proxy:
    external:
      name: nginxproxy_bridge
```
Unfortunately I got the same behavior on the production server; however setting the same thing up locally (and adding the domain name entry into my /etc/hosts file) results in a working site, redirected to https, which is the behavior I would expect on my production server.

I'm using the same nginx.tmpl file on both local and production, and the same certificate files on both.  I checked the firewall settings for the production server and both ports 80 and 443 are exposed.  

Inspecting the networks for the drupal container on the production server reveals the following:
```
{
  "testme_default": {
    "IPAMConfig": null,
    "Links": null,
    "Aliases": [
      "drupal",
      "0f1e3558f8a3"
    ],
    "NetworkID": "53f8ebffb111eefef0f42596d8175f8ea4131c3d6e74e4ccef95bf3a2e95075c",
    "EndpointID": "9e8bf75339a5657b4f2d954c133b3b9c63ba684488f6c68f55a750a927198a01",
    "Gateway": "172.19.0.1",
    "IPAddress": "172.19.0.2",
    "IPPrefixLen": 16,
    "IPv6Gateway": "",
    "GlobalIPv6Address": "",
    "GlobalIPv6PrefixLen": 0,
    "MacAddress": "02:42:ac:13:00:02"
  }
}
```

On a local machine, I get the following networks:
```
{
  "drupaldocker_default": {
    "IPAMConfig": null,
    "Links": null,
    "Aliases": [
      "drupal",
      "40f172aeb2eb"
    ],
    "NetworkID": "acec9867ea4190b87834d6def7a99eb751600a5dbc2dbc3a881af673bfcb02e2",
    "EndpointID": "ac3abe420781507dc071e343fa1b7b5ffac2e2a762a12da226f366f6194e0467",
    "Gateway": "172.23.0.1",
    "IPAddress": "172.23.0.3",
    "IPPrefixLen": 16,
    "IPv6Gateway": "",
    "GlobalIPv6Address": "",
    "GlobalIPv6PrefixLen": 0,
    "MacAddress": "02:42:ac:17:00:03"
  },
  "nginxproxy_bridge": {
    "IPAMConfig": null,
    "Links": null,
    "Aliases": [
      "drupal",
      "40f172aeb2eb"
    ],
    "NetworkID": "3ef4570f086f7191f51bd9283e5dca60907f9811e144c707200f8e082b184fca",
    "EndpointID": "3e756f8f36d0c6e60d8e8c0c6597ad8b3761f73b2cfd7da86c96d00615e121d5",
    "Gateway": "172.24.0.1",
    "IPAddress": "172.24.0.4",
    "IPPrefixLen": 16,
    "IPv6Gateway": "",
    "GlobalIPv6Address": "",
    "GlobalIPv6PrefixLen": 0,
    "MacAddress": "02:42:ac:18:00:04"
  }
}
```
So, I'm not getting the nginxproxy_bridge on production, but I am getting it on a local setup.

I'm at a loss.  Any help would be appreciated.  I've tried restarting the nginx and dockergen services, and then starting the project stack to no avail.
