### ISSUE TITLE
Running on bridge multiple compose error

### ISSUE THREAD

**Issue by ale-batt** [jwilder/nginx-proxy#673]
I can't make it worked with using `nginx-proxy` in compose.

```
version: '2'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /home/al/nginx-proxy/503.html:/usr/share/nginx/html/503.html
      - /home/al/nginx-proxy/nginx.tmpl:/app/nginx.tmpl
    network_mode: "bridge" 
```
and for example `gogs/gogs`:
```
version: '2'
services:
  gogs:
    image: gogs/gogs
    ports:
      - "10080:3000"
      - "10022:22"
    environment:
      - VIRTUAL_HOST = "git.mywebsite.io,git.mywebsite.com"
      - VIRTUAL_PORT = 3000
    volumes:
      - "/home/al/gogs:/data"
    network_mode: "bridge"
```
when i check with `docker network inspect bridge` i see my 2 containers

```
[
    {
        "Name": "bridge",
        "Id": "b6c5166d0bc741827ed43813aca418170cf58190baca1ba61bb908c501eaeea9",
        "Scope": "local",
        "Driver": "bridge",
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.17.0.0/16",
                    "Gateway": "172.17.0.1"
                }
            ]
        },
        "Containers": {
            "8938372dddbd6f77eecb46714eb32d4eaa5d9fbd1a57b02b7df85e2288118260": {
                "Name": "gogs_gogs_1",
                "EndpointID": "72a0f97a89462202902bb7c483078df78d50e3b3f5d73da66b7b173f5be5898a",
                "MacAddress": "02:42:ac:11:00:03",
                "IPv4Address": "172.17.0.3/16",
                "IPv6Address": ""
            },
            "b0798eb6803c2b2ac3c707b905b7932553dd56c8f057130b8636d277a06c7154": {
                "Name": "nginx-proxy",
                "EndpointID": "7f8a7e97af03d2fba066de28ca8be2c9f37e47b8c410897d5ff2d586f0f3a0cd",
                "MacAddress": "02:42:ac:11:00:02",
                "IPv4Address": "172.17.0.2/16",
                "IPv6Address": ""
            }
        },
        "Options": {
            "com.docker.network.bridge.default_bridge": "true",
            "com.docker.network.bridge.enable_icc": "true",
            "com.docker.network.bridge.enable_ip_masquerade": "true",
            "com.docker.network.bridge.host_binding_ipv4": "0.0.0.0",
            "com.docker.network.bridge.name": "docker0",
            "com.docker.network.driver.mtu": "1500"
        }
    }
]
```
And it's worked well with multiple `docker run ...`  but my compose project not working ... 
Any idea ??
