### ISSUE TITLE
docker-compose proxy returning 503 for every request

### ISSUE THREAD

**Issue by jamesla** [jwilder/nginx-proxy#681]
Hi I have the following docker-compose.yml file

```
version: '2'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
  elasticsearch:
    build: elasticsearch/
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
    networks:
      - docker_elk
  logstash:
    build: logstash/
    command: -f /etc/logstash/conf.d/
    volumes:
      - ./logstash/config:/etc/logstash/conf.d
    ports:
      - "5000:5000"
    networks:
      - docker_elk
    depends_on:
      - elasticsearch
  kibana:
    build: kibana/
    volumes:
      - ./kibana/config/:/etc/kibana/
    ports:
      - "5601:5601"
    networks:
      - docker_elk
    depends_on:
      - elasticsearch
    environment:
      - VIRTUAL_HOST=kibana.local
      - VIRTUAL_PORT=5601
networks:
  docker_elk:
    driver: bridge
```

that produces the following nginx.confg

```
# HTTP 1.1 support
proxy_http_version 1.1;
proxy_buffering off;
proxy_set_header Host $http_host;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection $proxy_connection;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $proxy_x_forwarded_proto;
proxy_set_header X-Forwarded-Ssl $proxy_x_forwarded_ssl;
proxy_set_header X-Forwarded-Port $proxy_x_forwarded_port;
# Mitigate httpoxy attack (see README for details)
proxy_set_header Proxy "";
server {
        server_name _; # This is just an invalid value which will never trigger on a real hostname.
        listen 80;
        access_log /var/log/nginx/access.log vhost;
        return 503;
}
# kibana.local
upstream d8db1a3f45ad8b864545f522da2521974e07e8c9 {
}
server {
        server_name kibana.local;
        listen 80 ;
        access_log /var/log/nginx/access.log vhost;
        location / {
                proxy_pass http://d8db1a3f45ad8b864545f522da2521974e07e8c9;
        }
}
```

there is no problem with kibana as I can browse to it fine via localhost:5601.

both curl localhost and curl -H "Host: kibana.local" localhost result in a 503. 

Can anybody provide an advise on how can I troubleshoot this as it pretty much follows the example. I have tried this both on docker for mac and a docker installed on ubuntu. Help greatly appreciated.

PS I have noticed that the proxy_pass is missing a port number however if that was the problem I would imagine that would result in a 502 and quite a tricky one to test without making major changes to this container.
