### ISSUE TITLE
VIRTUAL_PORT doesnt work with php:5.6-apache without expose

### ISSUE THREAD

**Issue by Soivi** [jwilder/nginx-proxy#686]
Hi,

VIRTUAL_PORT doesn't seem to take effect on upstream port if you don't use expose. I tried to make demo where it is easy to confirm.

I have proxy running on 80 port and apache running on 8080. Virtual host is site1.soivi.net.

My files:
```
├── 000-default.conf
├── docker-compose.yaml
├── index.html
└── ports.conf
```

docker.compose.yaml
```
version: '2'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy:0.5.0
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  apachephp:
    image: php:5.6-apache
    volumes:
      - ./index.html:/var/www/html/index.html
      - ./000-default.conf:/etc/apache2/sites-available/000-default.conf:ro
      - ./ports.conf:/etc/apache2/ports.conf:ro
    environment:
      - VIRTUAL_HOST=site1.soivi.net
      - VIRTUAL_PORT=8080
```

000-default.conf
```
<VirtualHost *:8080>
	ServerAdmin webmaster@localhost
	DocumentRoot /var/www/html

	ErrorLog ${APACHE_LOG_DIR}/error.log
	CustomLog ${APACHE_LOG_DIR}/access.log combined

</VirtualHost>
```

ports.conf
`Listen 8080`

index.html
```
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Title of the document</title>
</head>

<body>
Content of the document......
</body>

</html>
```

/etc/hosts
`127.0.0.1 site1.soivi.net`

If I try to connect to site1.soivi.net I get this error:
`nginx-proxy    | nginx.1    | 2017/01/22 11:35:28 [error] 27#27: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: site1.soivi.net, request: "GET / HTTP/1.1", upstream: "http://172.22.0.3:80/", host: "site1.soivi.net"`

This is because In proxys default.conf upstream port doesn't update.
```
cat /etc/nginx/conf.d/default.conf 
   
..
upstream site1.soivi.net {
				## Can be connect with "dockertest_default" network
			# dockertest_apachephp_1
			server 172.22.0.3:80;
}
..
```

If I add expose: 8080 to docker-compose.yaml it works perfectly

docker.compose.yaml after fix:
```
version: '2'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy:0.5.0
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  apachephp:
    image: php:5.6-apache
    volumes:
      - ./index.html:/var/www/html/index.html
      - ./000-default.conf:/etc/apache2/sites-available/000-default.conf:ro
      - ./ports.conf:/etc/apache2/ports.conf:ro
    environment:
      - VIRTUAL_HOST=site1.soivi.net
      - VIRTUAL_PORT=8080
    expose:
      - "8080"
```

default.conf after fix:
```
cat /etc/nginx/conf.d/default.conf 
   
..
upstream site1.soivi.net {
				## Can be connect with "dockertest_default" network
			# dockertest_apachephp_1
			server 172.22.0.3:8080;
}
..
```

Why I need expose to get upstream to go right?
