### ISSUE TITLE
Location block not rewriting - Custom config

### ISSUE THREAD

**Issue by SeanSassenrath** [jwilder/nginx-proxy#689]
Having trouble executing a rewrite from the location block in my custom config. When I try to hit the route, I receive a blank page and a 304. 

I've checked `/etc/nginx/conf.d` to confirm that the copy of the custom config file to the container was successful. Would greatly appreciate any guidance! Thanks in advance!

**Custom image**

```
FROM jwilder/nginx-proxy

COPY ./my-proxy.conf /etc/nginx/conf.d/my-proxy.conf
```

**docker-compose.yml**
```
version: '2'

services:
  service:
    build: app-service
    environment:
      - VIRTUAL_HOST=my-domain.com
  nginx-proxy:
    build: custom-nginx-proxy
    container_name: nginx-proxy
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
```

**my-proxy.conf**
```
server {
  location /test {
    proxy_pass http://11.22.33.444/;
  }
}
```
