### ISSUE TITLE
AWS upstream sent too big header while reading response header from upstream

### ISSUE THREAD

**Issue by etiennemtl** [jwilder/nginx-proxy#694]
I'm currently using your wonderfull container in order to provide multiple containerize apps trough AWS ElasticBeanstalk multicontainer service. Everything is working perfectly, except that the authorization microservices of my app send big header (cookies) in order to allow single signon process resulting in a 502 Bad gateway error from nginx. Here is the corresponding `docker-compose.yml` file:

```
version: '2'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  triforce.web:
    image: triforce.web
    build:
      context: ./src/Triforce.Web
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "VIRTUAL_HOST=lvh.me,www.lvh.me"


  triforce.dashboard:
    image: triforce.dashboard
    build:
      context: ./src/Triforce.Dashboard
      dockerfile: Dockerfile
    volumes:
      - /var/triforce-dashboard-keys:/root/.aspnet/DataProtection-Keys
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - VIRTUAL_HOST=dashboard.lvh.me

  triforce.admin:
    image: triforce.admin
    build:
      context: ./src/Triforce.Admin
      dockerfile: Dockerfile
    volumes:
      - /var/triforce-admin-keys:/root/.aspnet/DataProtection-Keys
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - VIRTUAL_HOST=admin.lvh.me

  triforce.id:
    image: triforce.id
    build:
      context: ./src/Triforce.Id
      dockerfile: Dockerfile
    volumes:
      - /var/triforce-id-keys:/root/.aspnet/DataProtection-Keys
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - VIRTUAL_HOST=id.lvh.me
```

I tried to use custom configuration but without success, nginx could not redirect the host to the corresponding container. How could i change the buffer size?
