### ISSUE TITLE
Connection refused while connecting to upstream

### ISSUE THREAD

**Issue by Hermsi1337** [jwilder/nginx-proxy#700]
Hey Folks,

I'm a bit of a blockhead just now. Basically, I try to setup a nginx-container along with a bare php-fpm as application-container and server them threw the jwilder-proxy. I've set up a network for my nginx-jwilder-proxy and a network for my nginx+fpm-php container. But there is no way to get this thing work properly:
```
[error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: XXX.XX.X.X, server: application, request: "GET / HTTP/1.1", upstream: "fastcgi://XXX.XX.X.X:9000", host: "domain.tld"
```

It seems like it's not possible to connect to the application-container on port 9000. But a ping from webserver to application is possible without problems. And now the intereseting part: as soon as I remove the nginx-jwilder-proxy network from networks of my webserver everything works fine. So there is a networking issue I guess, but I have no idea where to locate the error. All ports are exposed correctly.

I hope that you guys can help me.

This is my docker-compose.yml:
```
version: '3'

volumes:
  invoice-db-data:
     driver: local-persist
     driver_opts:
       mountpoint: ${CONTAINERVOLUME}/var/lib/mysql
  invoice-app-data:
     driver: local-persist
     driver_opts:
       mountpoint: ${CONTAINERVOLUME}/var/www/app

services:
  database:
     image: mysql
     restart: unless-stopped
     volumes:
       - invoice-db-data:/var/lib/mysql
     environment:
       - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
       - MYSQL_DATABASE=${MYSQL_DATABASE}
       - MYSQL_USER=${MYSQL_USER}
       - MYSQL_PASSWORD=${MYSQL_PASSWORD}

  webserver:
    image: nginx
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - invoice-app-data:/var/www/app
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - VIRTUAL_PROTO=http
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    ports:
      - ${PROXYPORT}:80
    networks:
      - nginxproxy
      - default

  application:
    image: invoiceninja/invoiceninja
    restart: unless-stopped
    environment:
       - APP_DEBUG=1
       - APP_URL=http://${VIRTUAL_HOST}
       - DB_HOST=database
       - DB_DATABASE=${MYSQL_DATABASE}
       - DB_USERNAME=${MYSQL_USER}
       - DB_PASSWORD=${MYSQL_PASSWORD}
    depends_on:
      - database
      - webserver
    volumes:
      - invoice-app-data:/var/www/app

  cron:
    image: invoiceninja/invoiceninja
    restart: unless-stopped
    user: www-data
    environment:
       - APP_DEBUG=1
       - DB_HOST=database
       - DB_DATABASE=${MYSQL_DATABASE}
       - DB_USERNAME=${MYSQL_USER}
       - DB_PASSWORD=${MYSQL_PASSWORD}
    depends_on:
      - database
      - webserver
      - application
    entrypoint: |
      bash -c 'bash -s <<EOF
      trap "break;exit" SIGHUP SIGINT SIGTERM
      sleep 300s
      while /bin/true; do
        DB_USERNAME=${MYSQL_USER} DB_PASSWORD=${MYSQL_PASSWORD} /usr/local/bin/php /var/www/app/artisan ninja:send-invoices
        DB_USERNAME=${MYSQL_USER} DB_PASSWORD=${MYSQL_PASSWORD} /usr/local/bin/php /var/www/app/artisan ninja:send-reminders
        sleep 1d
      done
      EOF'

networks:
  nginxproxy:
    external:
      name: ${NGINXPROXYNETWORK}
```

My nginx.conf:
```
user www-data;

events {
  worker_connections 768;
}

http {
    upstream backend {
        server application:9000;
    }
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    gzip on;
    gzip_disable "msie6";

    server {
        listen      80 default;
        server_name application;

        root /var/www/app/public;

        index index.php;

        charset utf-8;

        location / {
            try_files $uri $uri/ /index.php?$query_string;
        }

        location = /favicon.ico { access_log off; log_not_found off; }
        location = /robots.txt  { access_log off; log_not_found off; }

        sendfile off;

        location ~ \.php$ {
            fastcgi_split_path_info ^(.+\.php)(/.+)$;
            fastcgi_pass backend;
            fastcgi_index index.php;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_intercept_errors off;
            fastcgi_buffer_size 16k;
            fastcgi_buffers 4 16k;
        }

        location ~ /\.ht {
            deny all;
        }
    }
}
```
