### ISSUE TITLE
Reverse Proxy not working

### ISSUE THREAD

**Issue by ctejada10** [jwilder/nginx-proxy#701]
After updating Docker, the reverse proxy does not forward the request to my other containers but to a "Welcome to NGINX" page.

No config was changed in the containers or the proxy.
![screen shot 2017-01-30 at 10 41 47 am](https://cloud.githubusercontent.com/assets/9596346/22429488/c9a9de42-e6d8-11e6-97cf-c625e56d7e8e.png)

**Comment by bjoernbusch** [comment]
Did you check the logs files of nginx-proxy?

`docker logs nginx-proxy`?

**Comment by ctejada10** [comment]
I did not.

Here's an example of the logs when I'm not accessing anything:

```
1/31/2017 11:12:55 AMforego     | starting nginx.1 on port 5000
1/31/2017 11:12:55 AMforego     | starting dockergen.1 on port 5100
1/31/2017 11:12:55 AMdockergen.1 | 2017/01/31 16:12:55 Generated '/etc/nginx/conf.d/default.conf' from 18 containers
1/31/2017 11:12:55 AMdockergen.1 | 2017/01/31 16:12:55 Running 'nginx -s reload'
1/31/2017 11:12:56 AMdockergen.1 | 2017/01/31 16:12:56 Error running notify command: nginx -s reload, exit status 1
1/31/2017 11:12:56 AMdockergen.1 | 2017/01/31 16:12:56 Watching docker events
1/31/2017 11:12:56 AMdockergen.1 | 2017/01/31 16:12:56 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification 'nginx -s reload'
```

And here's when I try to access a container:

```
1/31/2017 11:13:53 AMnginx.1    | 129.21.101.88 - - [31/Jan/2017:16:13:53 +0000] "GET / HTTP/1.1" 200 612 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/602.3.12 (KHTML, like Gecko) Version/10.0.2 Safari/602.3.12" "-"
1/31/2017 11:14:00 AMnginx.1    | 129.21.101.88 - - [31/Jan/2017:16:14:00 +0000] "GET / HTTP/1.1" 200 612 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/602.3.12 (KHTML, like Gecko) Version/10.0.2 Safari/602.3.12" "-"
```

**Comment by thomasleveil** [comment]
and what does the following command reports?

    docker exec nginx-proxy nginx -s reload

**Comment by ctejada10** [comment]
```
2017/01/31 17:00:54 [emerg] 35#35: host not found in upstream "down" in /etc/nginx/conf.d/default.conf:52
nginx: [emerg] host not found in upstream "down" in /etc/nginx/conf.d/default.conf:52
```

**Comment by thomasleveil** [comment]
This config file is generated everytime you stop or start a container with the `VIRTUAL_HOST` environment variable set.

**Comment by thomasleveil** [comment]
this file is generated everytime you start or stop a container having the `VIRTUAL_HOST` environment variable set

**Comment by ctejada10** [comment]
Oh, ok. 

However, all my hosts are up and running. They all have the `VIRTUAL_HOST` variable set since day one. Not sure what changed.

**Comment by thomasleveil** [comment]
Then run:

    docker exec nginx-proxy cat /etc/nginx/conf.d/default.conf

and look at line 52 to discover with which container/virtualhost that config fails.

**Comment by ctejada10** [comment]
So this is an example of one container: 

```
# www.urlofcontainer.com
upstream d3c0c69aebb8604b6f6b0b15adadb67ad8a6c15c {
## Can be connect with "none" network
# r-Plex-couchpotato-1-495820e9
  server  down;
}
server {
  server_name www.urlofcontainer.com;
  listen 80 ;
  access_log /var/log/nginx/access.log vhost;
  location / {
    proxy_pass http://d3c0c69aebb8604b6f6b0b15adadb67ad8a6c15c;
  }
}
```

I am not very experienced on NGINX configs, so not sure if there's anything wrong here.

**Comment by thomasleveil** [comment]
Are that container and the nginx container on different docker networks? If so, the nginx proxy container will not be able to forward trafic to that container.

**Comment by ctejada10** [comment]
They are on the same machine. So, yeah, they should be in the same network.

**Comment by thomasleveil** [comment]
not true, being on the same machine does not imply that they are on the same _docker network_

**Comment by ctejada10** [comment]
You're totally right. 

I'm managing my containers using Rancher, and they're all on the same stack. So they should be on the same _docker network_.

**Comment by thomasleveil** [comment]
it looks like a duplicate of #648

**Comment by ctejada10** [comment]
Looking into it now. Thanks!

**Comment by ctejada10** [comment]
So it looks like it's not resolved, then?

**Comment by ctejada10** [comment]
So, it looks like it's not resolved then?

**Comment by trentdavida** [comment]
I'miss having the same issue and I'm not in rancher. Straight docker compose.

**Comment by ctejada10** [comment]
Weird…

I guess I'll try to setup an NGINX server manually 😢

**Comment by trentdavida** [comment]
My Fault! I was mixing Wild cards and non wild cards and it was throwing up

**Comment by TheBlusky** [comment]
Same issue here.

**Comment by jaketame** [comment]
Same issue too but outside Rancher

**Comment by cweiske** [comment]
We experience the same issue. Our setup:

1. a project using `docker-compose` v3, defining a `VIRTUAL_HOST`. It has its own network, as docker-compose v3 automatically creates an application-specific network.
2. `nginx-proxy` running in its own application-specific docker network

When starting up `nginx-proxy`, it is not able to connect to the project container and creates empty `upstream $hostname {}` sections in `/etc/nginx/conf.d/default.conf`.

When starting up nginx-proxy with `--network $project_default`, it works fine because `nginx-proxy` is instantly able to connect to the container.

So the issue is in my eyes that an invalid config file is created when `nginx-proxy` is not able to access the containers, and that there is no auto config change when `nginx-proxy` is added to another network.

**Comment by eltiare** [comment]
@henryjcee Are you saying that nginx-proxy needs to start AFTER every other app servers start? That seems to be crazy.

**Comment by eltiare** [comment]
I fixed this by removing all `depends_on` either with the proxy or the running apps, oddly enough. Can't figure that out for the life of me.

**Comment by tiagoad** [comment]
Would be cool to only add containers to the nginx config after being up for a few seconds, maybe user-defined in something like VIRTUAL_WAIT. This way a rogue container in a reboot loop won't DOS the whole thing.

**Comment by GreatFireWall** [comment]
Same problem, Docker for Windows Linux Container. Anybody can help me?

`docker-compose.exe logs -f`:

![image](https://user-images.githubusercontent.com/4510984/55085150-1fa0b400-50e1-11e9-883d-1efb7382bab4.png)


`docker-compose.yml`:
```yaml
version: "3.7"

services:
  db:
    image: mysql
    container_name: mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - ./mysql:/var/lib/mysql

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db

  wordpress:
    image: wordpress
    container_name: wordpress
    restart: always
    #ports:
    #  - 80:80
    #  - 443:443
    environment:
      VIRTUAL_HOST: localhost
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: 123456
      WORDPRESS_DB_NAME: wordpress
      HTTP_PROXY: http://10.0.75.1:1235
      HTTPS_PROXY: http://10.0.75.1:1235
    volumes:
      - ./wordpress:/var/www/html
    depends_on:
      - db
  
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs
    depends_on: 
      - wordpress
```


`certs`:
![image](https://user-images.githubusercontent.com/4510984/55084872-a1441200-50e0-11e9-874f-ef3ad70d94ba.png)


`docker exec nginx-proxy cat /etc/nginx/conf.d/default.conf`:
```config
# If we receive X-Forwarded-Proto, pass it through; otherwise, pass along the
# scheme used to connect to this server
map $http_x_forwarded_proto $proxy_x_forwarded_proto {
  default $http_x_forwarded_proto;
  ''      $scheme;
}
# If we receive X-Forwarded-Port, pass it through; otherwise, pass along the
# server port the client connected to
map $http_x_forwarded_port $proxy_x_forwarded_port {
  default $http_x_forwarded_port;
  ''      $server_port;
}
# If we receive Upgrade, set Connection to "upgrade"; otherwise, delete any
# Connection header that may have been passed to this server
map $http_upgrade $proxy_connection {
  default upgrade;
  '' close;
}
# Apply fix for very long server names
server_names_hash_bucket_size 128;
# Default dhparam
ssl_dhparam /etc/nginx/dhparam/dhparam.pem;
# Set appropriate X-Forwarded-Ssl header
map $scheme $proxy_x_forwarded_ssl {
  default off;
  https on;
}
gzip_types text/plain text/css application/javascript application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript;
log_format vhost '$host $remote_addr - $remote_user [$time_local] '
                 '"$request" $status $body_bytes_sent '
                 '"$http_referer" "$http_user_agent"';
access_log off;
resolver 127.0.0.11;
# HTTP 1.1 support
proxy_http_version 1.1;
proxy_buffering off;
proxy_set_header Host $http_host;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection $proxy_connection;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $proxy_x_forwarded_proto;
proxy_set_header X-Forwarded-Ssl $proxy_x_forwarded_ssl;
proxy_set_header X-Forwarded-Port $proxy_x_forwarded_port;
# Mitigate httpoxy attack (see README for details)
proxy_set_header Proxy "";
server {
        server_name _; # This is just an invalid value which will never trigger on a real hostname.
        listen 80;
        access_log /var/log/nginx/access.log vhost;
        return 503;
}
# localhost
upstream localhost {
                                ## Can be connected with "wordpress-ecommerce_default" network
                        # wordpress
                        server 172.23.0.3:80;
}
server {
        server_name localhost;
        listen 80 ;
        access_log /var/log/nginx/access.log vhost;
        return 301 https://$host$request_uri;
}
server {
        server_name localhost;
        listen 443 ssl http2 ;
        access_log /var/log/nginx/access.log vhost;
        ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;
        ssl_ciphers 'ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:!DSS';
        ssl_prefer_server_ciphers on;
        ssl_session_timeout 5m;
        ssl_session_cache shared:SSL:50m;
        ssl_session_tickets off;
        ssl_certificate /etc/nginx/certs/localhost.crt;
        ssl_certificate_key /etc/nginx/certs/localhost.key;
        add_header Strict-Transport-Security "max-age=31536000" always;
        location / {
                proxy_pass http://localhost;
        }
}
```
