### ISSUE TITLE
Config in separate docker-compose.yml

### ISSUE THREAD

**Issue by marucjmar** [jwilder/nginx-proxy#714]
Hi, 

when run docker-compose.prod.yml with this config, site work
```
 services:
  db:
   volumes:
     ....
   environment:
     MYSQL_ROOT_PASSWORD: ...
     MYSQL_DATABASE: ...
     MYSQL_USER: ...
     MYSQL_PASSWORD: ...

  wordpress:
    volumes:
      -  ....
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_PASSWORD: ....
      VIRTUAL_HOST: fooo.com
      VIRTUAL_PORT: 80
  nginx-proxy:
    restart: always
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
```

But when my docker-compose.prod.yml separate to two file:

/docker-compose.prod.yml
```
version: '2'

services:
  db:
   volumes:
     ....
   environment:
     MYSQL_ROOT_PASSWORD: ...
     MYSQL_DATABASE: ...
     MYSQL_USER: ...
     MYSQL_PASSWORD: ...

  wordpress:
    volumes:
      -  ....
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_PASSWORD: ....
      VIRTUAL_HOST: fooo.com
      VIRTUAL_PORT: 80
```

and

/nginx/docker-compose.yml
```
version: '2'
services:
  nginx-proxy:
    restart: always
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
```

Site not work and display default nginx page, or 503

.conf like this
```
upstream 2075d816b463193acbe6d624b2e2c651933d4299 {
}
server {
	server_name fooo.com;
	listen 80 ;
	access_log /var/log/nginx/access.log vhost;
	location / {
		proxy_pass http://2075d816b463193acbe6d624b2e2c651933d4299;
	}
}
```

Could help me?

Command to run my compose
```
docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d
```

**Comment by phelpsiv** [comment]
Are the containers on the same docker network?

**Comment by marucjmar** [comment]
@phelpsiv thanks, I solve this problem add this config:

docker-compose.prod.yml
```
version: '2'

services:
  db:
   volumes:
     ....
   environment:
     MYSQL_ROOT_PASSWORD: ...
     MYSQL_DATABASE: ...
     MYSQL_USER: ...
     MYSQL_PASSWORD: ...

  wordpress:
    volumes:
      -  ....
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_PASSWORD: ....
      VIRTUAL_HOST: fooo.com
      VIRTUAL_PORT: 80
    networks:
      - default
      - nginx_default

networks:
  nginx_default:
    external:
      name: nginx_default
```
Nice!  #Close!
