### ISSUE TITLE
Can't set up nginx-proxy and wordpress container

### ISSUE THREAD

**Issue by murbanowicz** [jwilder/nginx-proxy#721]
Hi Gents,
I spent like 2 hrs trying to sort it out by myself but I can't find the way.

I am using docker-compose for nginx-proxy and letsencrypt companion together.

This is my `docker-compose.yml` for them:
```                                                                                                   
version: '2'                                                                                                             
                                                                                                                         
services:                                                                                                                
  nginx-proxy:                                                                                                           
    restart: always                                                                                                      
    image: jwilder/nginx-proxy                                                                                           
    container_name: proxy_nginx-proxy                                                                                    
    ports:                                                                                                               
      - 80:80                                                                                                            
      - 443:443                                                                                                          
    networks:                                                                                                            
      - nginxproxy                                                                                                       
    volumes:                                                                                                             
      - /var/run/docker.sock:/tmp/docker.sock:ro                                                                         
      - /etc/nginx/vhost.d                                                                                               
      - /usr/share/nginx/html                                                                                            
      - /data/letsencrypt-nginx-proxy-companion/certs/:/etc/nginx/certs:ro                                               
                                                                                                                         
  letsencrypt-nginx-proxy-companion:                                                                                     
networks:
      - nginxproxy                                                                                                       
    restart: always                                                                                                      
    image: jrcs/letsencrypt-nginx-proxy-companion                                                                        
    container_name: proxy_letsencrypt-nginx-proxy-companion                                                              
    volumes_from:                                                                                                        
      - nginx-proxy                                                                                                      
    volumes:                                                                                                             
      - /var/run/docker.sock:/var/run/docker.sock:ro                                                                     
      - /data/letsencrypt-nginx-proxy-companion/certs/:/etc/nginx/certs:rw           

networks:                                                                                                                
  nginxproxy:                                                                                                            
    external:                                                                                                            
      name: nginxproxy     
```

Not sure if it is working really correctly as calling my VPS IP giving nginx 503 error.

Going further I have my wordpress container.
```
sion: '2'                                                                                                             
                                                                                                                         
services:                                                                                                                
  db:                                                                                                                    
    image: mysql:8                                                                                                       
    volumes:                                                                                                             
      - /var/docker-images/neopolis/mysql:/var/lib/mysql                                                                 
    restart: always                                                                                                      
    environment:                                                                                                         
      MYSQL_ROOT_PASSWORD: pass                                                                              
      MYSQL_DATABASE: wp_neopolis                                                                                        
      MYSQL_USER: neopolis                                                                                               
      MYSQL_PASSWORD: pass                                                                                  
                                                                                                                         
  wordpress:                                                                                                             
    depends_on:                                                                                                          
      - db                                                                                                               
    image: wordpress:latest                                                                                              
    hostname: mydomain.com 
networks:                                                                                                            
      - nginxproxy                                                                                                       
    links:                                                                                                               
       - db                                                                                                              
    expose:                                                                                                              
      - "80"                                                                                                             
    ports:                                                                                                               
      - "127.0.0.1:8080:80"                                                                                              
    restart: always                                                                                                      
    environment:                    
    VIRTUAL_HOST: mydomain.com                                                                                          
      WORDPRESS_DB_NAME: wp_neopolis                                                                                     
      WORDPRESS_DB_HOST: db:3306                                                                                         
      WORDPRESS_DB_PASSWORD: pass                                                                            
    volumes:                                                                                                             
      - /var/www/neopolis:/var/www/html/                                                                                 
                                                                                                                         
networks:                                                                                                                
  nginxproxy:                                                                                                            
    external:              
     name: nginxproxy  
```

When I check nginx conf in nginx-proxy container, I see upstream but port never changes no matter what I put in expose or porst. I was trying many different combinations, always getting error (connection refused, not nginx page).

It redirects from http to https so something is happening but nothing correct...

**Comment by murbanowicz** [comment]
UPDATE:

I did manage to get it partially working by changing ports/expose part of wordpress container:
```
wordpress: 
    depends_on: 
      - db 
    image: wordpress:latest 
    hostname: mydomain
    networks:
      - nginxproxy
    expose:
      - '8081'
    ports:
      - '8081:8081'
    links:
      - db:mysql
    restart: always 
    environment: 
      VIRTUAL_HOST: mydomain.com
      WORDPRESS_DB_NAME: wp_neopolis 
      PORT: 8081
      WORDPRESS_DB_PASSWORD: m3P5-AuYSUcr%u[Y 
    volumes: 
      - /var/www/neopolis:/var/www/html/ 
```

**It is working fine on HTTP port 80, but not working on port 443 to get HTTPS.**
