### ISSUE TITLE
It does not work and there is nothing in the logs

### ISSUE THREAD

**Issue by ioganegambaputifonguser** [jwilder/nginx-proxy#742]
Hello guys! Example with whoami works for me. But when I try with my api service, I get

```
$ curl -H "Host: api.local" localhost
curl: (52) Empty reply from server

```
If I do same with my api service through the browser directly, http://x.x.x.x:8000 works fine, but http://x.x.x.x gives me "refused to connect". 

Probably something stupid, but I can not find error. Maybe someone can help me. There are my files

My docker-compose.yml

```
version: '2'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:8000"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
  whoami:
    image: jwilder/whoami
    container_name: whoami
    environment:
      - VIRTUAL_HOST=whoami.local
  db:
    image: postgres
    volumes:
      - moderator-db:/var/lib/postgresql/data
  redis:
    image: redis
  rabbitmq:
    image: rabbitmq:3.6
  api:
    build: .
    mem_limit: 1000m
    container_name: api
    command: /usr/bin/supervisord
    environment:
      - VIRTUAL_HOST=api.local
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db
      - rabbitmq
volumes:
  moderator-redis:
    driver: local
  moderator-db:
    driver: local
```

My Dockerfile

```
FROM ubuntu:latest
RUN locale-gen en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LC_ALL en_US.UTF-8

RUN apt-get update && \
    apt-get -y -qq install python3 python3-pip git libpq-dev nginx gunicorn supervisor
RUN useradd --shell /bin/bash -u 1024 -o -c "" -m myuser
RUN mkdir -p /code

# Setup supervisord
RUN mkdir -p /code/log/supervisor
RUN mkdir -p /code/run
COPY deploy/supervisord.conf /etc/supervisor/supervisord.conf

# Setup nginx
RUN rm /etc/nginx/sites-enabled/default
RUN rm /etc/nginx/nginx.conf
COPY deploy/nginx.conf /etc/nginx/
COPY deploy/flask.conf /etc/nginx/sites-available/
RUN ln -s /etc/nginx/sites-available/flask.conf /etc/nginx/sites-enabled/flask.conf
RUN chown myuser /var/lib/nginx -R
RUN chown myuser /var/log/nginx -R

WORKDIR /code
RUN chown myuser /code -R

ADD python_modules /code
RUN pip3 install -r python_modules

RUN pip3 install setuptools -U
ADD . /code/
USER myuser

```

In the api service launched nginx who listens to port 8000 and makes proxy_pass in the Flask application.

Autogenerated file with nginx-proxy

```
server {
	server_name api.local;
	listen 80 ;
	access_log /var/log/nginx/access.log vhost;
	location / {
		proxy_pass http://api.local;
	}
}
# whoami.local
upstream whoami.local {
				## Can be connect with "moderator_default" network
			# whoami
			server 172.19.0.2:8000;
}
```
