### ISSUE TITLE
503 Service temporary unavailable

### ISSUE THREAD

**Issue by Ekzer** [jwilder/nginx-proxy#748]
Hi,
I tried to follow exactly your tutorial to run nginx-proxy then add a docker-node instance, but it always returns 503.
What am I doing wrong please ?
Here is the docker-compose.yml : 

```
version: '2'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
  test-node:
    image: ucraft/test-node
    container_name : test-node
    environment:
      - VIRTUAL_HOST=test.node.fr

```

The dockerfile of ucraft/test-node : 

```
FROM node

## Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

## Install app dependencies
COPY package.json /usr/src/app/
RUN npm install

## Bundle app source
COPY . /usr/src/app

EXPOSE 8080
CMD [ "npm", "start" ]

```

And here are the logs from docker-compose up : 

> docker-compose up
Starting nginx-proxy
Starting test-node
Attaching to test-node, nginx-proxy
nginx-proxy    | forego     | starting dockergen.1 on port 5000
nginx-proxy    | forego     | starting nginx.1 on port 5100
nginx-proxy    | dockergen.1 | 2017/02/27 11:00:08 Generated '/etc/nginx/conf.d/default.conf' from 2 containers
nginx-proxy    | dockergen.1 | 2017/02/27 11:00:08 Watching docker events
nginx-proxy    | dockergen.1 | 2017/02/27 11:00:08 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification 'nginx -s reload'
test-node      | npm info it worked if it ends with ok
test-node      | npm info using npm@4.1.2
test-node      | npm info using node@v7.6.0
test-node      | npm info lifecycle docker_web_app@1.0.0~prestart: docker_web_app@1.0.0
test-node      | npm info lifecycle docker_web_app@1.0.0~start: docker_web_app@1.0.0
test-node      |
test-node      | > docker_web_app@1.0.0 start /usr/src/app
test-node      | > node server.js
test-node      |
test-node      | Running on http://localhost:8080
nginx-proxy    | nginx.1    | localhost 172.18.0.1 - - [27/Feb/2017:11:00:14 +0000] "GET / HTTP/1.1" 503 616 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36"

And here is the deault.conf generated : 
```
 server {
	server_name _; # This is just an invalid value which will never trigger on a real hostname.
	listen 80;
	access_log /var/log/nginx/access.log vhost;
	return 503;
}
# test.node.fr
upstream test.node.fr {
				## Can be connect with "ucraft_default" network
			# test-node
			server 172.18.0.2:8080;
}
server {
	server_name test.node.fr;
	listen 80 ;
	access_log /var/log/nginx/access.log vhost;
	location / {
		proxy_pass http://test.node.fr;
	}
}
```

Thank you in advance for any help.
