### ISSUE TITLE
503 Service Temporarily Unavailable

### ISSUE THREAD

**Issue by ioganegambaputifonguser** [jwilder/nginx-proxy#749]
docker-compose.yml

```
version: '2'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
  db:
    image: postgres
    volumes:
      - moderator-db:/var/lib/postgresql/data
  redis:
    image: redis
  rabbitmq:
    image: rabbitmq:3.6
  api:
    build: .
    mem_limit: 1000m
    container_name: api
    command: python3 manage.py gunicorn
    environment:
      - SIMPLE_SETTINGS=app.config,instance.docker
      - VIRTUAL_HOST=api.local
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    depends_on:
      - redis
      - db
      - rabbitmq
  task-queue:
    build: .
    command: python3 manage.py watch_task_queue
    environment:
      - SIMPLE_SETTINGS=app.config,instance.docker
    depends_on:
      - redis
      - db
      - rabbitmq
volumes:
  moderator-redis:
    driver: local
  moderator-db:
    driver: local
```

Docker

```
FROM ubuntu:latest
RUN locale-gen en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LC_ALL en_US.UTF-8

RUN apt-get update && \
    apt-get -y -qq install python3 python3-pip git libpq-dev gunicorn
RUN useradd --shell /bin/bash -u 1024 -o -c "" -m myuser
RUN mkdir -p /code

WORKDIR /code
RUN chown myuser /code -R

ADD python_modules /code
RUN pip3 install -r python_modules

RUN pip3 install setuptools -U
ADD . /code/

ENV PORT 8000
EXPOSE 8000

USER myuser
```

/etc/nginx/conf.d/default.conf

```
upstream api.local {
				## Can be connect with "moderator_default" network
			# api
			server 172.19.0.7:8000;
}
server {
	server_name api.local;
	listen 80 ;
	access_log /var/log/nginx/access.log vhost;
	location / {
		proxy_pass http://api.local;
	}
}
```

$docker ps

```
CONTAINER ID        IMAGE                  COMMAND                  CREATED             STATUS              PORTS                                NAMES
7059c1918462        moderator_api          "python3 manage.py..."   4 minutes ago       Up 3 minutes        0.0.0.0:8000->8000/tcp               api
c7e579e2f9f8        moderator_task-queue   "python3 manage.py..."   7 minutes ago       Up 3 minutes        8000/tcp                             moderator_task-queue_1
191e08e66a57        rabbitmq:3.6           "docker-entrypoint..."   7 minutes ago       Up 4 minutes        4369/tcp, 5671-5672/tcp, 25672/tcp   moderator_rabbitmq_1
7369d18d5e0b        redis                  "docker-entrypoint..."   7 minutes ago       Up 4 minutes        6379/tcp                             moderator_redis_1
0f524906ad70        jwilder/nginx-proxy    "/app/docker-entry..."   7 minutes ago       Up 3 minutes        0.0.0.0:80->80/tcp, 443/tcp          nginx-proxy
819570cb2e43        postgres               "docker-entrypoint..."   7 minutes ago       Up 4 minutes        5432/tcp                             moderator_db_1

```

I get 503 and that is curl output

```
 curl -H "Host: api.local" localhost
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>404 Not Found</title>
<h1>Not Found</h1>
<p>The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.</p>
```

where is my mistake? (

**Comment by codepython** [comment]
Have you checked  the api.local service has been  running well?

**Comment by GangsterHyj** [comment]
I am also confused with the 503 situation. 
Here's my docker-compose file. 
```yml
version: '3'
services:
    db:
        image: mysql:latest
        environment: 
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            MYSQL_DATABASE: coupons
        volumes:
            - "./db:/docker-entrypoint-initdb.d"
    tomcat_node_1_1:
        image: tomcat:latest
        environment: 
            VIRTUAL_HOST: tomcat_node_1.com
            VIRTUAL_PORT: 8080
            JDBC_USER: root
            JDBC_PASS: root
            JDBC_URL: jdbc:mysql://db:3306/coupons?useSSL=false
        volumes: 
            - "./tomcat/webapps:/usr/local/tomcat/webapps"
        links: 
            - db
            - redis
        depends_on: 
            - db
            - redis
    tomcat_node_1_2:
        image: tomcat:latest
        environment: 
            VIRTUAL_HOST: tomcat_node_1.com
            VIRTUAL_PORT: 8080
            JDBC_USER: root
            JDBC_PASS: root
            JDBC_URL: jdbc:mysql://db:3306/coupons?useSSL=false
        volumes: 
            - "./tomcat/webapps:/usr/local/tomcat/webapps"
        links: 
            - db
            - redis
        depends_on: 
            - db
            - redis            
    tomcat_node_2_1:
        image: tomcat:latest
        environment: 
            VIRTUAL_HOST: tomcat_node_2.com
            VIRTUAL_PORT: 8080
            JDBC_USER: root
            JDBC_PASS: root
            JDBC_URL: jdbc:mysql://db:3306/coupons?useSSL=false
        volumes: 
            - "./tomcat/webapps:/usr/local/tomcat/webapps"
        links: 
            - db
            - redis
        depends_on: 
            - db
            - redis
    tomcat_node_2_2:
        image: tomcat:latest
        environment: 
            VIRTUAL_HOST: tomcat_node_2.com
            VIRTUAL_PORT: 8080
            JDBC_USER: root
            JDBC_PASS: root
            JDBC_URL: jdbc:mysql://db:3306/coupons?useSSL=false
        volumes: 
            - "./tomcat/webapps:/usr/local/tomcat/webapps"
        links: 
            - db
            - redis
        depends_on: 
            - db
            - redis            
    redis:
        image: redis
        ports: 
            - "6389:6379"
    nginx:
        image: jwilder/nginx-proxy:latest
        container_name: nginx-proxy
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
        ports:
            - "8989:80"
        depends_on: 
            - tomcat_node_1_1
            - tomcat_node_1_2
            - tomcat_node_2_1
            - tomcat_node_2_2
        links:
            - tomcat_node_1_1
            - tomcat_node_1_2
            - tomcat_node_2_1
            - tomcat_node_2_2
networks:
  default:
    external:
      name: nginx-proxy
```
Here's the directory which the docker-compose.yml is in.
![image](https://cloud.githubusercontent.com/assets/7380114/23748528/f4aff736-04fe-11e7-9c22-8075adc1621a.png)
Here's the running result:
![image](https://cloud.githubusercontent.com/assets/7380114/23748570/1c791360-04ff-11e7-954f-52ef905f16d4.png)
![image](https://cloud.githubusercontent.com/assets/7380114/23748598/46e6fd4c-04ff-11e7-893c-a962314e7bd8.png)
![image](https://cloud.githubusercontent.com/assets/7380114/23748630/6870c9b6-04ff-11e7-8c20-66a2a5412eeb.png)

Here's the generated config file.
![image](https://cloud.githubusercontent.com/assets/7380114/23748762/ee2c580e-04ff-11e7-9a2b-7dd8d8b49e36.png)
![image](https://cloud.githubusercontent.com/assets/7380114/23748782/fe2ad668-04ff-11e7-9f37-855151d2039a.png)
I don't know why I get 503 when I access localhost:8989...
