### ISSUE TITLE
Assigning containers to different proxy instances

### ISSUE THREAD

**Issue by colinodell** [jwilder/nginx-proxy#751]
I have Docker running on a server with two network interfaces - one has a private IP (internal network) and the other is public (web-accessible).  I'd like the ability to spin up two instances of `nginx-proxy`, one bound to each interface, and then make containers available either privately or publically via one of the two proxies.

Is this currently possible?

If not, could we implement something where each `nginx-proxy` instance can be configured to only handle a certain "group" of containers?  For example:

```
version: '2'
services:
  public-proxy:
    image: jwilder/nginx-proxy
    container_name: public-proxy
    ports:
      - "12.34.56.78:80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      - VIRTUAL_GROUP=public

  public-whoami:
    image: jwilder/whoami
    container_name: public-whoami
    environment:
      - VIRTUAL_HOST=whoami.com
      - VIRTUAL_GROUP=public

  private-proxy:
    image: jwilder/nginx-proxy
    container_name: private-proxy
    ports:
      - "10.11.12.13:80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      - VIRTUAL_GROUP=private

  private-whoami:
    image: jwilder/whoami
    container_name: private-whoami
    environment:
      - VIRTUAL_HOST=whoami.local
      - VIRTUAL_GROUP=private
```

In the `nginx.tmpl` template, we'd check whether the current proxy container has a `VIRTUAL_GROUP` set - if so, we only generate configurations for other containers which also have that same `VIRTUAL_GROUP` value.

If the proxy container does not have a `VIRTUAL_GROUP` set, it would generate configurations for other containers which also lack a `VIRTUAL_GROUP` (thus preserving the current behavior).

Does this idea make sense?

(I'd offer to create the PR, but I've never worked with this templating syntax before, so I'm not confident I'd get it right)
