### ISSUE TITLE
Add option to activate /nginx_status

### ISSUE THREAD

**Issue by TigPT** [jwilder/nginx-proxy#762]
I think it would be interesting to add the option to activate /nginx_status

I was trying to do my implementation for myself and to pull a request but I was not able to do it successfully. Have anyone done it? Help please.

I was doing a .conf file to add to dock-composer as a volume
`- /my_proxy.conf:/etc/nginx/conf.d/my_proxy.conf:ro`

`server {
    listen 127.0.0.1:80;
    server_name 127.0.0.1;
    location /nginx_status {
        stub_status on;
        allow 127.0.0.1;
        deny all;
    }
}`

**Comment by thomasleveil** [comment]
Note that `127.0.0.1` in `listen 127.0.0.1:80` will make the `/nginx_status` path only accessible from the nginx-proxy container itself. Is this what you were trying to do?

The code you provided works fine, maybe you are not calling `http://127.0.0.1/nginx_status` from the `nginx-proxy` container. The following reports the status on my computer (assuming the nginx proxy container is named `nginx-proxy`):

    $ docker exec nginx-proxy wget -qO - http://127.0.0.1/nginx_status
    Active connections: 1 
    server accepts handled requests
     2 2 2 
    Reading: 0 Writing: 1 Waiting: 0

**Comment by TigPT** [comment]
You are right.

I was trying to access from the docker host. Should I use docker0 instead?

Sorry my noob networking questions, I'm new to it.

**Comment by thomasleveil** [comment]
Since that bit of conf is only listening on 127.0.0.1, you have no choice
but to call it from inside the nginx container.

Le mar. 14 mars 2017 à 11:28, Tiago Rodrigues <notifications@github.com> a
écrit :

**Comment by TigPT** [comment]
I can now check the proxy status from the docker host with this change.

`server {
    server_name MY_PUBLIC_IP;
    location /nginx_status {
        stub_status on;
        access_log off;
        allow MY_PUBLIC_IP;
        deny all;
    }
}`

Thanks for your help @thomasleveil its working now. Its here for other if they need.

Do docker set any hostname to the docker host that I can use instead of manually enter IP? Thanks.

**Comment by jessequinn** [comment]
My suggestion, to you're question @tigpt , and to others that may be interested. You could always set static ips in your docker-compose and reference those static ips in your location segment. As an example,

```yaml
version: '3.7'

x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

networks:
  frontend:
    ipam:
      config:
        - subnet: 172.20.0.0/24

services:
  nginx-proxy:
    image: jwilder/nginx-proxy:latest
    container_name: nginx-proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    security_opt:
      - label:type:docker_t`
    volumes:
      - ./docker/public:/usr/share/nginx/html
      - ./docker/certs:/etc/nginx/certs:ro
      - ./docker/nginx-proxy/vhost.d:/etc/nginx/vhost.d
      - ./docker/nginx-proxy/my_proxy.conf:/etc/nginx/conf.d/my_proxy.conf:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    depends_on:
      - frontend
      - frontend2
    networks:
      frontend:
        ipv4_address: 172.20.0.10
    logging: *default-logging
```

and in your `my_proxy.conf`,

```text
server {
  listen 172.20.0.10:80;
  server_name 172.20.0.10;

  location /nginx_status {
    stub_status on;
    allow 172.20.0.10;
    allow 172.20.0.1;
    deny all;
  }
}
```

I needed this as I am using Metricbeat to access nginx_status. So I needed to make my configuration slightly more open.
