### ISSUE TITLE
template incorrectly created

### ISSUE THREAD

**Issue by NickBolles** [jwilder/nginx-proxy#764]
I have been struggling with this issue for a while, and have suspected this, but havent been able to prove it till now.

First off:
## **`docker version`**
```
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 10:40:59 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   3a232c8
 Built:        Tue Feb 28 07:52:04 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

## **`docker-compose version`**

```
docker-compose version 1.11.2, build f963d76f
docker-py version: 2.1.0
CPython version: 2.7.13
OpenSSL version: OpenSSL 1.0.2j  26 Sep 2016
```

## `docker images --format "{{.ID}}\t{{.Repository}}:{{.Tag}}" jwilder/nginx-proxy`

`5759c9e822de    jwilder/nginx-proxy:latest`

## docker-compose.yml:
(from: https://github.com/jwilder/nginx-proxy/blob/master/docker-compose.yml)
```
version: '2'
services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
    volumes:
      - "./proxy/conf.d:/etc/nginx/conf.d"
      - "./proxy/vhost.d:/etc/nginx/vhost.d"
      - "./proxy/certs:/etc/nginx/certs:ro"
      - "./proxy/htpasswd:/etc/nginx/htpasswd" 
      - "./proxy/html:/usr/share/nginx/html"
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
  dockergen:
    image: jwilder/docker-gen
    command: -notify-sighup nginx -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes_from:
      - nginx
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./proxy/templates/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl

  whoami:
    image: jwilder/whoami
    environment:
      - VIRTUAL_HOST=whoami.local
```

##  `docker-compose up` output
```
whoami_1     | Listening on :8000
nginx        | 2017/03/13 20:45:12 [emerg] 1#1: no host in upstream ":8000" in /etc/nginx/conf.d/default.conf:35
nginx        | nginx: [emerg] no host in upstream ":8000" in /etc/nginx/conf.d/default.conf:35
nginx exited with code 1
dockergen_1  | 2017/03/13 20:45:13 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification ''
dockergen_1  | 2017/03/13 20:45:13 Watching docker events
dockergen_1  | 2017/03/13 20:45:13 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification ''
```

the `no host in upstream ":8000" in /etc/nginx/conf.d/default.conf:35` part is the problem. Now if we look at the generated config, lines 33-45

```
upstream whoami.local {
           # docker_whoami_1
           server :8000;
}
server {
    server_name whoami.local;
    listen 80 ;
    access_log /var/log/nginx/access.log vhost;
    include /etc/nginx/vhost.d/default;
    location / {
        proxy_pass http://whoami.local;
    }
}
```

This can be fixed by changing the line `server :8000;` to `server docker_whoami_1:8000;`, or `<Container name>:8000`, because the container names are resolved to the container  IPs. After changing that line and doing `docker exec proxy nginx -s reload` and navigating to `http://whoami.local/`
the web page appears! Woo!

So now the question is how to fix the generation. I thought that changing line 9-10 in the nginx.tmpl from 
```
            # {{ .Container.Name }}
            server {{ .Address.IP }}:{{ .Address.Port }};
```
```
            # {{ .Container.Name }}
            server {{ .Container.Name }}:{{ .Address.Port }};
```

would fix the problem, but the generated config doesn't change. Is this because the template isn't being placed correctly?
`docker exec -it docker_dockergen_1 cat /etc/docker-gen/templates/nginx.tmpl`
prints out the correct template though...
also, 
`docker exec -it docker_dockergen_1 sh` and `find . -name '*.tmpl'` only prints out  
`./etc/docker-gen/templates/nginx.tmpl`

So I am stumped... can someone help me out?
