### ISSUE TITLE
Have to use port to access certain vhosts

### ISSUE THREAD

**Issue by moltra** [jwilder/nginx-proxy#779]
I have 3 web server containers running on the same VPS.  I have to include the port number on 2 of the web servers and do not have to on the 3rd.  ie example.com works great on one server.  But if I try to go to myexample.com which is in a different container, I have to include the port in the address bar.

Here is part of my docker-compose file.
```
#Nginx server

  nginx:
    image: nginx
    container_name: nginx
    ports:
    - "80:80"
    - "443:443"
    volumes:
      - /home/sstrickland/nginx:/etc/nginx/conf.d
      - /home/sstrickland/logs:/var/log/nginx
      - "/home/sstrickland/vhost.d:/etc/nginx/vhost.d:rw"
      - /usr/share/nginx/html
      - /home/sstrickland/certs:/etc/nginx/certs:ro

  #nginx-gen
  #repository   https://github.com/jwilder/docker-gen
  nginx-gen:
    image: jwilder/docker-gen
    container_name: nginx-gen
    volumes_from:
      - nginx
    volumes:
      - /home/sstrickland/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    command: -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf

  #nginx-proxy
  #repository   https://github.com/jwilder/nginx-proxy
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    volumes:
      - /var/run/docker.sock:/home/sstrickland/docker.sock:ro   
    volumes_from:
      - nginx-gen`

  example:
    image: wordpress
    container_name: example
    restart: always
    links:
      - mariadb:mysql
    environment:
      - VIRTUAL_HOST=www.example.com,example.com
      - LETSENCRYPT_HOST=www.example.com,example.com
      - LETSENCRYPT_EMAIL=contact@example.com
      - WORDPRESS_DB_NAME=
      - WORDPRESS_DB_PASSWORD=
    ports:
      - "87:80"
      - "445:443"
    working_dir: /var/www/html
    volumes:
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - /home/user/example:/var/www/html

  example_two:
    image: wordpress
    container_name: example_two
    restart: always
    links:
      - mariadb:mysql
    environment:
      - VIRTUAL_HOST=www.example_two.com,example_two.com
      - LETSENCRYPT_HOST= www.example_two.com,example_two.com
      - LETSENCRYPT_EMAIL= orders@example_two.com
      - WORDPRESS_DB_NAME=
      - WORDPRESS_DB_PASSWORD=S
    ports:
      - "86:80"
      - "444:443"
    working_dir: /var/www/html
    volumes:
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - /home/yser/example_two:/var/www/html

  doesnotwork:
    image: wordpress
    container_name: doesnotwork
    restart: always
    links:
      - mariadb:mysql
    environment:
      - VIRTUAL_HOST=doesnotwork.info,www.doesnotwork.info
      - WORDPRESS_DB_NAME=
      - WORDPRESS_DB_PASSWORD=
    ports:
      - "88:80"
      - "446:443"
    working_dir: /var/www/html
    volumes:
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - /home/user/doesnotwork:/var/www/html

```

If I go to http:/example.com and http://example_two.com everything is fine.  If i go to http://doesnotwork.com It does not work but if I go to **http://doesnotwork.com:88** It works great.

Any and all help is greatly appreciated.
