### ISSUE TITLE
Provide a working example for Mac in README

### ISSUE THREAD

**Issue by razbakov** [jwilder/nginx-proxy#787]
Hello,

I struggled for a few days to found a working configuration.

Problem, which I had:

- 503 Service temporary unavailable (because whoami service is using port `8000`, not `80`)
- curl: (7) Failed to connect to localhost port 80: Connection refused (because Mac Firewall blocks port `80`)
- in order to open `whoami.nginx.container.docker` in browser you have to add line `127.0.0.1 whoami.nginx.container.docker` in `/etc/hosts` file

Here is what finally worked for me:

`docker-compose.yml`:

```
version: '2'

services:
  nginx:
    image: jwilder/nginx-proxy
    container_name: nginx
    ports:
      - 8080:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  web:
    image: jwilder/whoami
    container_name: whoami
    ports:
      - 8091:8000
    expose:
      - "8000"
    environment:
      WEB_PORTS: 8000
      VIRTUAL_HOST: whoami.nginx.container.docker

  dockergen:
    image: jwilder/docker-gen
    command: -notify-sighup nginx -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes_from:
      - nginx
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
```
