### ISSUE TITLE
empty upstream for a container

### ISSUE THREAD

**Issue by sandrodz** [jwilder/nginx-proxy#793]
I'm trying to run https://github.com/zammad/zammad-docker-compose this with nginx-proxy.

I've modified zammad-nginx:

<img width="461" alt="screen shot 2017-04-17 at 7 30 31 pm" src="https://cloud.githubusercontent.com/assets/8479569/25093670/5528dfd8-23a4-11e7-9063-79ca1aa68e9d.png">

but dockergen doesn't generate correct config, upstream block is empty

<img width="430" alt="screen shot 2017-04-17 at 7 33 55 pm" src="https://cloud.githubusercontent.com/assets/8479569/25093791/dcccc0da-23a4-11e7-95e4-563e247ff176.png">

what am I doing wrong?

**Comment by thomasleveil** [comment]
try with:

      environment:
        VIRTUAL_HOST: zammad.kubikthemes.com
        VIRTUAL_PORT: 80

**Comment by ITSOES** [comment]
My guess is that port 80 isn't exposed. If it helps...  https://docs.docker.com/compose/compose-file/#expose

**Comment by sandrodz** [comment]
@ITSOES do I've a major hole in my docker knowledge? I thought publishing ports was automatically exposing them.

**Comment by thomasleveil** [comment]
- *exposed* port is a property of a *docker image*
- *published* port is a property of a *docker container*

The image's exposed ports are automatically published if you create and run a container from it using the [`-P` option](https://docs.docker.com/engine/reference/run/#expose-incoming-ports).

**Comment by sandrodz** [comment]
hm I've tried to expose via docker-compose.yml but no go.

<img width="528" alt="screen shot 2017-04-24 at 12 12 48 am" src="https://cloud.githubusercontent.com/assets/8479569/25317087/d9709096-2882-11e7-97b2-d4d0e5f3bfcb.png">

<img width="473" alt="screen shot 2017-04-24 at 12 12 52 am" src="https://cloud.githubusercontent.com/assets/8479569/25317088/dba31a00-2882-11e7-8e35-8eb955ab9599.png">

**Comment by thomasleveil** [comment]
which version of the compose syntax are you using? There is a difference regarding how docker networks are created depending on the compose version

**Comment by sandrodz** [comment]
its version: 3.

**Comment by thomasleveil** [comment]
This works for me

![image](https://cloud.githubusercontent.com/assets/42300/25317374/d24c0c60-2877-11e7-8cfa-e23db0e6c5f6.png)

**Comment by sandrodz** [comment]
what does entry in config say?
docker exec -it nginx-proxy cat /etc/nginx/conf.d/default.conf

I still get empty upstream :( 

its driving me nuts.

**Comment by thomasleveil** [comment]
```
server {
	server_name _; # This is just an invalid value which will never trigger on a real hostname.
	listen 80;
	access_log /var/log/nginx/access.log vhost;
	return 503;
}
# zammad.home.thomasleveil.fr
upstream zammad.home.thomasleveil.fr {
				## Can be connect with "zammaddockercompose_default" network
			# zammaddockercompose_zammad-nginx_1
			server 172.22.0.7:80;
}
server {
	server_name zammad.home.thomasleveil.fr;
	listen 80 ;
	access_log /var/log/nginx/access.log vhost;
	location / {
		proxy_pass http://zammad.home.thomasleveil.fr;
	}
}
```

are you starting nginx-proxy without docker-compose?

**Comment by sandrodz** [comment]
@thomasleveil I'm starting it with docker-compose but in a seperate file.

<img width="401" alt="screen shot 2017-04-24 at 1 15 12 am" src="https://cloud.githubusercontent.com/assets/8479569/25317529/7b742e40-288b-11e7-82d8-487797d28fb8.png">

**Comment by sandrodz** [comment]
So I've nginx-proxy and zammad on different networks.

But I've tried: `docker network connect zammadkubikthemescom_default nginx-proxy` where `zammadkubikthemescom_default` is zammads network, no luck.

**Comment by thomasleveil** [comment]
That's the issue. Each docker compose file will create its own set of docker networks. containers from different compose files cannot talk to each others by default.

If you really want to keep separated compose files, you need to manually create a docker network : `docker network create nginx-proxy-net`

Then in the compose file for nginx proxy:

```
cat docker-compose-nginx-proxy.yml 
version: '3'

services:

  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - external-foo

networks:
  external-foo:
    external:
      name: nginx-proxy-net
```

and in the compose file for zammad:
![image](https://cloud.githubusercontent.com/assets/42300/25317682/b66ce252-287d-11e7-9aae-89a63c187153.png)

**Comment by thomasleveil** [comment]
another way would be to add the following `docker-compose.override.yml` file in the same directory as the zammad compose file:

```
version: '3'

services:

  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  zammad-nginx:
    environment:
      VIRTUAL_HOST: zammad.home.thomasleveil.fr
```

and remove the following lines from the zammad `docker-compose.yml` file:

```
    ports:
      - "80:80"
```

Then, just call `docker-compose up`. See [this doc](https://docs.docker.com/compose/extends/) for details on how to extend and do overrides with compose.
