### ISSUE TITLE
Making multiples containers

### ISSUE THREAD

**Issue by lramos1994** [jwilder/nginx-proxy#796]
I have multiple containers but keep getting status 503.

*docker-compose 1*
```
version:` '2'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
```

*docker-compose 2*
```
version: '2'
services:
  whoami:
    image: jwilder/whoami
    environment:
      - VIRTUAL_HOST=teste1.dev
```

*docker-compose 3*
```
version: '2'
services:
  whoami:
    image: jwilder/whoami
    environment:
      - VIRTUAL_HOST=teste2.dev
```

When i put on the same docker-compose works, but i need separated compose files.

**Comment by falnos24865** [comment]
Why was this closed? I am having the same issue and all documentation assumes that you only have one docker-compose.yml file. Its not practical to have one when managing large numbers of services so I would like to figure this out.

**Comment by chrisivens** [comment]
I think you can achieve what you want @falnos24865 by specifying a network to communicate over.

I create one before bringing up any of my containers and they connect to the proxy-tier network, named proxy when creating it.

```
networks:
  proxy-tier:
    external:
      name: "proxy"
```
