### ISSUE TITLE
Question: how-to enable CORS 

### ISSUE THREAD

**Issue by niksubramanian** [jwilder/nginx-proxy#804]
Hi there,

First of all, thanks for the wonderful package: it simplifies life tremendously!

# The issue I'm looking to solve
I'm looking for a way to extend the proxy to __enable CORS between subdomains__. 

More specifically, in a scenario with three services...
* ```jwilder/nginx-proxy```
* ```image/foo```  with ```VIRTUAL_HOST=foo.mydomain.com```
* ```image/bar``` with ```VIRTUAL_HOST=bar.mydomain.com```

... I'd like nginx to set the headers to allow CORS between ```foo.mydomain.com``` and ```bar.mydomain.com```, but not from outside of the domain (e.g. ```www.otherdomain.com```).

# What the docker-compose file looks like
```
version: "3.2"
services:
    proxy:
        image: jwilder/nginx-proxy
        ports:
            - "80:80"
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro     
    foo:
        image: image/foo
        env:
            - VIRTUAL_HOST=foo.mydomain.com
    bar:
        image: image/bar
        env:
            - VIRTUAL_HOST=bar.mydomain.com 
```

# What I've already tried
I understand that I can _replace_ the default proxy settings, but ideally, I'd just like to _extend_ it with this functionality. Through some googling, [I've found a way to approach this issue](http://rustyrazorblade.com/2013/10/cors-with-wildcard-subdomains-using-nginx/), but I'm unsure about how I'd go about and actually implement this.

The general approach would be to add this block of code in each ```server``` block of ```/etc/nginx/conf.d/default.conf```:
```
server {
    set $cors "";
    if ($http_origin ~* (.*\.mydomain.com)) {
        set $cors "true";
    }
    location / {
        if ($cors = "true") {
            add_header 'Access-Control-Allow-Origin' "$http_origin";
            add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, DELETE, PUT';
            add_header 'Access-Control-Allow-Credentials' 'true';
            add_header 'Access-Control-Allow-Headers' 'User-Agent,Keep-Alive,Content-Type';
        }
        if ($request_method = OPTIONS) {
            return 204;
        }
    }
}
```
However, this approach overwrites all the other elements in the ```server``` block, such as ```server_name```, and hence, doesn't achieve my purposes.

Is there any canonical approach to this problem?

Thanks in advance for your help and insights.
