### ISSUE TITLE
VIRTUAL_PORT not working with docker-compose.yml

### ISSUE THREAD

**Issue by DRogue1337** [jwilder/nginx-proxy#816]
I'm running my GitLab container with the following docker-compose.yml

**docker-compose.yml**
```
web:
  container_name: 'test.gitlab.code.ag'
  image: 'gitlab/gitlab-ce:latest'
  restart: always
  hostname: 'test.gitlab.code.ag'
  environment:
    VIRTUAL_HOST: test.gitlab.code.ag
    VIRTUAL_PORT: 8080
    GITLAB_OMNIBUS_CONFIG: |
      external_url 'http://test.gitlab.code.ag'
      registry_external_url 'http://test.gitlab.code.ag:4567'
      # Add any other gitlab.rb configuration here, each on its own line
  ports:
    - '8080:80'
    - '44300:443'
    - '22000:22'
  volumes:
    - '/srv/gitlab/config:/etc/gitlab'
    - '/gitlab/logs:/var/log/gitlab'
    - '/srv/gitlab/gitlab/data:/var/opt/gitlab'
```

Relevant output of `docker exec nginx-proxy cat /etc/nginx/conf.d/default.conf`
```
# test.gitlab.code.ag
upstream test.gitlab.code.ag {
                                ## Can be connect with "bridge" network
                # test.gitlab.code.ag
                server 172.17.0.4 down;
}
```

Using the nginx-proxy's `docker-compose.yml` didn't work so easily together with my GitLab `docker-compose.yml` so I decided to just go with the simple run command for nginx-proxy:

```
docker run -d --name nginx-proxy -p 80:80 \
  -v /var/run/docker.sock:/tmp/docker.sock:ro \
  jwilder/nginx-proxy
```

What am I doing wrong that the VIRTUAL_PORT is not recognized?
