### ISSUE TITLE
Q: How to configure independent containers

### ISSUE THREAD

**Issue by sekiroh** [jwilder/nginx-proxy#827]
Is it possible to have two independent running containers running on different ports?

```yaml
# folder1/docker-compose.yml
version: '2'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "5550:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  whoami:
    image: jwilder/whoami
    environment:
      - VIRTUAL_HOST=whoami1.local
```

```yaml
# folder2/docker-compose.yml
version: '2'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "5551:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  whoami:
    image: jwilder/whoami
    environment:
      - VIRTUAL_HOST=whoami2.local
```

I thought that docker-compose was creating different networks. I can start the two docker-compose files, but when I restart one, there are some interactions with the other.

```text
$ folder1: docker-compose up

# folder2 logs:
2017/05/19 17:46:45 Received event start for container eedf5331f57b
```
I don't want any interaction, just having two independent projects.
