### ISSUE TITLE
[Support] Redirect port 12080 to https without port

### ISSUE THREAD

**Issue by iamstevetran** [jwilder/nginx-proxy#833]
I'm having difficulties configuring the reserved proxy with my app.

My app (Gitlab) have 12080 exposed port followed [docker gitlab](https://github.com/sameersbn/docker-gitlab)'s configurations.

All absolute url in the app are now started with `http://mygitlab.com:12080/`, and will be redirected to `https://mygitlab.com:12080/` which will be broken.

I managed to redirect all url started with `http://$host:12080` to `https://$host` for only `$host` named `mygitlab.com` but I don't familiar with Go template, and took a lot of time researching but still have no idea how it work.

Any glue to resolve this is highly appreciated.

**Comment by DRogue1337** [comment]
I'm assuming right now that your desired outcome is to have `https://mygitlab.com` as your GitLab url.

The `nginx-proxy` doesn't actually need a port to be bound to the outside of your gitlab container, the port your GitLab install **inside** the container uses(80) only needs to be exposed. Since this is not the only port your gitlab container is exposing, you need to add `-e VIRTUAL_PORT=80` to your `docker run` command.

I'm not 100% sure how the image your are using needs to be configured to work here. But I guess you have to enable https for your gitlab install inside the container, too.

There' also an official gitlab docker instruction you could use (that's what I'm using): https://docs.gitlab.com/omnibus/docker/README.html

My **docker-compose.yml**, maybe it can help you.
```
web:
  container_name: '$server_name'
  image: 'gitlab/gitlab-ce:latest'
  restart: always
  hostname: '$server_name'
  environment:
    VIRTUAL_HOST: $server_name
    VIRTUAL_PORT: 80
    LETSENCRYPT_HOST: $server_name
    LETSENCRYPT_EMAIL: $lc_email
    GITLAB_OMNIBUS_CONFIG: |
      external_url 'https://$server_name'
      registry_external_url 'https://$server_name:4567'
      gitlab_rails['gitlab_shell_ssh_port'] = $GITLAB_SHELL_SSH_PORT
      nginx['listen_port'] = 80
      nginx['listen_https'] = false
      nginx['proxy_set_headers'] = { "X-Forwarded-Proto" => "https", "X-Forwarded-Ssl" => "on" }

  ports:
    - '$GITLAB_SHELL_SSH_PORT:22'
  volumes:
    - '$files_path/config:/etc/gitlab'
    - '$files_path/logs:/var/log/gitlab'
    - '$files_path/data:/var/opt/gitlab'
    - '$files_path/certs:/etc/gitlab/ssl'
```
