### ISSUE TITLE
Docker Compose application silently goes down from time to time. `docker ps` to wake it up. 

### ISSUE THREAD

**Issue by levibostian** [jwilder/nginx-proxy#840]
I have a nodejs application I have running via Docker Compose:

```
version: '2'
services:
  caddy-app:
    build: .
    user: app
    working_dir: /home/app/caddy-app
    command: npm run run-build
    expose:
     - "5000"
    restart: always
    environment:
      - NODE_ENV=production
      - VIRTUAL_HOST=api.foo.co
      - LETSENCRYPT_HOST=api.foo.co
      - LETSENCRYPT_EMAIL=foo@bar.com
    links:
      - redis
  redis:
      image: "redis:3.2.8-alpine"
      restart: always
      expose:
          - "6379"
      volumes:
          - /home/core/redis-storage/caddy-app-prod/:/usr/local/var/db/redis/
  nginx-proxy:
    image: "jwilder/nginx-proxy:alpine"
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/nginx/certs:/etc/nginx/certs:ro
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
  letsencrypt-nginx-proxy-companion:
      image: "jrcs/letsencrypt-nginx-proxy-companion"
      restart: always
      volumes_from:
          - nginx-proxy
      depends_on:
          - nginx-proxy
      volumes:
        - /etc/nginx/certs:/etc/nginx/certs:rw
        - /var/run/docker.sock:/var/run/docker.sock:ro
```

`caddy-app` service is building via a Dockerfile extending the image: `node:6.10.0-alpine` and is simply copying the source code into the container and running `npm install` before starting it. 

I have this Docker Compose application running on a DigitalOcean CoreOS Stable VM with 1GB ram and 1 core CPU. 

This application has been live for 2 months. It has been running great for these 2 months. I use updown.io to ping my API every 2 minutes to check if a ping returns a 200 to check the uptime of my server. 

This morning I was notified by updown.io that my application was down. I checked my Sentry logs, my application did not crash. I logged into my VM and checked my `caddy-app` Node application assuming that was the cause of the service being down, no crashes of any kind. 

Then, I ran `docker ps`, had to wait ~10 seconds for it to print to me the output of `docker ps` where it listed all of my containers for my application. All of the containers said they have been up for 3 seconds. A simple `docker ps` command was what got them back up and running. Huh, weird. 

I then proceeded to check the logs of all of my containers. Redis, postgres, then `jwilder/nginx-proxy:alpine` and `jrcs/letsencrypt-nginx-proxy-companion` where I found these messages:

`jrcs/letsencrypt-nginx-proxy-companion`:
![screen shot 2017-06-01 at 12 18 42 pm](https://cloud.githubusercontent.com/assets/2041082/26691941/9857d582-46c4-11e7-8679-11247e3b90d0.png)

`jwilder/nginx-proxy:alpine`:
![screen shot 2017-06-01 at 12 15 45 pm](https://cloud.githubusercontent.com/assets/2041082/26691877/67970df0-46c4-11e7-9a80-dc0eb0635bb5.png)

I am not sure when `forego` ran as I don't see a timestamp to see if that happened around `9:13` around the last time the updown.io bot pinged it or if it ran when I entered `docker ps` and woke it up. 

Either way, it seems as though the `jwilder/nginx-proxy` container had an issue and terminated. 

This is the first time this has happened to this particular application I have running. It has, however, also happened to me for another application I am running with the same exact configuration. Same Node type of app (minus redis), same OS, same VM, same Docker Compose file setup. Same issue has happened to it where I login, enter `docker ps` and we are back up and running. 

Any ideas for this issue?
