### ISSUE TITLE
Docker Cloud and SSL Certs

### ISSUE THREAD

**Issue by mjdavies** [jwilder/nginx-proxy#844]
Hi everyone

Apologies for possibly the dumbest question for a while.

We're using nginx-proxy as the front end proxy on nodes managed by docker cloud.

I stipulate the nginx-proxy stack file like so.

```
nginx-proxy:
  image: 'jwilder/nginx-proxy:latest'
  ports:
    - '80:80'
  tags:
    - stage2
  volumes:
    - '/var/run/docker.sock:/tmp/docker.sock:ro'
```

I know want to start using ssl certificates, but don't want to add the certificates to the actual VM file system, as I can't easily move everything then, if I needed to.

So, would the plan be to create our own version of the nginx-proxy image with the certificates added to that?  Then refer to that in the image section?

image:'ourdockrehubrepo/nginx-proxy:latest'

I'm not quite sure how I'd then refer to the certs in the volumes section, of even I'd need to.

Any help or tips greatly appreciated.
