### ISSUE TITLE
Running nginx-proxy outside of docker-compose; inter-container communication from compose

### ISSUE THREAD

**Issue by vonky** [jwilder/nginx-proxy#854]
Hey there, great work on this. I have what is potentially a _different_ use case than what you had in mind when developing this image, but probably not one a _unique_ one.

Effectively, I'd like to run `nginx-proxy` on my host, on its own. The reason for this is so that I can map multiple projects to the same IP in my host machine's `/etc/hosts`, and have everything work seamlessly. I'm using `docker-compose` for the projects, and here's a simplified example of how I have this working.

First, I started an instance of `nginx-proxy` on its own, so that it's always running:

```
docker run \
    --detach \
    --publish 80:80 \
    --publish 443:443 \
    --volume nginx-vhostd:/etc/nginx/vhost.d:ro \
    --volume /var/run/docker.sock:/tmp/docker.sock:ro \
    --restart always \
    --name nginx-proxy \
    jwilder/nginx-proxy:alpine
```

Next, I created a `docker-compose.yml` file for a project:

```
version: '3'

services:

  web:
    build:
      context: ./lib/docker/web
      args:
        VIRTUAL_HOST: dev.myproject.com
        APP_ROOT: \/var\/www\/html
        APP_INDEX: index.html
    network_mode: bridge
    volumes:
      - src:/var/www/html

volumes:
  src:
    driver_opts:
      type: none
      device: ${PWD}/src
      o: bind
```

The `web` service might look a bit odd, but the envvar `VIRTUAL_HOST` gets set _from_ the build argument. I did this simply to avoid duplicating my arg/var definitions in the compose file. For the curious, the `Dockerfile` for the `web` service looks like:

```
FROM nginx:1.12-alpine

ARG VIRTUAL_HOST
ARG APP_ROOT
ARG APP_INDEX

ENV VIRTUAL_HOST ${VIRTUAL_HOST}

COPY ./nginx.conf /etc/nginx/conf.d/default.conf
RUN sed --in-place \
    -e 's/{{VIRTUAL_HOST}}/'"${VIRTUAL_HOST}"'/g' \
    -e 's/{{APP_ROOT}}/'"${APP_ROOT}"'/g' \
    -e 's/{{APP_INDEX}}/'"${APP_INDEX}"'/g' \
    /etc/nginx/conf.d/default.conf && \
    cat /etc/nginx/conf.d/default.conf
```

And the `nginx` configuration, in my running container (after the `sed` substitution), looks like:

```
server {
  listen 80;
  root {{APP_ROOT}};
  index {{APP_INDEX}};
  server_name {{VIRTUAL_HOST}};
}
```

So far, so good. Everything works peachy, and the `nginx-proxy` container has successfully regenerated the `default.conf` configuration file:

```
upstream dev.myproject.com {
        server <ip-of-container>;
}
server {
        server_name dev.myproject.com;
        listen 80 ;
        access_log /var/log/nginx/access.log vhost;
        location / {
                proxy_pass http://dev.myproject.com;
        }

```

**This works great**. However, an issue arises when adding a backend within the `compose` file; for example, `php-fpm`:

```
php-fpm:
    image: php:7.1-fpm-alpine
```

And adjusting the nginx configuration (in the project's nginx container) to proxy requests to this container:

```
location ~ \.php$ {
    try_files $uri =404;
    fastcgi_pass php-fpm:9000;
    fastcgi_index index.php;
    include fastcgi_params;
}
```

The hostname `php-fpm` isn't available, because the `web` service (running nginx) needs to have `network_mode: bridge` defined in order to be picked up by `nginx-proxy`.

Sorry for the super long post. Does anyone have any ideas how to accomplish what I want?
