### ISSUE TITLE
USE_IP_HASH seems to have zero impact to the default.conf

### ISSUE THREAD

**Issue by redskate** [jwilder/nginx-proxy#871]
Hi,

My docker-compose definition for your nginx is:

```
nginx:
    image: xxx-nginx
    restart: always
    environment:
      DEFAULT_HOST: xxx.local #mandatory to load balance
      USE_IP_HASH: 1
    ports:
      - 90:80
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "./nginxlogs:/var/log/nginx"
    links:
      - xxx_tomcat_node_1
      - xxx_tomcat_node_2
```

When I bash log in into the corrensponding nginx container, and look into `/etc/nginx/conf.d/default.conf`, I do not find ip_hash" in it - why?
