### ISSUE TITLE
AWS EC2 issue?

### ISSUE THREAD

**Issue by latitudehopper** [jwilder/nginx-proxy#888]
I am trying to get this working on an EC2 instance. The same docker-compose file works locally but will not resolve in AWS. XXX is to protect sensitive data. On my local version I run oscp2.local and have it set in my hosts file. The A record for the VIRTUAL_HOST value is pointing at the IP for the box. Has anyone else see this issue?
```
proxy:
 image: "jwilder/nginx-proxy"
 ports:
  - "80:80"
 volumes:
  - /var/run/docker.sock:/tmp/docker.sock:ro
postgres:
 image: "mdillon/postgis"
 container_name: postgres
 volumes:
  - ~/postgres/data:/var/lib/postgresql
 environment:
  - DB_PASSWORD=postgres
 ports:
  - "5432:5432"
web:
 image: "XXXXXXX.dkr.ecr.eu-west-2.amazonaws.com/oscp"
 container_name: web
 environment:
  - DB_HOST=XXX.XXX.XXX.184
  - DB_USER=postgres
  - DB_PASS=postgres
  - VIRTUAL_HOST=oscp2.XXX.com
 links:
  - postgres
```
