### ISSUE TITLE
Problems setting up nginx-proxy with official wordpress image

### ISSUE THREAD

**Issue by Nihilivin** [jwilder/nginx-proxy#892]
Hi,
I'm trying for several hours to set up properly nginx-proxy with wordpress docker images. I have 2 docker-compose.yml files

Here is my docker-compose.yml file for nginx-proxy
```yaml
version: "3"
volumes:
  nginx-socket:
    driver: local-persist
    driver_opts:
      mountpoint: "/var/run/docker.sock:"
services:
#  letsencrypt:
#    labels:
#      io.rancher.scheduler.global: 'true'
#      io.rancher.container.pull_image: always
#    image: thomastweets/docker-letsencrypt-nginx-proxy-companion:latest
#    volumes:
#      - nginx-socket:/var/run/docker.sock:ro
#      - /var/run/docker.sock:/var/run/docker.sock:ro
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
  whoami:
    image: jwilder/whoami
    environment:
      - VIRTUAL_HOST=whoami.local
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - 8080:8080
    volumes:
      - nginx-socket:/var/run/docker.sock:ro
    deploy:
      placement:
        constraints: [node.role == manager]
networks:
  nginx-proxy:
```

Here is my docker-compose.yml file for my wordpress site
```yaml
version: "3"
services:
  web:
    depends_on:
      - mysql
    # replace username/repo:tag with your name and image details
    image: wordpress:4.8.0-php7.0-fpm-alpine
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    environment:
      VIRTUAL_HOST: test.local
      WORDPRESS_DB_PASSWORD: "mypass_user"
      WORDPRESS_DB_USER: "myuser"
      WORDPRESS_DB_NAME: "db"
    depends_on:
      - mysql
    ports:
      - 14225:80
    volumes:
      - ./data/wordpress:/var/www/html
    networks:
      - webnet
      - nginx-proxy
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root_password"
      MYSQL_DATABASE: "db"
      MYSQL_ROOT_HOST: "%"
      MYSQL_USER: "myuser"
      MYSQL_PASSWORD: "mypass_user"
    ports:
      - 3306:3306
    volumes:
      - ./data/mysql:/var/lib/mysql
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
networks:
  webnet:
  nginx-proxy:
    external:
      name: nginx_proxy_default
```

I first started up my nginx-proxy stack, then my WordPress stack. Both start-up successfully. Logs in the nginx-proxy container after the WP stack init are the following:
```
dockergen.1 | 2017/08/01 00:06:52 Received event start for container ddf6c1c3212e
dockergen.1 | 2017/08/01 00:06:52 Generated '/etc/nginx/conf.d/default.conf' from 4 containers
dockergen.1 | 2017/08/01 00:06:52 Running 'nginx -s reload'
```
And finaly, my `default.conf` file is the following: 
```
# If we receive X-Forwarded-Proto, pass it through; otherwise, pass along the
# scheme used to connect to this server
map $http_x_forwarded_proto $proxy_x_forwarded_proto {
  default $http_x_forwarded_proto;
  ''      $scheme;
}
# If we receive X-Forwarded-Port, pass it through; otherwise, pass along the
# server port the client connected to
map $http_x_forwarded_port $proxy_x_forwarded_port {
  default $http_x_forwarded_port;
  ''      $server_port;
}
# If we receive Upgrade, set Connection to "upgrade"; otherwise, delete any
# Connection header that may have been passed to this server
map $http_upgrade $proxy_connection {
  default upgrade;
  '' close;
}
# Apply fix for very long server names
server_names_hash_bucket_size 128;
# Default dhparam
ssl_dhparam /etc/nginx/dhparam/dhparam.pem;
# Set appropriate X-Forwarded-Ssl header
map $scheme $proxy_x_forwarded_ssl {
  default off;
  https on;
}
gzip_types text/plain text/css application/javascript application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript;
log_format vhost '$host $remote_addr - $remote_user [$time_local] '
                 '"$request" $status $body_bytes_sent '
                 '"$http_referer" "$http_user_agent"';
access_log off;
# HTTP 1.1 support
proxy_http_version 1.1;
proxy_buffering off;
proxy_set_header Host $http_host;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection $proxy_connection;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $proxy_x_forwarded_proto;
proxy_set_header X-Forwarded-Ssl $proxy_x_forwarded_ssl;
proxy_set_header X-Forwarded-Port $proxy_x_forwarded_port;
# Mitigate httpoxy attack (see README for details)
proxy_set_header Proxy "";
server {
	server_name _; # This is just an invalid value which will never trigger on a real hostname.
	listen 80;
	access_log /var/log/nginx/access.log vhost;
	return 503;
}
# test.local
upstream test.local {
				## Can be connect with "ingress" network
			# wp_local_web.1.rklfgzgwkcxg0bht0na0p797h
			server 10.255.0.11:9000;
				## Can be connect with "nginx_proxy_default" network
			# wp_local_web.1.rklfgzgwkcxg0bht0na0p797h
			server 10.0.0.12:9000;
}
server {
	server_name test.local;
	listen 80 ;
	access_log /var/log/nginx/access.log vhost;
	location / {
		proxy_pass http://test.local;
	}
}
# whoami.local
upstream whoami.local {
				## Can be connect with "nginx_proxy_default" network
			# nginx_proxy_whoami.1.l1m51850xymws6xop5kufxvqy
			server 10.0.0.7:8000;
}
server {
	server_name whoami.local;
	listen 80 ;
	access_log /var/log/nginx/access.log vhost;
	location / {
		proxy_pass http://whoami.local;
	}
}
```

What I don't understand is why the config file set up my wordpress upstream using the port 9000. My WP install should bind the port 80, thus nginx should redirect to it but.... But I can't setup that. I've tried to use the `VIRTUAL_PORT` env var on my WP container, but it didn't work either.

What is wrong? What am I supposed to do?

Thank you, have a great day!
