### ISSUE TITLE
Allow labels to be used to set VIRTUAL_HOST, VIRTUAL_PORT and VIRTUAL_PROTO

### ISSUE THREAD

**Issue by Znafon** [jwilder/nginx-proxy#899]
Hi,

so far it's only possible to set variables as environment variables to configure `nginx-proxy`.

Would it be possible to let people use labels too, i.e. let them use this `docker-compose.yml` for exemple:
```
version: '2'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  whoami:
    image: jwilder/whoami
    container_name: whoami
    labels:
      - VIRTUAL_HOST=whoami.local
```

This could be useful when using other software that set themselves only using labels.
