### ISSUE TITLE
Clarification on virtual_port

### ISSUE THREAD

**Issue by jeeftor** [jwilder/nginx-proxy#907]
I'm having issues understanding how to use `VIRTUAL_PORT` to work with a mongo in a `docker-compose` file.

My `ngnix-proxy` is run like so:
```
docker run \
   -p 80:80 \
   -p 443:443 \
   --name nginx-proxy \
   --restart always \
   -v /var/run/docker.sock:/tmp/docker.sock:ro \
   -v ./certs:/etc/nginx/certs \
   jwilder/nginx-proxy
```

As I understand the way things I'm supposed to set it up so that I can have `ngnix-proxy` forward request to my host into a specific port - what I'm finding isn't working is this:
Not working:

```
  mongo:
    container_name: frn-mongo
    image: mongo
    expose:
      - "27017"
    environment:
      - VIRTUAL_HOST=frn-db.dev
    network_mode: bridge # See note at top for details on bridge mod
```    

According to the **Readme**

> If your container exposes multiple ports, nginx-proxy will default to the service running on port 80. If you need to specify a different port, you can set a VIRTUAL_PORT env var to select a different one. If your container only exposes one port and it has a VIRTUAL_HOST env var set, that port will be selected.

So I was assuming this setup should be correct - I'm exposing a single port `27017` and I have a `VIRTUAL_HOST` env variable set. 

What does work is adding a

```
   port:
   - "27017:27017"
```

and then i can call `mongo --host frn-db.dev` and it will connect, however, `mongo --host localhost` also works - which is not what i want.

Am I doing something wrong - or is the `README` no longer up to date?

If i just use `expose` and `VIRTUAL_HOST` and `VIRTUAL_PORT` I still cant seem to hit `27017` 

`nc -zv frn-db.dev 80` connects

`nc -zv frn-db.dev 27017` does not connect
