### ISSUE TITLE
Port not exposed

### ISSUE THREAD

**Issue by trash-anger** [jwilder/nginx-proxy#916]
Hi everyone,

I have an strange issue on my docker server !
I don't know if this issue is due to the nginx-proxy ...

When I launch my `docker-compose up -d` for the docker-compose.yml bellow, **it doesn't expose my ssh port** on the gitlab container :
```
root@serv:~# docker port nginx-proxy
443/tcp -> 0.0.0.0:443
80/tcp -> 0.0.0.0:80
root@serv:~# docker port root_gitlab_1
root@serv:~#
```
**docker-compose.yml** (I changed the gitlab_shell_ssh_port directly in the gitlab.rb)
```
version: '2'
services:
 nginx-proxy:
  image: jwilder/nginx-proxy
  restart: always
  container_name: nginx-proxy
  ports:
   - "80:80"
   - "443:443"
  volumes:
   - /var/run/docker.sock:/tmp/docker.sock:ro
   - /srv/nginx-proxy/custom_proxy.conf:/etc/nginx/conf.d/custom_proxy.conf:ro
   - /srv/nginx-proxy/html:/usr/share/nginx/html
   - /srv/nginx-proxy/vhost.d:/etc/nginx/vhost.d
   - /srv/nginx-proxy/certs:/etc/nginx/certs:ro

 nginx-letsencrypt:
  image: jrcs/letsencrypt-nginx-proxy-companion
  restart: always
  container_name: nginx-letsencrypt
  volumes_from:
   - nginx-proxy
  volumes:
   - /srv/nginx-proxy/certs:/etc/nginx/certs:rw
   - /var/run/docker.sock:/var/run/docker.sock:ro

 gitlab:
  image: gitlab/gitlab-ce
  restart: always
  hostname: 'gitlab.website.com'
  ports:
   - "7915:22"
  environment:
   VIRTUAL_PORT: 80
   VIRTUAL_HOST: gitlab.website.com,mattermost.website.com
   LETSENCRYPT_HOST: gitlab.website.com,mattermost.website.com
   LETSENCRYPT_EMAIL: me@website.com
   GITLAB_OMNIBUS_CONFIG: |
        nginx['listen_https'] = false
        nginx['proxy_set_headers'] = {
          "X-Forwarded-Proto" => "https",
          "X-Forwarded-Ssl" => "on"
        }
  volumes:
   - /srv/gitlab/config:/etc/gitlab
   - /srv/gitlab/logs:/var/log/gitlab
   - /srv/gitlab/data:/var/opt/gitlab

 gitlab-runner:
  image: gitlab/gitlab-runner
  restart: always
  volumes:
   - /srv/gitlab-runner/run/docker.sock:/var/run/docker.sock
   - /srv/gitlab-runner/etc:/etc/gitlab-runner
```
Has anyone ever had this problem ?
