### ISSUE TITLE
listening on subdomain

### ISSUE THREAD

**Issue by nofear87** [jwilder/nginx-proxy#920]
lets say nginx-proxxy listening on a subdomain: f.e. test.mydomain.com

container 1 
 - I add a env var: one.test.mydomain.com

container 2
- should be addressed by the nginx listening domain: test.mydomain.com
- just adding test.mydomain.com as env var seems not be enough?

**Comment by denzuko** [comment]
the config that is generated internally to the container follows normal nginx host matching. Basically, one upstream for `one.test.mydomain.com` and a separate upstream for `test.mydomain.com` with each container's 172/24 ip address as a proxy followed by single server directive for the FQDN.

So if your familar with normal nginx configs it will looks something like:
```
upstream one.test.mydomain.com {
    server 172.x.x.10:80;
}
server {
    server_name one.test.mydomain.com;
    listen 80;
    ...
}

...

upstream test.mydomain.com {
    server 172.x.x.20:80;
}
server {
    server_name test.mydomain.com;
    listen 80;
    ...
}
```

**Comment by nofear87** [comment]
seems it generates the correct config:

```
version: '2'

services:
  nginx-proxy:
    container_name: nginx-proxy
    image: jwilder/nginx-proxy
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
  tomcat:
    image: tomcat:8.0
    expose:
      - 8080
    container_name: tomcat
    environment:
      - VIRTUAL_HOST=tom.zpa.test.local
      - VIRTUAL_PORT=8080
```

config:
```

proxy_set_header Proxy "";
server {
        server_name _; # This is just an invalid value which will never trigger on a real hostname.
        listen 80;
        access_log /var/log/nginx/access.log vhost;
        return 503;
}
# tom.zpa.tuevthef.de
upstream tom.zpa.tuevthef.de {
                                ## Can be connect with "nginxproxy_default" network
                        # tomcat
                        server 172.18.0.3:8080;
}
server {
        server_name tom.zpa.test.local;
        listen 80 ;
        access_log /var/log/nginx/access.log vhost;
        location / {
                proxy_pass http://tom.zpa.test.local;
        }
}
```

but it seems its not running correctly. I can't reach tomcat over tom.zpa.test.local

**Comment by denzuko** [comment]
Thanks for posting your `docker-compose.yml` file and the generated config. I suggest running `docker-compose logs  -f nginx-proxy` and `docker-compose logs  -f tomcat` then using `curl -sLk -H 'host: tom.zpa.test.local' http://<docker-host-address>/` to debug what is coming back the review solutions for corresponding nginx/tomcat error and access logs.

Also to address your original question; one can use multiple domains in their VIRTUAL_HOST setting. One for global and one per container such as:

```
---
version: '2'

services:
  nginx-proxy:
    container_name: nginx-proxy
    image: jwilder/nginx-proxy
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  tomcat_1:
    image: tomcat:8.0
    container_name: tomcat-1
    environment:
      - VIRTUAL_HOST=one.tom.zpa.test.local,tom.zpa.test.local
      - VIRTUAL_PORT=8080
  tomcat_2:
    image: tomcat:8.0
    container_name: tomcat-2
    environment:
      - VIRTUAL_HOST=two.tom.zpa.test.local,tom.zpa.test.local
      - VIRTUAL_PORT=8080
```

I would focus more on debugging via docker-compose log for your application container and verifying that nginx-proxy is able to talk with the application container viva the method I pointed out above.
