### ISSUE TITLE
proxying for port 80 and multiple networks

### ISSUE THREAD

**Issue by oojacoboo** [jwilder/nginx-proxy#922]
I'm getting a bit frustrated and I'm typically quite good with this stuff.  So, I know I'm missing a big gotcha somewhere.  If someone could please direct me that'd be awesome.

I'll start with one example.  We have a number of Docker containers that all use their own network built with `docker-compose`

So, here is an example `docker-compose.yml` file for some containers, simplified for what matters.

*`nginx` container exposes port 80 through the Dockerfile*

```yaml
version: '3.3'

services:
  nginx:
    build: ./nginx
    image: api-nginx:dev
    container_name: api-nginx
    environment:
      - CONTAINER_ENVIRONMENT=dev
      - VIRTUAL_HOST=foo.dev
    links:
      - php
    networks:
      - api-net
    volumes:
      - ../app/public:/srv/www
  php:
    build: ./php
    image: api-php:dev
    container_name: api-php
    environment:
      - CONTAINER_ENVIRONMENT=dev
    networks:
      - api-net
    volumes:
      - ../app:/srv/www
      - ~/.ssh:/root/.ssh   # copy devs ssh keys to Docker container for Composer

networks:
  api-net:
    driver: bridge
```

So, this is really a pretty simple setup.  We just have an `nginx` container that's listening on port 80, but not exposing it.  I've tried various methods of port mapping this to `8080`, etc.  But we do not want to modify the base image to be listening on port `8080` or something similar.  We want it listening on port `80` only, to keep these images universal between prod and dev.

I've then run the following `nginx-proxy` container for this.

```bash
docker run -d --name=nginx-proxy -p 80:80 -v /var/run/docker.sock:/tmp/docker.sock:ro jwilder/nginx-proxy --net=api-net
```

In addition to this, I've tried `--net=host` to get around some of the network concerns.

Regardless of any attempts I make, I cannot seem to get the nginx-proxy to pick up http requests for `foo.dev` or `foo.dev:8080` when using port mapping via the `docker-compose.yml`.  I understand that port mapping via `docker-compose` isn't supported and it needs to be explicitly exposed.

What am I missing here?
