### ISSUE TITLE
Subdomain 502 Bad gateway

### ISSUE THREAD

**Issue by dasmedium** [jwilder/nginx-proxy#925]
Using any subdomain gives me a 502 Bad gateway screen. Im new at using this tool, but have checked the certs folder, and it looks like all certs for my domain (and new subdomains) are the same key. Any tips on getting LetsEncrypt to work with subdomains?

**Comment by mabushey** [comment]
I'm having the same issue. The wildcard crt and key are readable in the container, it redirects from http to https, and then gives:
```
nginx.1    | 2017/09/15 01:55:25 [error] 37#37: *1 SSL_do_handshake() failed (SSL: error:1408F10B:SSL routines:ssl3_get_record:wrong version number) while SSL handshaking to upstream, client: 47.180.[redacted].[redacted], server: jira.my.network, request: "GET /list HTTP/2.0", upstream: "https://172.20.0.4:8080/list", host: "jira.my.network"
```
The certs are included (from /etc/nginx/conf.d/default.conf):
server {
        server_name jira.my.network;
        listen 443 ssl http2 ;
...
        ssl_certificate /etc/nginx/certs/my.network.crt;
        ssl_certificate_key /etc/nginx/certs/my.network.key;
...
```

**Comment by mabushey** [comment]
Look at my issue https://github.com/jwilder/nginx-proxy/issues/930 , One of your issues is likely that proxy pass is pulling from your service via https and not https.

**Comment by geirgp** [comment]
I've been intermittently having the same problem and have found this workaround which resolves the issue, until it surfaces again: 

1. stop nginx, nginx-gen and ngingx-letsencrypt, 
2. delete the volume for `/etc/nginx/conf.d/` (keep all other volumes including certs).
3. bring everything up again

Voila (at least for my setup). I wish I knew how to reproduce this issue, but have yet to figure out what triggers it. 

My docker-compose.yml file is based on https://github.com/jwilder/nginx-proxy/blob/master/docker-compose-separate-containers.yml, the only addition is the letsencrypt service:
```
  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-letsencrypt
    restart: always
    volumes:
      - nginx-certs:/etc/nginx/certs/:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    volumes_from:
      - nginx
    environment:
      NGINX_DOCKER_GEN_CONTAINER: 'nginx-gen'
```

This bug was actually getting so annoying that I created a small script which does the above 3 steps for me:

```bash
#!/bin/bash

# name of current directory
project_name=${PWD##*/}
# remove hyphen
project_name=${project_name/[-]}
# name of the volume which holds nginx configuration files
volume_to_delete=${project_name}_nginx-conf

# Stop proxy services (nginx, nginx-gen, nginx-letsencrypt)
$(docker-compose stop| tee /dev/tty)

# Delete the `nginx-conf` volume, this should force `nginx-gen` to create a new one from scratch, and
# that seems to fix the problem, until it surfaces again...
docker volume rm $volume_to_delete

# Bring proxy back up
$(docker-compose up -d| tee /dev/tty)
```
