### ISSUE TITLE
SSL termination is broke with (valid HTTPS) 502 

### ISSUE THREAD

**Issue by mabushey** [jwilder/nginx-proxy#930]
Tested on 1.12.6, 17.03.2-ce, and 17.06.2-ce with the same results

`➜  jwilder git:(master) ✗ cat docker-compose.yml`
```
version: '2'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /home/ubuntu/certs:/etc/nginx/certs:ro

  whoami:
    image: jwilder/whoami
    container_name: whoami
    environment:
      - VIRTUAL_HOST=whoami.local

  example-app:
    image: tutum/apache-php
    container_name: example-app
    environment:
      - VIRTUAL_HOST=www.example.com
      - VIRTUAL_PROTO=https
```
`➜  jwilder git:(master) ✗ docker ps`
```
CONTAINER ID        IMAGE                 COMMAND                  CREATED             STATUS              PORTS                                      NAMES
7adba4cb0783        tutum/apache-php      "/run.sh"                3 minutes ago       Up 3 minutes        80/tcp                                     example-app
95b27264355d        jwilder/nginx-proxy   "/app/docker-entry..."   3 minutes ago       Up 3 minutes        0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   nginx-proxy
3bd20ebd58fd        jwilder/whoami        "/app/http"              3 minutes ago       Up 3 minutes        8000/tcp                                   whoami
```
`➜  jwilder git:(master) ✗ curl -H 'Host: whoami.local' www.example.com`
I'm 3bd20ebd58fd

`➜  jwilder git:(master) ✗ curl -i -H 'Host: www.example.com' http://www.example.com`
```
HTTP/1.1 301 Moved Permanently
...
Location: https://www.example.com/
...
```

`➜  jwilder git:(master) ✗ curl -H 'Host: www.example.com' https://www.example.com/`
```
<html>
<head><title>502 Bad Gateway</title></head>
```
I have used the jrcs/letsencrypt-nginx-proxy-companion comtainer to get a cert for the site, as well as copied over a wildcard cert. Both certs report "This page is secure (valid HTTPS)." for the 502. I also added `VIRTUAL_PORT=80` which should be the default but that didn't change anything. I don't see anything wrong with the nginx config other than TLSv1 and TLSv1.1 being rather outdated.
