### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by casper-gh** [jwilder/nginx-proxy#956]
I followed the instruction but couldn't get it to work. Says I have an existing app exposed to port 8080 on the host. I ran nginx-proxy and my app as followed:
    
    docker run -d -p 80:80 -v /var/run/docker.sock:/tmp/docker.sock:ro jwilder/nginx-proxy
    docker run -d -p 8080:8080  -e VIRTUAL_HOST=foo.bar.com  myapp

Now `curl localhost:8080` works, and "foo.bar.com" is where I access my app from (AWS Route 53 to Load balancer). How do I get nginx-proxy to work in this case?

**Comment by buchdag** [comment]
If your `myapp` container expose port 8080 and only port 8080 that should work out the box. Exposing and publishing ports with `-p` is not the same, but the latter imply the former (if you publish a port, docker will expose it on the container for you).

[If your container exports more than one port and 80 is one of them, `nginx-proxy` will default to port 80.](https://github.com/jwilder/nginx-proxy#multiple-ports) You'll have to use the VIRTUAL_PORT env var to select port 8080 `-e VIRTUAL_PORT=8080`

**Comment by tomasinouk** [comment]
Hi, i have a same question as @casper-gh 

I am trying a simple setup and get to 503 page as per the generated config `'/etc/nginx/conf.d/default.conf'`

I can see that the file has correct upstream and server sections, but for some reason does not route the traffic to that container.

When I do `-p 1880:1880`, that is those ports are available on a host. I can access the application from the container on that port via DNS e.g. `beta.example.com:1880`

When I `expose` the port, so I should get to the application via DNS `beta.example.com` that's where I get 503 page. 

I am using docker-compose.

```
version: "2"

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
    depends_on:
      - node-red
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  node-red:
    image: nodered/node-red-docker
    # ports:
    #   - "1880:1880"
    expose:
      - 1880
    volumes:
      - ./data/node-red/data:/data
    environment:
      - VIRTUAL_HOST=beta.example.com
```

Is there anything obvious, which I am missing here?
Any pointers would be great.
Thank you
