### ISSUE TITLE
Websocket return 502 error

### ISSUE THREAD

**Issue by ticruz38** [jwilder/nginx-proxy#976]
I know this issues has been raised and fixes many times, but reading at the existing issues didn't helped me.
I have a web socket server here is my docker-compose config
```
bnbkeeper-ws:
    image: *****/keepers:0.9
    container_name: bnbkeeper-ws
    restart: unless-stopped
    depends_on:
      - mongo
      - redis
    ports:
      - "3800:3800"
    links:
      - mongo
      - redis
    environment:
      - VIRTUAL_HOST=websocket.thibautduchene.fr
      - VIRTUAL_PORT=3800
      - LETSENCRYPT_HOST=websocket.thibautduchene.fr
      - LETSENCRYPT_EMAIL=thib.******@gmail.com
      - WEBSOCKETS=1
```

I read somewhere that we can add the WEBSOCKETS env var, but I'm not sure it's still valid.
In my websocket.conf file I added the required headers, here it is.

```
map $http_upgrade $connection_upgrade {
        default upgrade;
        '' close;
}


server {
	location / {
            	proxy_http_version 1.1;
            	proxy_set_header Upgrade $http_upgrade;
            	proxy_set_header Connection $connection_upgrade;
	}
}
```

connecting in my browser to wss://websocket.thibautduchene.fr return 
`client.js:356 WebSocket connection to 'wss://websocket.thibautduchene.fr/' failed: Error during WebSocket handshake: Unexpected response code: 502`

and here is the default.conf file generated by docker-gen

```
# websocket.thibautduchene.fr
upstream websocket.thibautduchene.fr {
				## Can be connect with "nginx-proxy" network
			# bnbkeeper-ws
			server 172.20.0.10:3800;
}
server {
	server_name websocket.thibautduchene.fr;
	listen 80 ;
	access_log /var/log/nginx/access.log vhost;
	return 301 https://$host$request_uri;
}
server {
	server_name websocket.thibautduchene.fr;
	listen 443 ssl http2 ;
	access_log /var/log/nginx/access.log vhost;
	ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
	ssl_ciphers 'ECDHE*********************************************6-SHA:!DSS';
	ssl_prefer_server_ciphers on;
	ssl_session_timeout 5m;
	ssl_session_cache shared:SSL:50m;
	ssl_session_tickets off;
	ssl_certificate /etc/nginx/certs/websocket.thibautduchene.fr.crt;
	ssl_certificate_key /etc/nginx/certs/websocket.thibautduchene.fr.key;
	ssl_dhparam /etc/nginx/certs/websocket.thibautduchene.fr.dhparam.pem;
	add_header Strict-Transport-Security "max-age=31536000";
	include /etc/nginx/vhost.d/default;
	location / {
		proxy_pass http://websocket.thibautduchene.fr;
	}
}
```

and here is the logs in docker-nginx

`[error] 6#6: *8 connect() failed (111: Connection refused) while connecting to upstream, client: 93.******, server: websocket.thibautduchene.fr, request: "GET / HTTP/1.1", upstream: "http://172.20.0.10:3800/", host: "websocket.thibautduchene.fr"`

when using ws://websocket.thibautduchene.fr I get a 301 error instead

**Comment by ticruz38** [comment]
Ok for those who wonder how to enable websockets this setting is completely good, , I just didn't exposed the right host from inside my container, that's why I had a 502 error, the curl didn't work either as it didn't reach the right host.

**Comment by elhe26** [comment]
Hi @ticruz38,

>  I just didn't exposed the right host from inside my container, that's why I had a 502 error, the curl didn't work either as it didn't reach the right host.

What do you mean by that? Do you mean something like this:

```yaml
...
    expose:
      - "8108"
    environment:
      - VIRTUAL_HOST=app.example.com,www.app.example.com,ws.app.example.com
      - VIRTUAL_PORT=8108
      - LETSENCRYPT_HOST=app.example.com,www.app.example.com,ws.app.example.com
      - LETSENCRYPT_EMAIL=cloud@example.com
...
```
