### ISSUE TITLE
How to configure TCP load balancing over 5222 port?

### ISSUE THREAD

**Issue by BrianJVarley** [jwilder/nginx-proxy#979]
**Overview:**
I've setup a stack using `docker-ejabberd` depending on `nginx-proxy` image for load balancing via port `5222`. During testing I can scale up without port conflicts using `docker-compose scale ejabberd=3`.

**Issue:**
What I've noticed with my current docker-compose.yml file is defining ports: `- 5222:5222` in the nginx image config, **doesn't open that TCP port** on the nginx container spun up. Which in turn doesn't forward traffic to the upstream ejjaberd image when I try to connect via an XMPP client.

**Question**
Is it possible to configure TCP load balancing in the nginx-proxy spec configurations?

**Testing**
I do notice that setting ports: `- 80:80` in the spec, opens that port to my client and I can ping it.
But port 80 doesn't forward TCP traffic to my upstream ejabberd image giving 400 errors inside the nginx container.

Looking at the NGINX docs it seems to perform TCP load balancing the default.conf file needs to contain a `stream` block and specific TCP port which is not being generated in my default.conf file.

Example TCP config: 

```
stream {
    upstream ssh {
        server 192.168.1.12:22;
    }
        server {
        listen        12345;
        proxy_pass    ssh;

    }

}
```

**Snippets**

Below are the `docker-compose.yml` and auto generated `conf.d/default.conf`:

```
  version: '2'
  services: 
   ejabberd:
     image: rroemhild/ejabberd
     expose:
      - 8000
     depends_on:
      - nginx
     environment:
      - EJABBERD_LOGLEVEL=4
      - VIRTUAL_HOST=dockertestingvm
      - SERVER_HOSTNAME=dockertestingvm  
      - XMPP_DOMAIN=dockertestingvm 
      - ERLANG_NODE=ejabberd 
      - EJABBERD_ADMINS=admin@dockertestingvm admin2@dockertestingvm 
      - EJABBERD_USERS=admin@dockertestingvm:password1234 admin2@dockertestingvm:admin
      - TZ=Europe/Berlin 
      - EJABBERD_SKIP_MODULES_UPDATE=true
   nginx:
     image: jwilder/nginx-proxy
     volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro  
     ports:
      - 5222:5222
     environment:
      - VIRTUAL_PORT=5222
```

```
# If we receive X-Forwarded-Proto, pass it through; otherwise, pass along the
# scheme used to connect to this server
map $http_x_forwarded_proto $proxy_x_forwarded_proto {
  default $http_x_forwarded_proto;
  ''      $scheme;
}
# If we receive X-Forwarded-Port, pass it through; otherwise, pass along the
# server port the client connected to
map $http_x_forwarded_port $proxy_x_forwarded_port {
  default $http_x_forwarded_port;
  ''      $server_port;
}
# If we receive Upgrade, set Connection to "upgrade"; otherwise, delete any
# Connection header that may have been passed to this server
map $http_upgrade $proxy_connection {
  default upgrade;
  '' close;
}
# Apply fix for very long server names
server_names_hash_bucket_size 128;
# Default dhparam
ssl_dhparam /etc/nginx/dhparam/dhparam.pem;
# Set appropriate X-Forwarded-Ssl header
map $scheme $proxy_x_forwarded_ssl {
  default off;
  https on;
}
gzip_types text/plain text/css application/javascript application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript;
log_format vhost '$host $remote_addr - $remote_user [$time_local] '
                 '"$request" $status $body_bytes_sent '
                 '"$http_referer" "$http_user_agent"';
access_log off;
resolver 127.0.0.11;
# HTTP 1.1 support
proxy_http_version 1.1;
proxy_buffering off;
proxy_set_header Host $http_host;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection $proxy_connection;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $proxy_x_forwarded_proto;
proxy_set_header X-Forwarded-Ssl $proxy_x_forwarded_ssl;
proxy_set_header X-Forwarded-Port $proxy_x_forwarded_port;
# Mitigate httpoxy attack (see README for details)
proxy_set_header Proxy "";
server {
	server_name _; # This is just an invalid value which will never trigger on a real hostname.
	listen 80;
	access_log /var/log/nginx/access.log vhost;
	return 503;
}
# dockertestingvm
upstream dockertestingvm {
				## Can be connect with "ejabberdnode1_default" network
		# ejabberdnode1_ejabberd_1
		server 172.18.0.3 down;
}
server {
	server_name dockertestingvm;
	listen 80 ;
	access_log /var/log/nginx/access.log vhost;
	location / {
		proxy_pass http://dockertestingvm;
	}
}







```
