### ISSUE TITLE
Cannot connect to container with fastcgi

### ISSUE THREAD

**Issue by saesh** [jwilder/nginx-proxy#983]
I am having trouble getting fastcgi support to work which was  introduced in #863. I am using `jwilder/nginx-proxy:alpine` and `php:fpm-alpine` images for testing and I get this error in the logs of `nginx-proxy` and a `404` in the browser:

`FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream`

I am setting up the containers with Ansible:

```
- name: Pull php-fpm container
  docker_container:
    name: php-fpm
    image: php:fpm-alpine
    pull: true
    restart_policy: always
    ports:
      - "9000:9000"
    env:
      VIRTUAL_HOST: phpfpm.local
      VIRTUAL_ROOT: /var/www/html
      VIRTUAL_PORT: 9000
      VIRTUAL_PROTO: fastcgi
```

And the generated configuration in nginx looks like this:

```
# phpfpm.local
upstream phpfpm.local {
				## Can be connect with "bridge" network
			# php-fpm
			server 172.17.0.6:9000;
}
server {
	server_name phpfpm.local;
	listen 80 ;
	access_log /var/log/nginx/access.log vhost;
	include /etc/nginx/vhost.d/default;
	location / {
		root   /var/www/html;
		include fastcgi.conf;
		fastcgi_pass phpfpm.local;
	}
}
```

I placed a `index.php` with `phpinfo()` in `/var/www/html` and set permissions to `www-data`.

Any ideas how to debug this further?

**Comment by xgenvn** [comment]
I also met the same problem. It seems the fastcgi.conf not exists. You can try adding a fastcgi.conf in your root.
Please let me  know if it's working on your side:  https://gist.github.com/shadowhand/321689

**Comment by saesh** [comment]
Hey @xgenvn, thanks for your suggestion but there is already a `fastcgi.conf` in the `nginx-proxy` container which should be used by the configuration above. You can examine it in the `/etc/nginx` directory inside the `nginx-proxy` container:

`docker exec -ti nginx-proxy cat /etc/nginx/fastcgi.conf`

**Comment by saesh** [comment]
This seems to be just a configuration issue of the virtual host and not an issue with the fast cgi configuration of the `nginx-proxy` container. The above configuration works fine. All I had to do was to append `/index.php` to my URL. So the next step would be to configure `fastcgi_index` or similar to the virtual host.

**Comment by saesh** [comment]
Just for completion: I added a virtual host specific location configuration file in `/etc/nginx/vhost.d/phpfpm.local_location` with just one line: `fastcgi_index index.php;` and now all works as intended. See [per-virtual_host-location-configuration](https://github.com/jwilder/nginx-proxy#per-virtual_host-location-configuration) in the README.

**Comment by xgenvn** [comment]
@saesh actually I'm using [repo](https://github.com/evertramos/docker-compose-letsencrypt-nginx-proxy-companion/) and it referenced directly from this image for the template. I checked the nginx configuration but there're no fastcgi.conf in nginx folder. I'll fire an issue on that repo instead ;).

**Comment by qiqizjl** [comment]
@xgenvn  Sorry, I'm late. Fastcgi.conf should be nginx comes with the configuration file. If you find an error, you can provide the next nginx version and the Docker image name

**Comment by qiqizjl** [comment]
This is indeed my negligence caused. In my project, I added a rewrite, did not find this problem. I will consider fixing it as soon as possible.
~~~
 rewrite ^/(.*)$ /index.php?_url=/$1;
~~~

**Comment by HalisCz** [comment]
I am facing the same issue as xgenvn:
> I also met the same problem. It seems the fastcgi.conf not exists. You can try adding a fastcgi.conf in your root.

Here you can see state of container:
```
# docker exec -ti nginx-proxy cat /etc/nginx/fastcgi.conf
cat: /etc/nginx/fastcgi.conf: No such file or directory
```
```
# docker exec -ti nginx-proxy nginx -t
2018/03/19 11:41:25 [emerg] 56#56: open() "/etc/nginx/fastcgi.conf" failed (2: No such file or directory) in /etc/nginx/conf.d/default.conf:101
nginx: [emerg] open() "/etc/nginx/fastcgi.conf" failed (2: No such file or directory) in /etc/nginx/conf.d/default.conf:101
nginx: configuration file /etc/nginx/nginx.conf test failed
```

**Comment by jinfeei** [comment]
Hi @saesh, can you please elaborate on your solution? You have solved the problem you raised above right? Thanks...

**Comment by qiqizjl** [comment]
@saesh @HalisCz  Hello, this bug has been resolved. See #1116

**Comment by Divxtaman** [comment]
This bug still exists 
```
docker exec -ti nginx-proxy nginx -t
2018/11/26 23:35:56 [emerg] 17#17: open() "/etc/nginx/fastcgi.conf" failed (2: No such file or directory) in /etc/nginx/conf.d/default.conf:73
nginx: [emerg] open() "/etc/nginx/fastcgi.conf" failed (2: No such file or directory) in /etc/nginx/conf.d/default.conf:73
nginx: configuration file /etc/nginx/nginx.conf test failed
```

**Comment by qiqizjl** [comment]
@Divxtaman hello fix in #1116 .But not yet merged

**Comment by Divxtaman** [comment]
@qiqizjl  thanks since I don't see it being merged yet so I followed @xgenvn above, changed image to php:fpm-alpine version, But still I was having issue, in the browser I received 'File not found' error, then I placed a file in /etc/nginx/vhost.d/domain.com_location with content `fastcgi_index index.php;` , restarted nginx-proxy and it started to work.

**Comment by i3c-cloud** [comment]
I've added this line in my custom dockerfile (FROM jwilder/nginx-proxy:alpine):

`RUN echo "fastcgi_index index.php;" >> /etc/nginx/fastcgi.conf`

Works but it would be good to have something like "-e VIRTUAL_INDEX=index.php"

**Comment by tarikhagustia** [comment]
same issue here, i'm using this conf
```
version: '2'
services:
    proxy:
        image: jwilder/nginx-proxy
        ports:
            - "80:80"
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro

    fpm:
        image: php:fpm-alpine
        volumes:
          - ./sites:/var/www/html
        environment:
            - VIRTUAL_HOST=whoami.local
            - VIRTUAL_ROOT=/var/www/html
            - VIRTUAL_PORT=9000
            - VIRTUAL_PROTO=fastcgi
```
when trying access to browser, blank response, any ideas?

**Comment by SturmB** [comment]
There is no Google Group in which I could seek help, so I'm posting here.

I do not know what I am doing wrong. I have created a `docker-compose.yml` file like so:

```yaml
# docker-compose.yml

version: "2"
services:
  proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./docker-config/nginx/vhost.d:/etc/nginx/vhost.d
    networks:
      main-web:

  fpm:
    image: php:fpm-alpine
    volumes:
      - ./site:/var/www/html
    environment:
      - VIRTUAL_HOST=whoami.local
      - VIRTUAL_ROOT=/var/www/html
      - VIRTUAL_PORT=9000
      - VIRTUAL_PROTO=fastcgi
    ports:
      - 9000
    networks:
      main-web:

networks:
  main-web:
```

In the `./docker-config/nginx/vhost.d` directory is a single file, `whoami.local_location`, with the contents:

```nginx
# ./docker-config/nginx/vhost.d/whoami.local_location

fastcgi_index index.php;
```

and in `./site` is just a simple file, `index.php` with the following:

```php
# ./site/index.php

<?php
phpinfo();
?>
```

Finally, because `fpm`'s `VIRTUAL_HOST` environment variable is set to `whoami.local`, I update my computer's `hosts` file to redirect `whoami.local` to `127.0.0.1`. (Please let me know if any of these steps are incorrect.)

Navigating my browser to `http://whoami.local` results in nothing but a blank, white page. What am I doing wrong?

**Comment by songhanpoo** [comment]
> same issue here, i'm using this conf
> 
> ```
> version: '2'
> services:
>     proxy:
>         image: jwilder/nginx-proxy
>         ports:
>             - "80:80"
>         volumes:
>             - /var/run/docker.sock:/tmp/docker.sock:ro
> 
>     fpm:
>         image: php:fpm-alpine
>         volumes:
>           - ./sites:/var/www/html
>         environment:
>             - VIRTUAL_HOST=whoami.local
>             - VIRTUAL_ROOT=/var/www/html
>             - VIRTUAL_PORT=9000
>             - VIRTUAL_PROTO=fastcgi
> ```
> 
> when trying access to browser, blank response, any ideas?

i have same issue, anything idea for that ?

**Comment by execut** [comment]
> > same issue here, i'm using this conf
> > ```
> > version: '2'
> > services:
> >     proxy:
> >         image: jwilder/nginx-proxy
> >         ports:
> >             - "80:80"
> >         volumes:
> >             - /var/run/docker.sock:/tmp/docker.sock:ro
> > 
> >     fpm:
> >         image: php:fpm-alpine
> >         volumes:
> >           - ./sites:/var/www/html
> >         environment:
> >             - VIRTUAL_HOST=whoami.local
> >             - VIRTUAL_ROOT=/var/www/html
> >             - VIRTUAL_PORT=9000
> >             - VIRTUAL_PROTO=fastcgi
> > ```
> > 
> > 
> > when trying access to browser, blank response, any ideas?
> 
> i have same issue, anything idea for that ?

I solved the problem by replace the file fastcgi_params to own:
```
fastcgi_split_path_info ^(.+\.php)(.*)$;
fastcgi_index  index.php;

fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
fastcgi_param  PATH_TRANSLATED  /$fastcgi_script_name;
fastcgi_param  HTTP_HOST        $server_name;

fastcgi_keep_conn on;
fastcgi_intercept_errors        on;
fastcgi_ignore_client_abort     off;
fastcgi_connect_timeout 100000;
fastcgi_send_timeout 100000;
fastcgi_read_timeout 100000;
fastcgi_buffer_size 256k;
fastcgi_buffers 4 256k;
fastcgi_busy_buffers_size 256k;
fastcgi_temp_file_write_size 256k;

fastcgi_param  QUERY_STRING       $query_string;
fastcgi_param  REQUEST_METHOD     $request_method;
fastcgi_param  CONTENT_TYPE       $content_type;
fastcgi_param  CONTENT_LENGTH     $content_length;

fastcgi_param  SCRIPT_NAME        $fastcgi_script_name;
fastcgi_param  REQUEST_URI        $request_uri;
fastcgi_param  DOCUMENT_URI       $document_uri;
fastcgi_param  DOCUMENT_ROOT      $document_root;
fastcgi_param  SERVER_PROTOCOL    $server_protocol;
fastcgi_param  REQUEST_SCHEME     $scheme;
fastcgi_param  HTTPS              $https if_not_empty;

fastcgi_param  GATEWAY_INTERFACE  CGI/1.1;
fastcgi_param  SERVER_SOFTWARE    nginx/$nginx_version;

fastcgi_param  REMOTE_ADDR        $remote_addr;
fastcgi_param  REMOTE_PORT        $remote_port;
fastcgi_param  SERVER_ADDR        $server_addr;
fastcgi_param  SERVER_PORT        $server_port;
fastcgi_param  SERVER_NAME        $server_name;

# PHP only, required if PHP was built with --enable-force-cgi-redirect
fastcgi_param  REDIRECT_STATUS    200;
```

build.dockerfile:
```
FROM  jwilder/nginx-proxy:latest
COPY fastcgi_params /etc/nginx/
```
add build section to proxy docker-composer.yml:
```
services:
  nginx-proxy:
    build:
      context: .
      dockerfile: build.dockerfile
```

**Comment by smil2k** [comment]
Same for me, the new fastcgi_params did the trick. I'm using docker file mounts to replace, this spares one container layer.

```
  nginx-proxy:                                                                                                                                                                               
    image: nginxproxy/nginx-proxy                                                                                                                                                            
    ports:                                                                                                                                                                                   
      - "80:80"                                                                                                                                                                              
      - "443:443"                                                                                                                                                                            
    volumes:                                                                                                                                                                                 
      - /var/run/docker.sock:/tmp/docker.sock:ro                                                                                                                                             
      - ./php/fastcgi_params:/etc/nginx/fastcgi_params    
```
