### ISSUE TITLE
[Question] Multiple services with different ports and the same domain

### ISSUE THREAD

**Issue by vtvz** [jwilder/nginx-proxy#986]
And I have some services in docker-compose:

```yaml
version: "3"
services:
  site:
    volumes:
      - .:/app
    build:
      dockerfile: Dockerfile.dev
      context: docker
    ports:
      - "80:80"

  webpack:
    image: node:6.12.0
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    working_dir: /app
    command: bash -c "yarn install; yarn run gulp server"
  db:
    image: mysql:5.7.20
    ports: 
      - "3306:3306"
  environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
```

And I can connect to exposed ports of services:

- Site -- localhost:80
- Webpack  -- localhost:8080
- MySQL:  -- localhost:3306

How can I use nginx-proxy to expose multiple ports of different servers on the same domain (?):

- Site -- example.dev:80
- Webpack  -- example.dev:8080
- MySQL:  -- example.dev:3306

This works:

```yaml
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  site:
    volumes:
      - .:/app
    build:
      dockerfile: Dockerfile.dev
      context: docker
    expose:
      - 80
    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST}
```

But this is not:
```yaml
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  site:
    volumes:
      - .:/app
    build:
      dockerfile: Dockerfile.dev
      context: docker
    expose:
      - 80
    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST}

  webpack:
    image: node:6.12.0
    expose:
      - 8080
    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      VIRTUAL_PORT: 8080
    volumes:
      - .:/app
    working_dir: /app
    command: bash -c "yarn install; yarn run gulp server"
```

What am I do wrong? How can I solve this problem?

`//Sorry for my worst English. Hope you'll understand me`

**Comment by leoddias** [comment]
If you are running all container in the same host of the reverse proxy, you just must put the port of a container, your dns should do it for you.
`
  site:
    volumes:
      - .:/app
    build:
      dockerfile: Dockerfile.dev
      context: docker
    ports:
      - "8080:80"
    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST}
`

**Comment by devevderyadav** [comment]
Hi @vtvz ,
  were you able to figure that out?  I know this can be solved by using subdomain

**Comment by S0PEX** [comment]
Hey,

I don't want to create a new issue but currently I am deploying an NextJs Webapp with the corresponding Java Restapi.
The main app should run on the domain.local and the rest api under domain.local:8080, with this config the service seems to run fine but sometimes fails on refresh because I guess the data is routed into the wrong container.

My docker-compose.yml:
```yml
version: '2'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  server:
    image: timetables-server
    environment:
      VIRTUAL_HOST: domain.local
      VIRTUAL_PORT: 8080
    ports:
      - "8080:8080"
    volumes:
      - ./config:/config/

  webapp:
    image: timetables-webapp
    environment:
      VIRTUAL_HOST: domain.local
      VIRTUAL_PORT: 3000
 ```  

Is it possible to configure this correctly or is this an issue with my frontend application ?

Regards Artur
