### ISSUE TITLE
Feature Proposal: Opt-in support for HEALTHCHECK option 

### ISSUE THREAD

**Issue by bhurlow** [jwilder/nginx-proxy#987]
Hello!

I've been using `nginx-proxy` with some great results for over a year, nice job.
Docker now supports the [healthcheck](https://docs.docker.com/engine/reference/builder/#healthcheck) option which, at least for my use case, is a better indication of whether a container should be receiving proxied traffic. I'm wondering if the health status could be considered by `nginx-proxy` along side the regular container lifecycle.  

Anyone else looking for this? 
Thanks!

**Comment by jamiejackson** [comment]
I had mistakenly assumed that this is how it already worked but now that I am implementing a proper health on the proxied service, I seem to see nginx-proxy attempting to connect before the other service is healthy, leading to errors.

Is that the situation you're describing @bhurlow?

My service takes a long time (up to ~90s) to become healthy. For swarm, itself, that's not a big deal, as swarm waits for the container(s) to come up before taking down the old one(s). So for swarm, there's no down time, but nginx-proxy seems to be introducing its own disruption.

**Comment by bhurlow** [comment]
@jakejarvis yea that's correct as far as I know. `nginx-proxy` users the docker lifecycle events to reload the nginx config when a new container _starts_, it does not check health ala kubernetes

**Comment by aareman** [comment]
Here is a possible workaround. By using `DOCKER_CONTAINER_FILTERS` (https://github.com/nginx-proxy/nginx-proxy/tree/main/docs#filtering-containers) 

One can do 
```yml
#...
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    environment:
      DOCKER_CONTAINER_FILTERS: "health=none,health=healthy"
    restart: unless-stopped
    volumes:
      - dhparam:/etc/nginx/dhparam
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /var/log/nginx:/var/log/nginx
#...
```
I can't confirm how much this helps. There is still a lag in the deploy on my end, but none of the requests time out.
