### ISSUE TITLE
Plex not loading image posters on Android devices

### ISSUE THREAD

**Issue by l3uddz** [jwilder/nginx-proxy#989]
Trying to locate the source of an issue. 
Recently upgraded nginx-proxy to the latest build and was presented with an issue where plex was not loading posters for anything. Looking at logs it appears the android clients are trying to load images on http:// 443. 

This is only occurring on Android devices, and it continues to work perfectly fine with the build: ```sha256:76d9ed11c131fadc7546e3b9b085970e13ff45186171b975ad60830f5ca0d689```

You can see how I am creating the container at https://github.com/Cloudbox/Cloudbox/blob/master/roles/plex/tasks/main.yml

Is there anything obvious I should be looking at to fix this issue on the newer nginx-proxy builds?

**Comment by juliienp** [comment]
Same for me... maybe websocket ?

**Comment by juliienp** [comment]
Maybe @jwilder can help us ?
I found this topic but didn't understand if I have to make a custom nginx to deal with my plex container or I have to modify the nginx-proxy configuration..

Here's my plex definition :
```
    plex:
        image: plexinc/pms-docker
        container_name: "plex"
        restart: always
        expose:
            - 32400
        volumes:
          - /docker/container/plex/config:/config
          - /docker/container/plex/temp:/transcode
          - /data/srv/data:/data
          - /data/srv2/data:/data2
        environment:
            VIRTUAL_HOST: plex.***.fr
            LETSENCRYPT_HOST: plex.***.fr
            LETSENCRYPT_EMAIL: **@**.fr
            VIRTUAL_PORT: 32400
            TZ: Europe/Paris
        network_mode: webproxy
```
