### ISSUE TITLE
Nginx-proxy in docker-compose and `$ docker run -e VIRTUAL_HOST=foo.bar.com  ...` gives empty upstream

### ISSUE THREAD

**Issue by laurenskling** [jwilder/nginx-proxy#997]
When i start nginx-proxy with compose, because i like to manage the companion with it, everything works alright; But when i add dockers with VIRTUAL_HOST's, they are added but without upstream, so not working.

config:
```
version: '2'

services:
  proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - '8080:80'
      - '443:443'
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html # to write challenge files
      - /apps/web/ssl:/etc/nginx/certs:ro # update this to change cert location

  ssl-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: ssl-companion
    volumes:
      - /apps/web/ssl:/etc/nginx/certs:rw # same path as above, now RW
      - /var/run/docker.sock:/var/run/docker.sock:ro
    volumes_from:
      - proxy
    depends_on:
      - proxy

  whoami:
    image: jwilder/whoami
    environment:
      - VIRTUAL_HOST=whoami.local
```

add new docker:
`docker run -d -e VIRTUAL_HOST=test.local test-project`

gives a config like:
```
root@dcc1ae4b6de3:/app# cat /etc/nginx/conf.d/default.conf 
[.....]
# test.local
upstream test.local {
}
server {
	server_name test.local;
	listen 80 ;
	access_log /var/log/nginx/access.log vhost;
	location / {
		proxy_pass http://test.local;
	}
}
# whoami.local
upstream whoami.local {
				## Can be connect with "compose_default" network
			# compose_whoami_1
			server 172.20.0.3:8000;
}
server {
	server_name whoami.local;
	listen 80 ;
	access_log /var/log/nginx/access.log vhost;
	location / {
		proxy_pass http://whoami.local;
	}
}
```

**Comment by DanielRedOak** [comment]
I was just going through the process and ran into the same issue when using compose. Any traction on finding the root cause?

**Comment by laurenskling** [comment]
Nope. Only when you add projects in the compose it works correctly. I moved my experiment to Docker Cloud instead of Compose, so I stopped looking into it.

**Comment by gscalise** [comment]
I struggled with this until I found the cause: containers running in the same compose stack share the same network and, thus, are reachable by the nginx-proxy container, but when you launch other containers in other stacks (or as standalone containers) you have to bind them to the same network as the nginx-proxy container, or else it will be as if they are running totally isolated from each other.

The way I've resolved this is by creating a docker network outside both compose projects:

`docker network create local_frontend`

Then on the nginx-proxy compose I've added `local_frontend` as the default network:

```yaml
(...)
networks:
  default:
    external:
      name: local_frontend
```

And on my project I created two networks, one for the backend (database + redis) and one for the frontend (app server), with the app server bound to both the backend network and the frontend network:

Networks section:
```yaml
networks:
  frontend:
    external:
      name: local_frontend
  backend:
    driver: bridge
```

App Server:
```yaml
services:
  app:
    (...)
    networks:
      - frontend
      - backend
```

Redis:
```yaml
redis:
  image: "redis:alpine"
  networks:
    - backend
```

Database:
```yaml
db:
  image: "mariadb:10.2.11"
  networks:
    - backend
```
