### ISSUE TITLE
Howto proxy an app running without docker

### ISSUE THREAD

**Issue by caplod** [jwilder/nginx-proxy#998]
I have a app thats running locally on port 3000 without docker.
Is it possible to proxy that app as well?

I am running nginx-proxy like this:

`docker run --rm -p 80:80 -p 443:443 -v /srv/vhost.d:/etc/nginx/vhost.d:ro -v /var/run/docker.sock:/tmp/docker.sock:ro jwilder/nginx-proxy`

and have the following file:
```
# /srv/vhost.d/testdomain.dev_location
proxy_pass http://10.0.15.21:3000;
```

in the generated /etc/nginx/conf.d/default.conf however I dont see anything.

**Comment by Panderine** [comment]
I'm on the same path. I tried creating a full "virtual host" name on vhost.d with a server block and nothing happens. I wan't to proxy to an application running on the host OS and outside docker.

**Comment by fmanzke** [comment]
see #646

I connected nginx-proxy running in docker with [netdata](https://my-netdata.io/) running the host machine port 19999 via https://hub.docker.com/r/tynor88/socat/
`docker run --name=socat -e LISTEN_PORT=80 -e FORWARD_PORT=19999 -e VIRTUAL_HOST=host.example.com -e VIRTUAL_PORT=80 tynor88/socat`

**Comment by samara8609** [comment]
@fmanzke i've done this, but seem to have a problem with forwarding to apps that need cookies(pfsense and esxi).  Have you ran into this issue at all?

**Comment by Panderine** [comment]
I can't make it work. I use --expose to reverse proxy from nginx to my app-outside-docker but not luck.

**Comment by CWempe** [comment]
I solved this by editing the template to support a new variable with a dummy container.

new Template: https://github.com/CWempe/nginx-proxy/blob/upstream_name/nginx.tmpl
README: https://github.com/CWempe/nginx-proxy/tree/upstream_name#non-docker-host

Pull Request: https://github.com/jwilder/nginx-proxy/pull/1100

**Comment by bkraul** [comment]
@jwilder Could you please look into this? It would be awesome to have this functionality.

**Comment by chimera27** [comment]
@CWempe Hi, i have a non-docker deluge running on port 20000. This is my docker compose for it to benefit from nginx proxy, however i can't seem to make it work:

version: '2'

services:
    dummy:
        image: cwempe/docker-dummy:latest
        container_name: dummy
        restart: always
        environment:
            VIRTUAL_HOST: deluge.chimerako.com
            VIRTUAL_PORT: 20000
            UPSTREAM_NAME: https://185.107.80.2:20000

networks:
  default:
    external:
      name: nginx-proxy

**Comment by CWempe** [comment]
The first difference I see is you defined the whole URL in `UPSTREAM_NAME`.
Just try `185.107.80.2` without `https://` and `:20000`.

And take a look in the generated `nginx-conf/_data/default.conf`if that looks ok to you.
Or post the content of the file (or a part of it) for us.

**Comment by roboxv** [comment]
Here is my workaround

```
version: '3'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"

  someserviceonhost:
    restart: on-failure
    image: qoomon/docker-host
    cap_add: [ 'NET_ADMIN', 'NET_RAW' ]
    expose:
      - "8080"
    environment:
      - VIRTUAL_HOST=subdomain.domain.tld

```

`docker-host` is an image that proxies to host machine

**Comment by amosipov** [comment]
You could just add your non-docker proxy config files to `/etc/nginx/conf.d/` by mounting them as a volume. Config filenames must end with `.conf`.

**Comment by galeksandrp** [comment]
Note to my future self: in 2024 it is better to:
```
   dummyweb:
    image: alpine
    restart: always
    command: tail -f /dev/null
    environment:
      VIRTUAL_HOST: web.example.com
      LETSENCRYPT_HOST: web.example.com
```
and then `/etc/nginx/vhost.d/web.example.com_location_override`
```
location / {
    proxy_pass http://192.168.1.1:80;
    auth_basic "web.example.com";
    auth_basic_user_file /etc/nginx/htpasswd/web.example.com;
}
```
